// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class AncientGreekMusicalNotation
    {
        public enum OtherSymbol : int
        {
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-1 𝈀
            /// </summary>
            GreekVocalNotationSymbol1 = 0x1D200,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-2 𝈁
            /// </summary>
            GreekVocalNotationSymbol2 = 0x1D201,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-3 𝈂
            /// </summary>
            GreekVocalNotationSymbol3 = 0x1D202,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-4 𝈃
            /// </summary>
            GreekVocalNotationSymbol4 = 0x1D203,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-5 𝈄
            /// </summary>
            GreekVocalNotationSymbol5 = 0x1D204,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-6 𝈅
            /// </summary>
            GreekVocalNotationSymbol6 = 0x1D205,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-7 𝈆
            /// </summary>
            GreekVocalNotationSymbol7 = 0x1D206,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-8 𝈇
            /// </summary>
            GreekVocalNotationSymbol8 = 0x1D207,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-9 𝈈
            /// </summary>
            GreekVocalNotationSymbol9 = 0x1D208,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-10 𝈉
            /// </summary>
            GreekVocalNotationSymbol10 = 0x1D209,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-11 𝈊
            /// </summary>
            GreekVocalNotationSymbol11 = 0x1D20A,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-12 𝈋
            /// </summary>
            GreekVocalNotationSymbol12 = 0x1D20B,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-13 𝈌
            /// </summary>
            GreekVocalNotationSymbol13 = 0x1D20C,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-14 𝈍
            /// </summary>
            GreekVocalNotationSymbol14 = 0x1D20D,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-15 𝈎
            /// </summary>
            GreekVocalNotationSymbol15 = 0x1D20E,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-16 𝈏
            /// </summary>
            GreekVocalNotationSymbol16 = 0x1D20F,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-17 𝈐
            /// </summary>
            GreekVocalNotationSymbol17 = 0x1D210,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-18 𝈑
            /// </summary>
            GreekVocalNotationSymbol18 = 0x1D211,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-19 𝈒
            /// </summary>
            GreekVocalNotationSymbol19 = 0x1D212,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-20 𝈓
            /// </summary>
            GreekVocalNotationSymbol20 = 0x1D213,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-21 𝈔
            /// </summary>
            GreekVocalNotationSymbol21 = 0x1D214,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-22 𝈕
            /// </summary>
            GreekVocalNotationSymbol22 = 0x1D215,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-23 𝈖
            /// </summary>
            GreekVocalNotationSymbol23 = 0x1D216,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-24 𝈗
            /// </summary>
            GreekVocalNotationSymbol24 = 0x1D217,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-50 𝈘
            /// </summary>
            GreekVocalNotationSymbol50 = 0x1D218,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-51 𝈙
            /// </summary>
            GreekVocalNotationSymbol51 = 0x1D219,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-52 𝈚
            /// </summary>
            GreekVocalNotationSymbol52 = 0x1D21A,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-53 𝈛
            /// </summary>
            GreekVocalNotationSymbol53 = 0x1D21B,
            /// <summary>
            /// GREEK VOCAL NOTATION SYMBOL-54 𝈜
            /// </summary>
            GreekVocalNotationSymbol54 = 0x1D21C,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-1 𝈝
            /// </summary>
            GreekInstrumentalNotationSymbol1 = 0x1D21D,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-2 𝈞
            /// </summary>
            GreekInstrumentalNotationSymbol2 = 0x1D21E,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-4 𝈟
            /// </summary>
            GreekInstrumentalNotationSymbol4 = 0x1D21F,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-5 𝈠
            /// </summary>
            GreekInstrumentalNotationSymbol5 = 0x1D220,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-7 𝈡
            /// </summary>
            GreekInstrumentalNotationSymbol7 = 0x1D221,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-8 𝈢
            /// </summary>
            GreekInstrumentalNotationSymbol8 = 0x1D222,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-11 𝈣
            /// </summary>
            GreekInstrumentalNotationSymbol11 = 0x1D223,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-12 𝈤
            /// </summary>
            GreekInstrumentalNotationSymbol12 = 0x1D224,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-13 𝈥
            /// </summary>
            GreekInstrumentalNotationSymbol13 = 0x1D225,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-14 𝈦
            /// </summary>
            GreekInstrumentalNotationSymbol14 = 0x1D226,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-17 𝈧
            /// </summary>
            GreekInstrumentalNotationSymbol17 = 0x1D227,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-18 𝈨
            /// </summary>
            GreekInstrumentalNotationSymbol18 = 0x1D228,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-19 𝈩
            /// </summary>
            GreekInstrumentalNotationSymbol19 = 0x1D229,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-23 𝈪
            /// </summary>
            GreekInstrumentalNotationSymbol23 = 0x1D22A,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-24 𝈫
            /// </summary>
            GreekInstrumentalNotationSymbol24 = 0x1D22B,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-25 𝈬
            /// </summary>
            GreekInstrumentalNotationSymbol25 = 0x1D22C,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-26 𝈭
            /// </summary>
            GreekInstrumentalNotationSymbol26 = 0x1D22D,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-27 𝈮
            /// </summary>
            GreekInstrumentalNotationSymbol27 = 0x1D22E,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-29 𝈯
            /// </summary>
            GreekInstrumentalNotationSymbol29 = 0x1D22F,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-30 𝈰
            /// </summary>
            GreekInstrumentalNotationSymbol30 = 0x1D230,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-32 𝈱
            /// </summary>
            GreekInstrumentalNotationSymbol32 = 0x1D231,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-36 𝈲
            /// </summary>
            GreekInstrumentalNotationSymbol36 = 0x1D232,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-37 𝈳
            /// </summary>
            GreekInstrumentalNotationSymbol37 = 0x1D233,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-38 𝈴
            /// </summary>
            GreekInstrumentalNotationSymbol38 = 0x1D234,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-39 𝈵
            /// </summary>
            GreekInstrumentalNotationSymbol39 = 0x1D235,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-40 𝈶
            /// </summary>
            GreekInstrumentalNotationSymbol40 = 0x1D236,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-42 𝈷
            /// </summary>
            GreekInstrumentalNotationSymbol42 = 0x1D237,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-43 𝈸
            /// </summary>
            GreekInstrumentalNotationSymbol43 = 0x1D238,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-45 𝈹
            /// </summary>
            GreekInstrumentalNotationSymbol45 = 0x1D239,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-47 𝈺
            /// </summary>
            GreekInstrumentalNotationSymbol47 = 0x1D23A,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-48 𝈻
            /// </summary>
            GreekInstrumentalNotationSymbol48 = 0x1D23B,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-49 𝈼
            /// </summary>
            GreekInstrumentalNotationSymbol49 = 0x1D23C,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-50 𝈽
            /// </summary>
            GreekInstrumentalNotationSymbol50 = 0x1D23D,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-51 𝈾
            /// </summary>
            GreekInstrumentalNotationSymbol51 = 0x1D23E,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-52 𝈿
            /// </summary>
            GreekInstrumentalNotationSymbol52 = 0x1D23F,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-53 𝉀
            /// </summary>
            GreekInstrumentalNotationSymbol53 = 0x1D240,
            /// <summary>
            /// GREEK INSTRUMENTAL NOTATION SYMBOL-54 𝉁
            /// </summary>
            GreekInstrumentalNotationSymbol54 = 0x1D241,
            /// <summary>
            /// GREEK MUSICAL LEIMMA 𝉅
            /// </summary>
            GreekMusicalLeimma = 0x1D245
        }
        public enum NonSpacingMark : int
        {
            /// <summary>
            /// COMBINING GREEK MUSICAL TRISEME 𝉂
            /// </summary>
            CombiningGreekMusicalTriseme = 0x1D242,
            /// <summary>
            /// COMBINING GREEK MUSICAL TETRASEME 𝉃
            /// </summary>
            CombiningGreekMusicalTetraseme = 0x1D243,
            /// <summary>
            /// COMBINING GREEK MUSICAL PENTASEME 𝉄
            /// </summary>
            CombiningGreekMusicalPentaseme = 0x1D244
        }
    }
}
