// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class MathematicalOperators
    {
        public enum MathSymbol : int
        {
            /// <summary>
            /// FOR ALL ∀
            /// </summary>
            ForAll = 0x2200,
            /// <summary>
            /// COMPLEMENT ∁
            /// </summary>
            Complement = 0x2201,
            /// <summary>
            /// PARTIAL DIFFERENTIAL ∂
            /// </summary>
            PartialDifferential = 0x2202,
            /// <summary>
            /// THERE EXISTS ∃
            /// </summary>
            ThereExists = 0x2203,
            /// <summary>
            /// THERE DOES NOT EXIST ∄
            /// </summary>
            ThereDoesNotExist = 0x2204,
            /// <summary>
            /// EMPTY SET ∅
            /// </summary>
            EmptySet = 0x2205,
            /// <summary>
            /// INCREMENT ∆
            /// </summary>
            Increment = 0x2206,
            /// <summary>
            /// NABLA ∇
            /// </summary>
            Nabla = 0x2207,
            /// <summary>
            /// ELEMENT OF ∈
            /// </summary>
            ElementOf = 0x2208,
            /// <summary>
            /// NOT AN ELEMENT OF ∉
            /// </summary>
            NotAnElementOf = 0x2209,
            /// <summary>
            /// SMALL ELEMENT OF ∊
            /// </summary>
            SmallElementOf = 0x220A,
            /// <summary>
            /// CONTAINS AS MEMBER ∋
            /// </summary>
            ContainsAsMember = 0x220B,
            /// <summary>
            /// DOES NOT CONTAIN AS MEMBER ∌
            /// </summary>
            DoesNotContainAsMember = 0x220C,
            /// <summary>
            /// SMALL CONTAINS AS MEMBER ∍
            /// </summary>
            SmallContainsAsMember = 0x220D,
            /// <summary>
            /// END OF PROOF ∎
            /// </summary>
            EndOfProof = 0x220E,
            /// <summary>
            /// N-ARY PRODUCT ∏
            /// </summary>
            NAryProduct = 0x220F,
            /// <summary>
            /// N-ARY COPRODUCT ∐
            /// </summary>
            NAryCoproduct = 0x2210,
            /// <summary>
            /// N-ARY SUMMATION ∑
            /// </summary>
            NArySummation = 0x2211,
            /// <summary>
            /// MINUS SIGN −
            /// </summary>
            MinusSign = 0x2212,
            /// <summary>
            /// MINUS-OR-PLUS SIGN ∓
            /// </summary>
            MinusOrPlusSign = 0x2213,
            /// <summary>
            /// DOT PLUS ∔
            /// </summary>
            DotPlus = 0x2214,
            /// <summary>
            /// DIVISION SLASH ∕
            /// </summary>
            DivisionSlash = 0x2215,
            /// <summary>
            /// SET MINUS ∖
            /// </summary>
            SetMinus = 0x2216,
            /// <summary>
            /// ASTERISK OPERATOR ∗
            /// </summary>
            AsteriskOperator = 0x2217,
            /// <summary>
            /// RING OPERATOR ∘
            /// </summary>
            RingOperator = 0x2218,
            /// <summary>
            /// BULLET OPERATOR ∙
            /// </summary>
            BulletOperator = 0x2219,
            /// <summary>
            /// SQUARE ROOT √
            /// </summary>
            SquareRoot = 0x221A,
            /// <summary>
            /// CUBE ROOT ∛
            /// </summary>
            CubeRoot = 0x221B,
            /// <summary>
            /// FOURTH ROOT ∜
            /// </summary>
            FourthRoot = 0x221C,
            /// <summary>
            /// PROPORTIONAL TO ∝
            /// </summary>
            ProportionalTo = 0x221D,
            /// <summary>
            /// INFINITY ∞
            /// </summary>
            Infinity = 0x221E,
            /// <summary>
            /// RIGHT ANGLE ∟
            /// </summary>
            RightAngle = 0x221F,
            /// <summary>
            /// ANGLE ∠
            /// </summary>
            Angle = 0x2220,
            /// <summary>
            /// MEASURED ANGLE ∡
            /// </summary>
            MeasuredAngle = 0x2221,
            /// <summary>
            /// SPHERICAL ANGLE ∢
            /// </summary>
            SphericalAngle = 0x2222,
            /// <summary>
            /// DIVIDES ∣
            /// </summary>
            Divides = 0x2223,
            /// <summary>
            /// DOES NOT DIVIDE ∤
            /// </summary>
            DoesNotDivide = 0x2224,
            /// <summary>
            /// PARALLEL TO ∥
            /// </summary>
            ParallelTo = 0x2225,
            /// <summary>
            /// NOT PARALLEL TO ∦
            /// </summary>
            NotParallelTo = 0x2226,
            /// <summary>
            /// LOGICAL AND ∧
            /// </summary>
            LogicalAnd = 0x2227,
            /// <summary>
            /// LOGICAL OR ∨
            /// </summary>
            LogicalOr = 0x2228,
            /// <summary>
            /// INTERSECTION ∩
            /// </summary>
            Intersection = 0x2229,
            /// <summary>
            /// UNION ∪
            /// </summary>
            Union = 0x222A,
            /// <summary>
            /// INTEGRAL ∫
            /// </summary>
            Integral = 0x222B,
            /// <summary>
            /// DOUBLE INTEGRAL ∬
            /// </summary>
            DoubleIntegral = 0x222C,
            /// <summary>
            /// TRIPLE INTEGRAL ∭
            /// </summary>
            TripleIntegral = 0x222D,
            /// <summary>
            /// CONTOUR INTEGRAL ∮
            /// </summary>
            ContourIntegral = 0x222E,
            /// <summary>
            /// SURFACE INTEGRAL ∯
            /// </summary>
            SurfaceIntegral = 0x222F,
            /// <summary>
            /// VOLUME INTEGRAL ∰
            /// </summary>
            VolumeIntegral = 0x2230,
            /// <summary>
            /// CLOCKWISE INTEGRAL ∱
            /// </summary>
            ClockwiseIntegral = 0x2231,
            /// <summary>
            /// CLOCKWISE CONTOUR INTEGRAL ∲
            /// </summary>
            ClockwiseContourIntegral = 0x2232,
            /// <summary>
            /// ANTICLOCKWISE CONTOUR INTEGRAL ∳
            /// </summary>
            AnticlockwiseContourIntegral = 0x2233,
            /// <summary>
            /// THEREFORE ∴
            /// </summary>
            Therefore = 0x2234,
            /// <summary>
            /// BECAUSE ∵
            /// </summary>
            Because = 0x2235,
            /// <summary>
            /// RATIO ∶
            /// </summary>
            Ratio = 0x2236,
            /// <summary>
            /// PROPORTION ∷
            /// </summary>
            Proportion = 0x2237,
            /// <summary>
            /// DOT MINUS ∸
            /// </summary>
            DotMinus = 0x2238,
            /// <summary>
            /// EXCESS ∹
            /// </summary>
            Excess = 0x2239,
            /// <summary>
            /// GEOMETRIC PROPORTION ∺
            /// </summary>
            GeometricProportion = 0x223A,
            /// <summary>
            /// HOMOTHETIC ∻
            /// </summary>
            Homothetic = 0x223B,
            /// <summary>
            /// TILDE OPERATOR ∼
            /// </summary>
            TildeOperator = 0x223C,
            /// <summary>
            /// REVERSED TILDE ∽
            /// </summary>
            ReversedTilde = 0x223D,
            /// <summary>
            /// INVERTED LAZY S ∾
            /// </summary>
            InvertedLazyS = 0x223E,
            /// <summary>
            /// SINE WAVE ∿
            /// </summary>
            SineWave = 0x223F,
            /// <summary>
            /// WREATH PRODUCT ≀
            /// </summary>
            WreathProduct = 0x2240,
            /// <summary>
            /// NOT TILDE ≁
            /// </summary>
            NotTilde = 0x2241,
            /// <summary>
            /// MINUS TILDE ≂
            /// </summary>
            MinusTilde = 0x2242,
            /// <summary>
            /// ASYMPTOTICALLY EQUAL TO ≃
            /// </summary>
            AsymptoticallyEqualTo = 0x2243,
            /// <summary>
            /// NOT ASYMPTOTICALLY EQUAL TO ≄
            /// </summary>
            NotAsymptoticallyEqualTo = 0x2244,
            /// <summary>
            /// APPROXIMATELY EQUAL TO ≅
            /// </summary>
            ApproximatelyEqualTo = 0x2245,
            /// <summary>
            /// APPROXIMATELY BUT NOT ACTUALLY EQUAL TO ≆
            /// </summary>
            ApproximatelyButNotActuallyEqualTo = 0x2246,
            /// <summary>
            /// NEITHER APPROXIMATELY NOR ACTUALLY EQUAL TO ≇
            /// </summary>
            NeitherApproximatelyNorActuallyEqualTo = 0x2247,
            /// <summary>
            /// ALMOST EQUAL TO ≈
            /// </summary>
            AlmostEqualTo = 0x2248,
            /// <summary>
            /// NOT ALMOST EQUAL TO ≉
            /// </summary>
            NotAlmostEqualTo = 0x2249,
            /// <summary>
            /// ALMOST EQUAL OR EQUAL TO ≊
            /// </summary>
            AlmostEqualOrEqualTo = 0x224A,
            /// <summary>
            /// TRIPLE TILDE ≋
            /// </summary>
            TripleTilde = 0x224B,
            /// <summary>
            /// ALL EQUAL TO ≌
            /// </summary>
            AllEqualTo = 0x224C,
            /// <summary>
            /// EQUIVALENT TO ≍
            /// </summary>
            EquivalentTo = 0x224D,
            /// <summary>
            /// GEOMETRICALLY EQUIVALENT TO ≎
            /// </summary>
            GeometricallyEquivalentTo = 0x224E,
            /// <summary>
            /// DIFFERENCE BETWEEN ≏
            /// </summary>
            DifferenceBetween = 0x224F,
            /// <summary>
            /// APPROACHES THE LIMIT ≐
            /// </summary>
            ApproachesTheLimit = 0x2250,
            /// <summary>
            /// GEOMETRICALLY EQUAL TO ≑
            /// </summary>
            GeometricallyEqualTo = 0x2251,
            /// <summary>
            /// APPROXIMATELY EQUAL TO OR THE IMAGE OF ≒
            /// </summary>
            ApproximatelyEqualToOrTheImageOf = 0x2252,
            /// <summary>
            /// IMAGE OF OR APPROXIMATELY EQUAL TO ≓
            /// </summary>
            ImageOfOrApproximatelyEqualTo = 0x2253,
            /// <summary>
            /// COLON EQUALS ≔
            /// </summary>
            ColonEquals = 0x2254,
            /// <summary>
            /// EQUALS COLON ≕
            /// </summary>
            EqualsColon = 0x2255,
            /// <summary>
            /// RING IN EQUAL TO ≖
            /// </summary>
            RingInEqualTo = 0x2256,
            /// <summary>
            /// RING EQUAL TO ≗
            /// </summary>
            RingEqualTo = 0x2257,
            /// <summary>
            /// CORRESPONDS TO ≘
            /// </summary>
            CorrespondsTo = 0x2258,
            /// <summary>
            /// ESTIMATES ≙
            /// </summary>
            Estimates = 0x2259,
            /// <summary>
            /// EQUIANGULAR TO ≚
            /// </summary>
            EquiangularTo = 0x225A,
            /// <summary>
            /// STAR EQUALS ≛
            /// </summary>
            StarEquals = 0x225B,
            /// <summary>
            /// DELTA EQUAL TO ≜
            /// </summary>
            DeltaEqualTo = 0x225C,
            /// <summary>
            /// EQUAL TO BY DEFINITION ≝
            /// </summary>
            EqualToByDefinition = 0x225D,
            /// <summary>
            /// MEASURED BY ≞
            /// </summary>
            MeasuredBy = 0x225E,
            /// <summary>
            /// QUESTIONED EQUAL TO ≟
            /// </summary>
            QuestionedEqualTo = 0x225F,
            /// <summary>
            /// NOT EQUAL TO ≠
            /// </summary>
            NotEqualTo = 0x2260,
            /// <summary>
            /// IDENTICAL TO ≡
            /// </summary>
            IdenticalTo = 0x2261,
            /// <summary>
            /// NOT IDENTICAL TO ≢
            /// </summary>
            NotIdenticalTo = 0x2262,
            /// <summary>
            /// STRICTLY EQUIVALENT TO ≣
            /// </summary>
            StrictlyEquivalentTo = 0x2263,
            /// <summary>
            /// LESS-THAN OR EQUAL TO ≤
            /// </summary>
            LessThanOrEqualTo = 0x2264,
            /// <summary>
            /// GREATER-THAN OR EQUAL TO ≥
            /// </summary>
            GreaterThanOrEqualTo = 0x2265,
            /// <summary>
            /// LESS-THAN OVER EQUAL TO ≦
            /// </summary>
            LessThanOverEqualTo = 0x2266,
            /// <summary>
            /// GREATER-THAN OVER EQUAL TO ≧
            /// </summary>
            GreaterThanOverEqualTo = 0x2267,
            /// <summary>
            /// LESS-THAN BUT NOT EQUAL TO ≨
            /// </summary>
            LessThanButNotEqualTo = 0x2268,
            /// <summary>
            /// GREATER-THAN BUT NOT EQUAL TO ≩
            /// </summary>
            GreaterThanButNotEqualTo = 0x2269,
            /// <summary>
            /// MUCH LESS-THAN ≪
            /// </summary>
            MuchLessThan = 0x226A,
            /// <summary>
            /// MUCH GREATER-THAN ≫
            /// </summary>
            MuchGreaterThan = 0x226B,
            /// <summary>
            /// BETWEEN ≬
            /// </summary>
            Between = 0x226C,
            /// <summary>
            /// NOT EQUIVALENT TO ≭
            /// </summary>
            NotEquivalentTo = 0x226D,
            /// <summary>
            /// NOT LESS-THAN ≮
            /// </summary>
            NotLessThan = 0x226E,
            /// <summary>
            /// NOT GREATER-THAN ≯
            /// </summary>
            NotGreaterThan = 0x226F,
            /// <summary>
            /// NEITHER LESS-THAN NOR EQUAL TO ≰
            /// </summary>
            NeitherLessThanNorEqualTo = 0x2270,
            /// <summary>
            /// NEITHER GREATER-THAN NOR EQUAL TO ≱
            /// </summary>
            NeitherGreaterThanNorEqualTo = 0x2271,
            /// <summary>
            /// LESS-THAN OR EQUIVALENT TO ≲
            /// </summary>
            LessThanOrEquivalentTo = 0x2272,
            /// <summary>
            /// GREATER-THAN OR EQUIVALENT TO ≳
            /// </summary>
            GreaterThanOrEquivalentTo = 0x2273,
            /// <summary>
            /// NEITHER LESS-THAN NOR EQUIVALENT TO ≴
            /// </summary>
            NeitherLessThanNorEquivalentTo = 0x2274,
            /// <summary>
            /// NEITHER GREATER-THAN NOR EQUIVALENT TO ≵
            /// </summary>
            NeitherGreaterThanNorEquivalentTo = 0x2275,
            /// <summary>
            /// LESS-THAN OR GREATER-THAN ≶
            /// </summary>
            LessThanOrGreaterThan = 0x2276,
            /// <summary>
            /// GREATER-THAN OR LESS-THAN ≷
            /// </summary>
            GreaterThanOrLessThan = 0x2277,
            /// <summary>
            /// NEITHER LESS-THAN NOR GREATER-THAN ≸
            /// </summary>
            NeitherLessThanNorGreaterThan = 0x2278,
            /// <summary>
            /// NEITHER GREATER-THAN NOR LESS-THAN ≹
            /// </summary>
            NeitherGreaterThanNorLessThan = 0x2279,
            /// <summary>
            /// PRECEDES ≺
            /// </summary>
            Precedes = 0x227A,
            /// <summary>
            /// SUCCEEDS ≻
            /// </summary>
            Succeeds = 0x227B,
            /// <summary>
            /// PRECEDES OR EQUAL TO ≼
            /// </summary>
            PrecedesOrEqualTo = 0x227C,
            /// <summary>
            /// SUCCEEDS OR EQUAL TO ≽
            /// </summary>
            SucceedsOrEqualTo = 0x227D,
            /// <summary>
            /// PRECEDES OR EQUIVALENT TO ≾
            /// </summary>
            PrecedesOrEquivalentTo = 0x227E,
            /// <summary>
            /// SUCCEEDS OR EQUIVALENT TO ≿
            /// </summary>
            SucceedsOrEquivalentTo = 0x227F,
            /// <summary>
            /// DOES NOT PRECEDE ⊀
            /// </summary>
            DoesNotPrecede = 0x2280,
            /// <summary>
            /// DOES NOT SUCCEED ⊁
            /// </summary>
            DoesNotSucceed = 0x2281,
            /// <summary>
            /// SUBSET OF ⊂
            /// </summary>
            SubsetOf = 0x2282,
            /// <summary>
            /// SUPERSET OF ⊃
            /// </summary>
            SupersetOf = 0x2283,
            /// <summary>
            /// NOT A SUBSET OF ⊄
            /// </summary>
            NotASubsetOf = 0x2284,
            /// <summary>
            /// NOT A SUPERSET OF ⊅
            /// </summary>
            NotASupersetOf = 0x2285,
            /// <summary>
            /// SUBSET OF OR EQUAL TO ⊆
            /// </summary>
            SubsetOfOrEqualTo = 0x2286,
            /// <summary>
            /// SUPERSET OF OR EQUAL TO ⊇
            /// </summary>
            SupersetOfOrEqualTo = 0x2287,
            /// <summary>
            /// NEITHER A SUBSET OF NOR EQUAL TO ⊈
            /// </summary>
            NeitherASubsetOfNorEqualTo = 0x2288,
            /// <summary>
            /// NEITHER A SUPERSET OF NOR EQUAL TO ⊉
            /// </summary>
            NeitherASupersetOfNorEqualTo = 0x2289,
            /// <summary>
            /// SUBSET OF WITH NOT EQUAL TO ⊊
            /// </summary>
            SubsetOfWithNotEqualTo = 0x228A,
            /// <summary>
            /// SUPERSET OF WITH NOT EQUAL TO ⊋
            /// </summary>
            SupersetOfWithNotEqualTo = 0x228B,
            /// <summary>
            /// MULTISET ⊌
            /// </summary>
            Multiset = 0x228C,
            /// <summary>
            /// MULTISET MULTIPLICATION ⊍
            /// </summary>
            MultisetMultiplication = 0x228D,
            /// <summary>
            /// MULTISET UNION ⊎
            /// </summary>
            MultisetUnion = 0x228E,
            /// <summary>
            /// SQUARE IMAGE OF ⊏
            /// </summary>
            SquareImageOf = 0x228F,
            /// <summary>
            /// SQUARE ORIGINAL OF ⊐
            /// </summary>
            SquareOriginalOf = 0x2290,
            /// <summary>
            /// SQUARE IMAGE OF OR EQUAL TO ⊑
            /// </summary>
            SquareImageOfOrEqualTo = 0x2291,
            /// <summary>
            /// SQUARE ORIGINAL OF OR EQUAL TO ⊒
            /// </summary>
            SquareOriginalOfOrEqualTo = 0x2292,
            /// <summary>
            /// SQUARE CAP ⊓
            /// </summary>
            SquareCap = 0x2293,
            /// <summary>
            /// SQUARE CUP ⊔
            /// </summary>
            SquareCup = 0x2294,
            /// <summary>
            /// CIRCLED PLUS ⊕
            /// </summary>
            CircledPlus = 0x2295,
            /// <summary>
            /// CIRCLED MINUS ⊖
            /// </summary>
            CircledMinus = 0x2296,
            /// <summary>
            /// CIRCLED TIMES ⊗
            /// </summary>
            CircledTimes = 0x2297,
            /// <summary>
            /// CIRCLED DIVISION SLASH ⊘
            /// </summary>
            CircledDivisionSlash = 0x2298,
            /// <summary>
            /// CIRCLED DOT OPERATOR ⊙
            /// </summary>
            CircledDotOperator = 0x2299,
            /// <summary>
            /// CIRCLED RING OPERATOR ⊚
            /// </summary>
            CircledRingOperator = 0x229A,
            /// <summary>
            /// CIRCLED ASTERISK OPERATOR ⊛
            /// </summary>
            CircledAsteriskOperator = 0x229B,
            /// <summary>
            /// CIRCLED EQUALS ⊜
            /// </summary>
            CircledEquals = 0x229C,
            /// <summary>
            /// CIRCLED DASH ⊝
            /// </summary>
            CircledDash = 0x229D,
            /// <summary>
            /// SQUARED PLUS ⊞
            /// </summary>
            SquaredPlus = 0x229E,
            /// <summary>
            /// SQUARED MINUS ⊟
            /// </summary>
            SquaredMinus = 0x229F,
            /// <summary>
            /// SQUARED TIMES ⊠
            /// </summary>
            SquaredTimes = 0x22A0,
            /// <summary>
            /// SQUARED DOT OPERATOR ⊡
            /// </summary>
            SquaredDotOperator = 0x22A1,
            /// <summary>
            /// RIGHT TACK ⊢
            /// </summary>
            RightTack = 0x22A2,
            /// <summary>
            /// LEFT TACK ⊣
            /// </summary>
            LeftTack = 0x22A3,
            /// <summary>
            /// DOWN TACK ⊤
            /// </summary>
            DownTack = 0x22A4,
            /// <summary>
            /// UP TACK ⊥
            /// </summary>
            UpTack = 0x22A5,
            /// <summary>
            /// ASSERTION ⊦
            /// </summary>
            Assertion = 0x22A6,
            /// <summary>
            /// MODELS ⊧
            /// </summary>
            Models = 0x22A7,
            /// <summary>
            /// TRUE ⊨
            /// </summary>
            True = 0x22A8,
            /// <summary>
            /// FORCES ⊩
            /// </summary>
            Forces = 0x22A9,
            /// <summary>
            /// TRIPLE VERTICAL BAR RIGHT TURNSTILE ⊪
            /// </summary>
            TripleVerticalBarRightTurnstile = 0x22AA,
            /// <summary>
            /// DOUBLE VERTICAL BAR DOUBLE RIGHT TURNSTILE ⊫
            /// </summary>
            DoubleVerticalBarDoubleRightTurnstile = 0x22AB,
            /// <summary>
            /// DOES NOT PROVE ⊬
            /// </summary>
            DoesNotProve = 0x22AC,
            /// <summary>
            /// NOT TRUE ⊭
            /// </summary>
            NotTrue = 0x22AD,
            /// <summary>
            /// DOES NOT FORCE ⊮
            /// </summary>
            DoesNotForce = 0x22AE,
            /// <summary>
            /// NEGATED DOUBLE VERTICAL BAR DOUBLE RIGHT TURNSTILE ⊯
            /// </summary>
            NegatedDoubleVerticalBarDoubleRightTurnstile = 0x22AF,
            /// <summary>
            /// PRECEDES UNDER RELATION ⊰
            /// </summary>
            PrecedesUnderRelation = 0x22B0,
            /// <summary>
            /// SUCCEEDS UNDER RELATION ⊱
            /// </summary>
            SucceedsUnderRelation = 0x22B1,
            /// <summary>
            /// NORMAL SUBGROUP OF ⊲
            /// </summary>
            NormalSubgroupOf = 0x22B2,
            /// <summary>
            /// CONTAINS AS NORMAL SUBGROUP ⊳
            /// </summary>
            ContainsAsNormalSubgroup = 0x22B3,
            /// <summary>
            /// NORMAL SUBGROUP OF OR EQUAL TO ⊴
            /// </summary>
            NormalSubgroupOfOrEqualTo = 0x22B4,
            /// <summary>
            /// CONTAINS AS NORMAL SUBGROUP OR EQUAL TO ⊵
            /// </summary>
            ContainsAsNormalSubgroupOrEqualTo = 0x22B5,
            /// <summary>
            /// ORIGINAL OF ⊶
            /// </summary>
            OriginalOf = 0x22B6,
            /// <summary>
            /// IMAGE OF ⊷
            /// </summary>
            ImageOf = 0x22B7,
            /// <summary>
            /// MULTIMAP ⊸
            /// </summary>
            Multimap = 0x22B8,
            /// <summary>
            /// HERMITIAN CONJUGATE MATRIX ⊹
            /// </summary>
            HermitianConjugateMatrix = 0x22B9,
            /// <summary>
            /// INTERCALATE ⊺
            /// </summary>
            Intercalate = 0x22BA,
            /// <summary>
            /// XOR ⊻
            /// </summary>
            Xor = 0x22BB,
            /// <summary>
            /// NAND ⊼
            /// </summary>
            Nand = 0x22BC,
            /// <summary>
            /// NOR ⊽
            /// </summary>
            Nor = 0x22BD,
            /// <summary>
            /// RIGHT ANGLE WITH ARC ⊾
            /// </summary>
            RightAngleWithArc = 0x22BE,
            /// <summary>
            /// RIGHT TRIANGLE ⊿
            /// </summary>
            RightTriangle = 0x22BF,
            /// <summary>
            /// N-ARY LOGICAL AND ⋀
            /// </summary>
            NAryLogicalAnd = 0x22C0,
            /// <summary>
            /// N-ARY LOGICAL OR ⋁
            /// </summary>
            NAryLogicalOr = 0x22C1,
            /// <summary>
            /// N-ARY INTERSECTION ⋂
            /// </summary>
            NAryIntersection = 0x22C2,
            /// <summary>
            /// N-ARY UNION ⋃
            /// </summary>
            NAryUnion = 0x22C3,
            /// <summary>
            /// DIAMOND OPERATOR ⋄
            /// </summary>
            DiamondOperator = 0x22C4,
            /// <summary>
            /// DOT OPERATOR ⋅
            /// </summary>
            DotOperator = 0x22C5,
            /// <summary>
            /// STAR OPERATOR ⋆
            /// </summary>
            StarOperator = 0x22C6,
            /// <summary>
            /// DIVISION TIMES ⋇
            /// </summary>
            DivisionTimes = 0x22C7,
            /// <summary>
            /// BOWTIE ⋈
            /// </summary>
            Bowtie = 0x22C8,
            /// <summary>
            /// LEFT NORMAL FACTOR SEMIDIRECT PRODUCT ⋉
            /// </summary>
            LeftNormalFactorSemidirectProduct = 0x22C9,
            /// <summary>
            /// RIGHT NORMAL FACTOR SEMIDIRECT PRODUCT ⋊
            /// </summary>
            RightNormalFactorSemidirectProduct = 0x22CA,
            /// <summary>
            /// LEFT SEMIDIRECT PRODUCT ⋋
            /// </summary>
            LeftSemidirectProduct = 0x22CB,
            /// <summary>
            /// RIGHT SEMIDIRECT PRODUCT ⋌
            /// </summary>
            RightSemidirectProduct = 0x22CC,
            /// <summary>
            /// REVERSED TILDE EQUALS ⋍
            /// </summary>
            ReversedTildeEquals = 0x22CD,
            /// <summary>
            /// CURLY LOGICAL OR ⋎
            /// </summary>
            CurlyLogicalOr = 0x22CE,
            /// <summary>
            /// CURLY LOGICAL AND ⋏
            /// </summary>
            CurlyLogicalAnd = 0x22CF,
            /// <summary>
            /// DOUBLE SUBSET ⋐
            /// </summary>
            DoubleSubset = 0x22D0,
            /// <summary>
            /// DOUBLE SUPERSET ⋑
            /// </summary>
            DoubleSuperset = 0x22D1,
            /// <summary>
            /// DOUBLE INTERSECTION ⋒
            /// </summary>
            DoubleIntersection = 0x22D2,
            /// <summary>
            /// DOUBLE UNION ⋓
            /// </summary>
            DoubleUnion = 0x22D3,
            /// <summary>
            /// PITCHFORK ⋔
            /// </summary>
            Pitchfork = 0x22D4,
            /// <summary>
            /// EQUAL AND PARALLEL TO ⋕
            /// </summary>
            EqualAndParallelTo = 0x22D5,
            /// <summary>
            /// LESS-THAN WITH DOT ⋖
            /// </summary>
            LessThanWithDot = 0x22D6,
            /// <summary>
            /// GREATER-THAN WITH DOT ⋗
            /// </summary>
            GreaterThanWithDot = 0x22D7,
            /// <summary>
            /// VERY MUCH LESS-THAN ⋘
            /// </summary>
            VeryMuchLessThan = 0x22D8,
            /// <summary>
            /// VERY MUCH GREATER-THAN ⋙
            /// </summary>
            VeryMuchGreaterThan = 0x22D9,
            /// <summary>
            /// LESS-THAN EQUAL TO OR GREATER-THAN ⋚
            /// </summary>
            LessThanEqualToOrGreaterThan = 0x22DA,
            /// <summary>
            /// GREATER-THAN EQUAL TO OR LESS-THAN ⋛
            /// </summary>
            GreaterThanEqualToOrLessThan = 0x22DB,
            /// <summary>
            /// EQUAL TO OR LESS-THAN ⋜
            /// </summary>
            EqualToOrLessThan = 0x22DC,
            /// <summary>
            /// EQUAL TO OR GREATER-THAN ⋝
            /// </summary>
            EqualToOrGreaterThan = 0x22DD,
            /// <summary>
            /// EQUAL TO OR PRECEDES ⋞
            /// </summary>
            EqualToOrPrecedes = 0x22DE,
            /// <summary>
            /// EQUAL TO OR SUCCEEDS ⋟
            /// </summary>
            EqualToOrSucceeds = 0x22DF,
            /// <summary>
            /// DOES NOT PRECEDE OR EQUAL ⋠
            /// </summary>
            DoesNotPrecedeOrEqual = 0x22E0,
            /// <summary>
            /// DOES NOT SUCCEED OR EQUAL ⋡
            /// </summary>
            DoesNotSucceedOrEqual = 0x22E1,
            /// <summary>
            /// NOT SQUARE IMAGE OF OR EQUAL TO ⋢
            /// </summary>
            NotSquareImageOfOrEqualTo = 0x22E2,
            /// <summary>
            /// NOT SQUARE ORIGINAL OF OR EQUAL TO ⋣
            /// </summary>
            NotSquareOriginalOfOrEqualTo = 0x22E3,
            /// <summary>
            /// SQUARE IMAGE OF OR NOT EQUAL TO ⋤
            /// </summary>
            SquareImageOfOrNotEqualTo = 0x22E4,
            /// <summary>
            /// SQUARE ORIGINAL OF OR NOT EQUAL TO ⋥
            /// </summary>
            SquareOriginalOfOrNotEqualTo = 0x22E5,
            /// <summary>
            /// LESS-THAN BUT NOT EQUIVALENT TO ⋦
            /// </summary>
            LessThanButNotEquivalentTo = 0x22E6,
            /// <summary>
            /// GREATER-THAN BUT NOT EQUIVALENT TO ⋧
            /// </summary>
            GreaterThanButNotEquivalentTo = 0x22E7,
            /// <summary>
            /// PRECEDES BUT NOT EQUIVALENT TO ⋨
            /// </summary>
            PrecedesButNotEquivalentTo = 0x22E8,
            /// <summary>
            /// SUCCEEDS BUT NOT EQUIVALENT TO ⋩
            /// </summary>
            SucceedsButNotEquivalentTo = 0x22E9,
            /// <summary>
            /// NOT NORMAL SUBGROUP OF ⋪
            /// </summary>
            NotNormalSubgroupOf = 0x22EA,
            /// <summary>
            /// DOES NOT CONTAIN AS NORMAL SUBGROUP ⋫
            /// </summary>
            DoesNotContainAsNormalSubgroup = 0x22EB,
            /// <summary>
            /// NOT NORMAL SUBGROUP OF OR EQUAL TO ⋬
            /// </summary>
            NotNormalSubgroupOfOrEqualTo = 0x22EC,
            /// <summary>
            /// DOES NOT CONTAIN AS NORMAL SUBGROUP OR EQUAL ⋭
            /// </summary>
            DoesNotContainAsNormalSubgroupOrEqual = 0x22ED,
            /// <summary>
            /// VERTICAL ELLIPSIS ⋮
            /// </summary>
            VerticalEllipsis = 0x22EE,
            /// <summary>
            /// MIDLINE HORIZONTAL ELLIPSIS ⋯
            /// </summary>
            MidlineHorizontalEllipsis = 0x22EF,
            /// <summary>
            /// UP RIGHT DIAGONAL ELLIPSIS ⋰
            /// </summary>
            UpRightDiagonalEllipsis = 0x22F0,
            /// <summary>
            /// DOWN RIGHT DIAGONAL ELLIPSIS ⋱
            /// </summary>
            DownRightDiagonalEllipsis = 0x22F1,
            /// <summary>
            /// ELEMENT OF WITH LONG HORIZONTAL STROKE ⋲
            /// </summary>
            ElementOfWithLongHorizontalStroke = 0x22F2,
            /// <summary>
            /// ELEMENT OF WITH VERTICAL BAR AT END OF HORIZONTAL STROKE ⋳
            /// </summary>
            ElementOfWithVerticalBarAtEndOfHorizontalStroke = 0x22F3,
            /// <summary>
            /// SMALL ELEMENT OF WITH VERTICAL BAR AT END OF HORIZONTAL STROKE ⋴
            /// </summary>
            SmallElementOfWithVerticalBarAtEndOfHorizontalStroke = 0x22F4,
            /// <summary>
            /// ELEMENT OF WITH DOT ABOVE ⋵
            /// </summary>
            ElementOfWithDotAbove = 0x22F5,
            /// <summary>
            /// ELEMENT OF WITH OVERBAR ⋶
            /// </summary>
            ElementOfWithOverbar = 0x22F6,
            /// <summary>
            /// SMALL ELEMENT OF WITH OVERBAR ⋷
            /// </summary>
            SmallElementOfWithOverbar = 0x22F7,
            /// <summary>
            /// ELEMENT OF WITH UNDERBAR ⋸
            /// </summary>
            ElementOfWithUnderbar = 0x22F8,
            /// <summary>
            /// ELEMENT OF WITH TWO HORIZONTAL STROKES ⋹
            /// </summary>
            ElementOfWithTwoHorizontalStrokes = 0x22F9,
            /// <summary>
            /// CONTAINS WITH LONG HORIZONTAL STROKE ⋺
            /// </summary>
            ContainsWithLongHorizontalStroke = 0x22FA,
            /// <summary>
            /// CONTAINS WITH VERTICAL BAR AT END OF HORIZONTAL STROKE ⋻
            /// </summary>
            ContainsWithVerticalBarAtEndOfHorizontalStroke = 0x22FB,
            /// <summary>
            /// SMALL CONTAINS WITH VERTICAL BAR AT END OF HORIZONTAL STROKE ⋼
            /// </summary>
            SmallContainsWithVerticalBarAtEndOfHorizontalStroke = 0x22FC,
            /// <summary>
            /// CONTAINS WITH OVERBAR ⋽
            /// </summary>
            ContainsWithOverbar = 0x22FD,
            /// <summary>
            /// SMALL CONTAINS WITH OVERBAR ⋾
            /// </summary>
            SmallContainsWithOverbar = 0x22FE,
            /// <summary>
            /// Z NOTATION BAG MEMBERSHIP ⋿
            /// </summary>
            ZNotationBagMembership = 0x22FF
        }
    }
}
