// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    partial struct Char32
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Coptic.UppercaseLetter value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Coptic.UppercaseLetter(Char32 c)
        {
            return (Coptic.UppercaseLetter)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Coptic.LowercaseLetter value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Coptic.LowercaseLetter(Char32 c)
        {
            return (Coptic.LowercaseLetter)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Coptic.OtherSymbol value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Coptic.OtherSymbol(Char32 c)
        {
            return (Coptic.OtherSymbol)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Coptic.NonSpacingMark value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Coptic.NonSpacingMark(Char32 c)
        {
            return (Coptic.NonSpacingMark)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Coptic.OtherPunctuation value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Coptic.OtherPunctuation(Char32 c)
        {
            return (Coptic.OtherPunctuation)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Coptic.OtherNumber value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Coptic.OtherNumber(Char32 c)
        {
            return (Coptic.OtherNumber)c.Value;
        }
    }
}
