// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class Coptic
    {
        public enum UppercaseLetter : int
        {
            /// <summary>
            /// COPTIC CAPITAL LETTER ALFA Ⲁ
            /// </summary>
            CopticCapitalLetterAlfa = 0x2C80,
            /// <summary>
            /// COPTIC CAPITAL LETTER VIDA Ⲃ
            /// </summary>
            CopticCapitalLetterVida = 0x2C82,
            /// <summary>
            /// COPTIC CAPITAL LETTER GAMMA Ⲅ
            /// </summary>
            CopticCapitalLetterGamma = 0x2C84,
            /// <summary>
            /// COPTIC CAPITAL LETTER DALDA Ⲇ
            /// </summary>
            CopticCapitalLetterDalda = 0x2C86,
            /// <summary>
            /// COPTIC CAPITAL LETTER EIE Ⲉ
            /// </summary>
            CopticCapitalLetterEie = 0x2C88,
            /// <summary>
            /// COPTIC CAPITAL LETTER SOU Ⲋ
            /// </summary>
            CopticCapitalLetterSou = 0x2C8A,
            /// <summary>
            /// COPTIC CAPITAL LETTER ZATA Ⲍ
            /// </summary>
            CopticCapitalLetterZata = 0x2C8C,
            /// <summary>
            /// COPTIC CAPITAL LETTER HATE Ⲏ
            /// </summary>
            CopticCapitalLetterHate = 0x2C8E,
            /// <summary>
            /// COPTIC CAPITAL LETTER THETHE Ⲑ
            /// </summary>
            CopticCapitalLetterThethe = 0x2C90,
            /// <summary>
            /// COPTIC CAPITAL LETTER IAUDA Ⲓ
            /// </summary>
            CopticCapitalLetterIauda = 0x2C92,
            /// <summary>
            /// COPTIC CAPITAL LETTER KAPA Ⲕ
            /// </summary>
            CopticCapitalLetterKapa = 0x2C94,
            /// <summary>
            /// COPTIC CAPITAL LETTER LAULA Ⲗ
            /// </summary>
            CopticCapitalLetterLaula = 0x2C96,
            /// <summary>
            /// COPTIC CAPITAL LETTER MI Ⲙ
            /// </summary>
            CopticCapitalLetterMi = 0x2C98,
            /// <summary>
            /// COPTIC CAPITAL LETTER NI Ⲛ
            /// </summary>
            CopticCapitalLetterNi = 0x2C9A,
            /// <summary>
            /// COPTIC CAPITAL LETTER KSI Ⲝ
            /// </summary>
            CopticCapitalLetterKsi = 0x2C9C,
            /// <summary>
            /// COPTIC CAPITAL LETTER O Ⲟ
            /// </summary>
            CopticCapitalLetterO = 0x2C9E,
            /// <summary>
            /// COPTIC CAPITAL LETTER PI Ⲡ
            /// </summary>
            CopticCapitalLetterPi = 0x2CA0,
            /// <summary>
            /// COPTIC CAPITAL LETTER RO Ⲣ
            /// </summary>
            CopticCapitalLetterRo = 0x2CA2,
            /// <summary>
            /// COPTIC CAPITAL LETTER SIMA Ⲥ
            /// </summary>
            CopticCapitalLetterSima = 0x2CA4,
            /// <summary>
            /// COPTIC CAPITAL LETTER TAU Ⲧ
            /// </summary>
            CopticCapitalLetterTau = 0x2CA6,
            /// <summary>
            /// COPTIC CAPITAL LETTER UA Ⲩ
            /// </summary>
            CopticCapitalLetterUa = 0x2CA8,
            /// <summary>
            /// COPTIC CAPITAL LETTER FI Ⲫ
            /// </summary>
            CopticCapitalLetterFi = 0x2CAA,
            /// <summary>
            /// COPTIC CAPITAL LETTER KHI Ⲭ
            /// </summary>
            CopticCapitalLetterKhi = 0x2CAC,
            /// <summary>
            /// COPTIC CAPITAL LETTER PSI Ⲯ
            /// </summary>
            CopticCapitalLetterPsi = 0x2CAE,
            /// <summary>
            /// COPTIC CAPITAL LETTER OOU Ⲱ
            /// </summary>
            CopticCapitalLetterOou = 0x2CB0,
            /// <summary>
            /// COPTIC CAPITAL LETTER DIALECT-P ALEF Ⲳ
            /// </summary>
            CopticCapitalLetterDialectPAlef = 0x2CB2,
            /// <summary>
            /// COPTIC CAPITAL LETTER OLD COPTIC AIN Ⲵ
            /// </summary>
            CopticCapitalLetterOldCopticAin = 0x2CB4,
            /// <summary>
            /// COPTIC CAPITAL LETTER CRYPTOGRAMMIC EIE Ⲷ
            /// </summary>
            CopticCapitalLetterCryptogrammicEie = 0x2CB6,
            /// <summary>
            /// COPTIC CAPITAL LETTER DIALECT-P KAPA Ⲹ
            /// </summary>
            CopticCapitalLetterDialectPKapa = 0x2CB8,
            /// <summary>
            /// COPTIC CAPITAL LETTER DIALECT-P NI Ⲻ
            /// </summary>
            CopticCapitalLetterDialectPNi = 0x2CBA,
            /// <summary>
            /// COPTIC CAPITAL LETTER CRYPTOGRAMMIC NI Ⲽ
            /// </summary>
            CopticCapitalLetterCryptogrammicNi = 0x2CBC,
            /// <summary>
            /// COPTIC CAPITAL LETTER OLD COPTIC OOU Ⲿ
            /// </summary>
            CopticCapitalLetterOldCopticOou = 0x2CBE,
            /// <summary>
            /// COPTIC CAPITAL LETTER SAMPI Ⳁ
            /// </summary>
            CopticCapitalLetterSampi = 0x2CC0,
            /// <summary>
            /// COPTIC CAPITAL LETTER CROSSED SHEI Ⳃ
            /// </summary>
            CopticCapitalLetterCrossedShei = 0x2CC2,
            /// <summary>
            /// COPTIC CAPITAL LETTER OLD COPTIC SHEI Ⳅ
            /// </summary>
            CopticCapitalLetterOldCopticShei = 0x2CC4,
            /// <summary>
            /// COPTIC CAPITAL LETTER OLD COPTIC ESH Ⳇ
            /// </summary>
            CopticCapitalLetterOldCopticEsh = 0x2CC6,
            /// <summary>
            /// COPTIC CAPITAL LETTER AKHMIMIC KHEI Ⳉ
            /// </summary>
            CopticCapitalLetterAkhmimicKhei = 0x2CC8,
            /// <summary>
            /// COPTIC CAPITAL LETTER DIALECT-P HORI Ⳋ
            /// </summary>
            CopticCapitalLetterDialectPHori = 0x2CCA,
            /// <summary>
            /// COPTIC CAPITAL LETTER OLD COPTIC HORI Ⳍ
            /// </summary>
            CopticCapitalLetterOldCopticHori = 0x2CCC,
            /// <summary>
            /// COPTIC CAPITAL LETTER OLD COPTIC HA Ⳏ
            /// </summary>
            CopticCapitalLetterOldCopticHa = 0x2CCE,
            /// <summary>
            /// COPTIC CAPITAL LETTER L-SHAPED HA Ⳑ
            /// </summary>
            CopticCapitalLetterLShapedHa = 0x2CD0,
            /// <summary>
            /// COPTIC CAPITAL LETTER OLD COPTIC HEI Ⳓ
            /// </summary>
            CopticCapitalLetterOldCopticHei = 0x2CD2,
            /// <summary>
            /// COPTIC CAPITAL LETTER OLD COPTIC HAT Ⳕ
            /// </summary>
            CopticCapitalLetterOldCopticHat = 0x2CD4,
            /// <summary>
            /// COPTIC CAPITAL LETTER OLD COPTIC GANGIA Ⳗ
            /// </summary>
            CopticCapitalLetterOldCopticGangia = 0x2CD6,
            /// <summary>
            /// COPTIC CAPITAL LETTER OLD COPTIC DJA Ⳙ
            /// </summary>
            CopticCapitalLetterOldCopticDja = 0x2CD8,
            /// <summary>
            /// COPTIC CAPITAL LETTER OLD COPTIC SHIMA Ⳛ
            /// </summary>
            CopticCapitalLetterOldCopticShima = 0x2CDA,
            /// <summary>
            /// COPTIC CAPITAL LETTER OLD NUBIAN SHIMA Ⳝ
            /// </summary>
            CopticCapitalLetterOldNubianShima = 0x2CDC,
            /// <summary>
            /// COPTIC CAPITAL LETTER OLD NUBIAN NGI Ⳟ
            /// </summary>
            CopticCapitalLetterOldNubianNgi = 0x2CDE,
            /// <summary>
            /// COPTIC CAPITAL LETTER OLD NUBIAN NYI Ⳡ
            /// </summary>
            CopticCapitalLetterOldNubianNyi = 0x2CE0,
            /// <summary>
            /// COPTIC CAPITAL LETTER OLD NUBIAN WAU Ⳣ
            /// </summary>
            CopticCapitalLetterOldNubianWau = 0x2CE2,
            /// <summary>
            /// COPTIC CAPITAL LETTER CRYPTOGRAMMIC SHEI Ⳬ
            /// </summary>
            CopticCapitalLetterCryptogrammicShei = 0x2CEB,
            /// <summary>
            /// COPTIC CAPITAL LETTER CRYPTOGRAMMIC GANGIA Ⳮ
            /// </summary>
            CopticCapitalLetterCryptogrammicGangia = 0x2CED,
            /// <summary>
            /// COPTIC CAPITAL LETTER BOHAIRIC KHEI Ⳳ
            /// </summary>
            CopticCapitalLetterBohairicKhei = 0x2CF2
        }
        public enum LowercaseLetter : int
        {
            /// <summary>
            /// COPTIC SMALL LETTER ALFA ⲁ
            /// </summary>
            CopticSmallLetterAlfa = 0x2C81,
            /// <summary>
            /// COPTIC SMALL LETTER VIDA ⲃ
            /// </summary>
            CopticSmallLetterVida = 0x2C83,
            /// <summary>
            /// COPTIC SMALL LETTER GAMMA ⲅ
            /// </summary>
            CopticSmallLetterGamma = 0x2C85,
            /// <summary>
            /// COPTIC SMALL LETTER DALDA ⲇ
            /// </summary>
            CopticSmallLetterDalda = 0x2C87,
            /// <summary>
            /// COPTIC SMALL LETTER EIE ⲉ
            /// </summary>
            CopticSmallLetterEie = 0x2C89,
            /// <summary>
            /// COPTIC SMALL LETTER SOU ⲋ
            /// </summary>
            CopticSmallLetterSou = 0x2C8B,
            /// <summary>
            /// COPTIC SMALL LETTER ZATA ⲍ
            /// </summary>
            CopticSmallLetterZata = 0x2C8D,
            /// <summary>
            /// COPTIC SMALL LETTER HATE ⲏ
            /// </summary>
            CopticSmallLetterHate = 0x2C8F,
            /// <summary>
            /// COPTIC SMALL LETTER THETHE ⲑ
            /// </summary>
            CopticSmallLetterThethe = 0x2C91,
            /// <summary>
            /// COPTIC SMALL LETTER IAUDA ⲓ
            /// </summary>
            CopticSmallLetterIauda = 0x2C93,
            /// <summary>
            /// COPTIC SMALL LETTER KAPA ⲕ
            /// </summary>
            CopticSmallLetterKapa = 0x2C95,
            /// <summary>
            /// COPTIC SMALL LETTER LAULA ⲗ
            /// </summary>
            CopticSmallLetterLaula = 0x2C97,
            /// <summary>
            /// COPTIC SMALL LETTER MI ⲙ
            /// </summary>
            CopticSmallLetterMi = 0x2C99,
            /// <summary>
            /// COPTIC SMALL LETTER NI ⲛ
            /// </summary>
            CopticSmallLetterNi = 0x2C9B,
            /// <summary>
            /// COPTIC SMALL LETTER KSI ⲝ
            /// </summary>
            CopticSmallLetterKsi = 0x2C9D,
            /// <summary>
            /// COPTIC SMALL LETTER O ⲟ
            /// </summary>
            CopticSmallLetterO = 0x2C9F,
            /// <summary>
            /// COPTIC SMALL LETTER PI ⲡ
            /// </summary>
            CopticSmallLetterPi = 0x2CA1,
            /// <summary>
            /// COPTIC SMALL LETTER RO ⲣ
            /// </summary>
            CopticSmallLetterRo = 0x2CA3,
            /// <summary>
            /// COPTIC SMALL LETTER SIMA ⲥ
            /// </summary>
            CopticSmallLetterSima = 0x2CA5,
            /// <summary>
            /// COPTIC SMALL LETTER TAU ⲧ
            /// </summary>
            CopticSmallLetterTau = 0x2CA7,
            /// <summary>
            /// COPTIC SMALL LETTER UA ⲩ
            /// </summary>
            CopticSmallLetterUa = 0x2CA9,
            /// <summary>
            /// COPTIC SMALL LETTER FI ⲫ
            /// </summary>
            CopticSmallLetterFi = 0x2CAB,
            /// <summary>
            /// COPTIC SMALL LETTER KHI ⲭ
            /// </summary>
            CopticSmallLetterKhi = 0x2CAD,
            /// <summary>
            /// COPTIC SMALL LETTER PSI ⲯ
            /// </summary>
            CopticSmallLetterPsi = 0x2CAF,
            /// <summary>
            /// COPTIC SMALL LETTER OOU ⲱ
            /// </summary>
            CopticSmallLetterOou = 0x2CB1,
            /// <summary>
            /// COPTIC SMALL LETTER DIALECT-P ALEF ⲳ
            /// </summary>
            CopticSmallLetterDialectPAlef = 0x2CB3,
            /// <summary>
            /// COPTIC SMALL LETTER OLD COPTIC AIN ⲵ
            /// </summary>
            CopticSmallLetterOldCopticAin = 0x2CB5,
            /// <summary>
            /// COPTIC SMALL LETTER CRYPTOGRAMMIC EIE ⲷ
            /// </summary>
            CopticSmallLetterCryptogrammicEie = 0x2CB7,
            /// <summary>
            /// COPTIC SMALL LETTER DIALECT-P KAPA ⲹ
            /// </summary>
            CopticSmallLetterDialectPKapa = 0x2CB9,
            /// <summary>
            /// COPTIC SMALL LETTER DIALECT-P NI ⲻ
            /// </summary>
            CopticSmallLetterDialectPNi = 0x2CBB,
            /// <summary>
            /// COPTIC SMALL LETTER CRYPTOGRAMMIC NI ⲽ
            /// </summary>
            CopticSmallLetterCryptogrammicNi = 0x2CBD,
            /// <summary>
            /// COPTIC SMALL LETTER OLD COPTIC OOU ⲿ
            /// </summary>
            CopticSmallLetterOldCopticOou = 0x2CBF,
            /// <summary>
            /// COPTIC SMALL LETTER SAMPI ⳁ
            /// </summary>
            CopticSmallLetterSampi = 0x2CC1,
            /// <summary>
            /// COPTIC SMALL LETTER CROSSED SHEI ⳃ
            /// </summary>
            CopticSmallLetterCrossedShei = 0x2CC3,
            /// <summary>
            /// COPTIC SMALL LETTER OLD COPTIC SHEI ⳅ
            /// </summary>
            CopticSmallLetterOldCopticShei = 0x2CC5,
            /// <summary>
            /// COPTIC SMALL LETTER OLD COPTIC ESH ⳇ
            /// </summary>
            CopticSmallLetterOldCopticEsh = 0x2CC7,
            /// <summary>
            /// COPTIC SMALL LETTER AKHMIMIC KHEI ⳉ
            /// </summary>
            CopticSmallLetterAkhmimicKhei = 0x2CC9,
            /// <summary>
            /// COPTIC SMALL LETTER DIALECT-P HORI ⳋ
            /// </summary>
            CopticSmallLetterDialectPHori = 0x2CCB,
            /// <summary>
            /// COPTIC SMALL LETTER OLD COPTIC HORI ⳍ
            /// </summary>
            CopticSmallLetterOldCopticHori = 0x2CCD,
            /// <summary>
            /// COPTIC SMALL LETTER OLD COPTIC HA ⳏ
            /// </summary>
            CopticSmallLetterOldCopticHa = 0x2CCF,
            /// <summary>
            /// COPTIC SMALL LETTER L-SHAPED HA ⳑ
            /// </summary>
            CopticSmallLetterLShapedHa = 0x2CD1,
            /// <summary>
            /// COPTIC SMALL LETTER OLD COPTIC HEI ⳓ
            /// </summary>
            CopticSmallLetterOldCopticHei = 0x2CD3,
            /// <summary>
            /// COPTIC SMALL LETTER OLD COPTIC HAT ⳕ
            /// </summary>
            CopticSmallLetterOldCopticHat = 0x2CD5,
            /// <summary>
            /// COPTIC SMALL LETTER OLD COPTIC GANGIA ⳗ
            /// </summary>
            CopticSmallLetterOldCopticGangia = 0x2CD7,
            /// <summary>
            /// COPTIC SMALL LETTER OLD COPTIC DJA ⳙ
            /// </summary>
            CopticSmallLetterOldCopticDja = 0x2CD9,
            /// <summary>
            /// COPTIC SMALL LETTER OLD COPTIC SHIMA ⳛ
            /// </summary>
            CopticSmallLetterOldCopticShima = 0x2CDB,
            /// <summary>
            /// COPTIC SMALL LETTER OLD NUBIAN SHIMA ⳝ
            /// </summary>
            CopticSmallLetterOldNubianShima = 0x2CDD,
            /// <summary>
            /// COPTIC SMALL LETTER OLD NUBIAN NGI ⳟ
            /// </summary>
            CopticSmallLetterOldNubianNgi = 0x2CDF,
            /// <summary>
            /// COPTIC SMALL LETTER OLD NUBIAN NYI ⳡ
            /// </summary>
            CopticSmallLetterOldNubianNyi = 0x2CE1,
            /// <summary>
            /// COPTIC SMALL LETTER OLD NUBIAN WAU ⳣ
            /// </summary>
            CopticSmallLetterOldNubianWau = 0x2CE3,
            /// <summary>
            /// COPTIC SYMBOL KAI ⳤ
            /// </summary>
            CopticSymbolKai = 0x2CE4,
            /// <summary>
            /// COPTIC SMALL LETTER CRYPTOGRAMMIC SHEI ⳬ
            /// </summary>
            CopticSmallLetterCryptogrammicShei = 0x2CEC,
            /// <summary>
            /// COPTIC SMALL LETTER CRYPTOGRAMMIC GANGIA ⳮ
            /// </summary>
            CopticSmallLetterCryptogrammicGangia = 0x2CEE,
            /// <summary>
            /// COPTIC SMALL LETTER BOHAIRIC KHEI ⳳ
            /// </summary>
            CopticSmallLetterBohairicKhei = 0x2CF3
        }
        public enum OtherSymbol : int
        {
            /// <summary>
            /// COPTIC SYMBOL MI RO ⳥
            /// </summary>
            CopticSymbolMiRo = 0x2CE5,
            /// <summary>
            /// COPTIC SYMBOL PI RO ⳦
            /// </summary>
            CopticSymbolPiRo = 0x2CE6,
            /// <summary>
            /// COPTIC SYMBOL STAUROS ⳧
            /// </summary>
            CopticSymbolStauros = 0x2CE7,
            /// <summary>
            /// COPTIC SYMBOL TAU RO ⳨
            /// </summary>
            CopticSymbolTauRo = 0x2CE8,
            /// <summary>
            /// COPTIC SYMBOL KHI RO ⳩
            /// </summary>
            CopticSymbolKhiRo = 0x2CE9,
            /// <summary>
            /// COPTIC SYMBOL SHIMA SIMA ⳪
            /// </summary>
            CopticSymbolShimaSima = 0x2CEA
        }
        public enum NonSpacingMark : int
        {
            /// <summary>
            /// COPTIC COMBINING NI ABOVE ⳯
            /// </summary>
            CopticCombiningNiAbove = 0x2CEF,
            /// <summary>
            /// COPTIC COMBINING SPIRITUS ASPER ⳰
            /// </summary>
            CopticCombiningSpiritusAsper = 0x2CF0,
            /// <summary>
            /// COPTIC COMBINING SPIRITUS LENIS ⳱
            /// </summary>
            CopticCombiningSpiritusLenis = 0x2CF1
        }
        public enum OtherPunctuation : int
        {
            /// <summary>
            /// COPTIC OLD NUBIAN FULL STOP ⳹
            /// </summary>
            CopticOldNubianFullStop = 0x2CF9,
            /// <summary>
            /// COPTIC OLD NUBIAN DIRECT QUESTION MARK ⳺
            /// </summary>
            CopticOldNubianDirectQuestionMark = 0x2CFA,
            /// <summary>
            /// COPTIC OLD NUBIAN INDIRECT QUESTION MARK ⳻
            /// </summary>
            CopticOldNubianIndirectQuestionMark = 0x2CFB,
            /// <summary>
            /// COPTIC OLD NUBIAN VERSE DIVIDER ⳼
            /// </summary>
            CopticOldNubianVerseDivider = 0x2CFC,
            /// <summary>
            /// COPTIC FULL STOP ⳾
            /// </summary>
            CopticFullStop = 0x2CFE,
            /// <summary>
            /// COPTIC MORPHOLOGICAL DIVIDER ⳿
            /// </summary>
            CopticMorphologicalDivider = 0x2CFF
        }
        public enum OtherNumber : int
        {
            /// <summary>
            /// COPTIC FRACTION ONE HALF ⳽
            /// </summary>
            CopticFractionOneHalf = 0x2CFD
        }
    }
}
