// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class BoxDrawing
    {
        public enum OtherSymbol : int
        {
            /// <summary>
            /// BOX DRAWINGS LIGHT HORIZONTAL ─
            /// </summary>
            BoxDrawingsLightHorizontal = 0x2500,
            /// <summary>
            /// BOX DRAWINGS HEAVY HORIZONTAL ━
            /// </summary>
            BoxDrawingsHeavyHorizontal = 0x2501,
            /// <summary>
            /// BOX DRAWINGS LIGHT VERTICAL │
            /// </summary>
            BoxDrawingsLightVertical = 0x2502,
            /// <summary>
            /// BOX DRAWINGS HEAVY VERTICAL ┃
            /// </summary>
            BoxDrawingsHeavyVertical = 0x2503,
            /// <summary>
            /// BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL ┄
            /// </summary>
            BoxDrawingsLightTripleDashHorizontal = 0x2504,
            /// <summary>
            /// BOX DRAWINGS HEAVY TRIPLE DASH HORIZONTAL ┅
            /// </summary>
            BoxDrawingsHeavyTripleDashHorizontal = 0x2505,
            /// <summary>
            /// BOX DRAWINGS LIGHT TRIPLE DASH VERTICAL ┆
            /// </summary>
            BoxDrawingsLightTripleDashVertical = 0x2506,
            /// <summary>
            /// BOX DRAWINGS HEAVY TRIPLE DASH VERTICAL ┇
            /// </summary>
            BoxDrawingsHeavyTripleDashVertical = 0x2507,
            /// <summary>
            /// BOX DRAWINGS LIGHT QUADRUPLE DASH HORIZONTAL ┈
            /// </summary>
            BoxDrawingsLightQuadrupleDashHorizontal = 0x2508,
            /// <summary>
            /// BOX DRAWINGS HEAVY QUADRUPLE DASH HORIZONTAL ┉
            /// </summary>
            BoxDrawingsHeavyQuadrupleDashHorizontal = 0x2509,
            /// <summary>
            /// BOX DRAWINGS LIGHT QUADRUPLE DASH VERTICAL ┊
            /// </summary>
            BoxDrawingsLightQuadrupleDashVertical = 0x250A,
            /// <summary>
            /// BOX DRAWINGS HEAVY QUADRUPLE DASH VERTICAL ┋
            /// </summary>
            BoxDrawingsHeavyQuadrupleDashVertical = 0x250B,
            /// <summary>
            /// BOX DRAWINGS LIGHT DOWN AND RIGHT ┌
            /// </summary>
            BoxDrawingsLightDownAndRight = 0x250C,
            /// <summary>
            /// BOX DRAWINGS DOWN LIGHT AND RIGHT HEAVY ┍
            /// </summary>
            BoxDrawingsDownLightAndRightHeavy = 0x250D,
            /// <summary>
            /// BOX DRAWINGS DOWN HEAVY AND RIGHT LIGHT ┎
            /// </summary>
            BoxDrawingsDownHeavyAndRightLight = 0x250E,
            /// <summary>
            /// BOX DRAWINGS HEAVY DOWN AND RIGHT ┏
            /// </summary>
            BoxDrawingsHeavyDownAndRight = 0x250F,
            /// <summary>
            /// BOX DRAWINGS LIGHT DOWN AND LEFT ┐
            /// </summary>
            BoxDrawingsLightDownAndLeft = 0x2510,
            /// <summary>
            /// BOX DRAWINGS DOWN LIGHT AND LEFT HEAVY ┑
            /// </summary>
            BoxDrawingsDownLightAndLeftHeavy = 0x2511,
            /// <summary>
            /// BOX DRAWINGS DOWN HEAVY AND LEFT LIGHT ┒
            /// </summary>
            BoxDrawingsDownHeavyAndLeftLight = 0x2512,
            /// <summary>
            /// BOX DRAWINGS HEAVY DOWN AND LEFT ┓
            /// </summary>
            BoxDrawingsHeavyDownAndLeft = 0x2513,
            /// <summary>
            /// BOX DRAWINGS LIGHT UP AND RIGHT └
            /// </summary>
            BoxDrawingsLightUpAndRight = 0x2514,
            /// <summary>
            /// BOX DRAWINGS UP LIGHT AND RIGHT HEAVY ┕
            /// </summary>
            BoxDrawingsUpLightAndRightHeavy = 0x2515,
            /// <summary>
            /// BOX DRAWINGS UP HEAVY AND RIGHT LIGHT ┖
            /// </summary>
            BoxDrawingsUpHeavyAndRightLight = 0x2516,
            /// <summary>
            /// BOX DRAWINGS HEAVY UP AND RIGHT ┗
            /// </summary>
            BoxDrawingsHeavyUpAndRight = 0x2517,
            /// <summary>
            /// BOX DRAWINGS LIGHT UP AND LEFT ┘
            /// </summary>
            BoxDrawingsLightUpAndLeft = 0x2518,
            /// <summary>
            /// BOX DRAWINGS UP LIGHT AND LEFT HEAVY ┙
            /// </summary>
            BoxDrawingsUpLightAndLeftHeavy = 0x2519,
            /// <summary>
            /// BOX DRAWINGS UP HEAVY AND LEFT LIGHT ┚
            /// </summary>
            BoxDrawingsUpHeavyAndLeftLight = 0x251A,
            /// <summary>
            /// BOX DRAWINGS HEAVY UP AND LEFT ┛
            /// </summary>
            BoxDrawingsHeavyUpAndLeft = 0x251B,
            /// <summary>
            /// BOX DRAWINGS LIGHT VERTICAL AND RIGHT ├
            /// </summary>
            BoxDrawingsLightVerticalAndRight = 0x251C,
            /// <summary>
            /// BOX DRAWINGS VERTICAL LIGHT AND RIGHT HEAVY ┝
            /// </summary>
            BoxDrawingsVerticalLightAndRightHeavy = 0x251D,
            /// <summary>
            /// BOX DRAWINGS UP HEAVY AND RIGHT DOWN LIGHT ┞
            /// </summary>
            BoxDrawingsUpHeavyAndRightDownLight = 0x251E,
            /// <summary>
            /// BOX DRAWINGS DOWN HEAVY AND RIGHT UP LIGHT ┟
            /// </summary>
            BoxDrawingsDownHeavyAndRightUpLight = 0x251F,
            /// <summary>
            /// BOX DRAWINGS VERTICAL HEAVY AND RIGHT LIGHT ┠
            /// </summary>
            BoxDrawingsVerticalHeavyAndRightLight = 0x2520,
            /// <summary>
            /// BOX DRAWINGS DOWN LIGHT AND RIGHT UP HEAVY ┡
            /// </summary>
            BoxDrawingsDownLightAndRightUpHeavy = 0x2521,
            /// <summary>
            /// BOX DRAWINGS UP LIGHT AND RIGHT DOWN HEAVY ┢
            /// </summary>
            BoxDrawingsUpLightAndRightDownHeavy = 0x2522,
            /// <summary>
            /// BOX DRAWINGS HEAVY VERTICAL AND RIGHT ┣
            /// </summary>
            BoxDrawingsHeavyVerticalAndRight = 0x2523,
            /// <summary>
            /// BOX DRAWINGS LIGHT VERTICAL AND LEFT ┤
            /// </summary>
            BoxDrawingsLightVerticalAndLeft = 0x2524,
            /// <summary>
            /// BOX DRAWINGS VERTICAL LIGHT AND LEFT HEAVY ┥
            /// </summary>
            BoxDrawingsVerticalLightAndLeftHeavy = 0x2525,
            /// <summary>
            /// BOX DRAWINGS UP HEAVY AND LEFT DOWN LIGHT ┦
            /// </summary>
            BoxDrawingsUpHeavyAndLeftDownLight = 0x2526,
            /// <summary>
            /// BOX DRAWINGS DOWN HEAVY AND LEFT UP LIGHT ┧
            /// </summary>
            BoxDrawingsDownHeavyAndLeftUpLight = 0x2527,
            /// <summary>
            /// BOX DRAWINGS VERTICAL HEAVY AND LEFT LIGHT ┨
            /// </summary>
            BoxDrawingsVerticalHeavyAndLeftLight = 0x2528,
            /// <summary>
            /// BOX DRAWINGS DOWN LIGHT AND LEFT UP HEAVY ┩
            /// </summary>
            BoxDrawingsDownLightAndLeftUpHeavy = 0x2529,
            /// <summary>
            /// BOX DRAWINGS UP LIGHT AND LEFT DOWN HEAVY ┪
            /// </summary>
            BoxDrawingsUpLightAndLeftDownHeavy = 0x252A,
            /// <summary>
            /// BOX DRAWINGS HEAVY VERTICAL AND LEFT ┫
            /// </summary>
            BoxDrawingsHeavyVerticalAndLeft = 0x252B,
            /// <summary>
            /// BOX DRAWINGS LIGHT DOWN AND HORIZONTAL ┬
            /// </summary>
            BoxDrawingsLightDownAndHorizontal = 0x252C,
            /// <summary>
            /// BOX DRAWINGS LEFT HEAVY AND RIGHT DOWN LIGHT ┭
            /// </summary>
            BoxDrawingsLeftHeavyAndRightDownLight = 0x252D,
            /// <summary>
            /// BOX DRAWINGS RIGHT HEAVY AND LEFT DOWN LIGHT ┮
            /// </summary>
            BoxDrawingsRightHeavyAndLeftDownLight = 0x252E,
            /// <summary>
            /// BOX DRAWINGS DOWN LIGHT AND HORIZONTAL HEAVY ┯
            /// </summary>
            BoxDrawingsDownLightAndHorizontalHeavy = 0x252F,
            /// <summary>
            /// BOX DRAWINGS DOWN HEAVY AND HORIZONTAL LIGHT ┰
            /// </summary>
            BoxDrawingsDownHeavyAndHorizontalLight = 0x2530,
            /// <summary>
            /// BOX DRAWINGS RIGHT LIGHT AND LEFT DOWN HEAVY ┱
            /// </summary>
            BoxDrawingsRightLightAndLeftDownHeavy = 0x2531,
            /// <summary>
            /// BOX DRAWINGS LEFT LIGHT AND RIGHT DOWN HEAVY ┲
            /// </summary>
            BoxDrawingsLeftLightAndRightDownHeavy = 0x2532,
            /// <summary>
            /// BOX DRAWINGS HEAVY DOWN AND HORIZONTAL ┳
            /// </summary>
            BoxDrawingsHeavyDownAndHorizontal = 0x2533,
            /// <summary>
            /// BOX DRAWINGS LIGHT UP AND HORIZONTAL ┴
            /// </summary>
            BoxDrawingsLightUpAndHorizontal = 0x2534,
            /// <summary>
            /// BOX DRAWINGS LEFT HEAVY AND RIGHT UP LIGHT ┵
            /// </summary>
            BoxDrawingsLeftHeavyAndRightUpLight = 0x2535,
            /// <summary>
            /// BOX DRAWINGS RIGHT HEAVY AND LEFT UP LIGHT ┶
            /// </summary>
            BoxDrawingsRightHeavyAndLeftUpLight = 0x2536,
            /// <summary>
            /// BOX DRAWINGS UP LIGHT AND HORIZONTAL HEAVY ┷
            /// </summary>
            BoxDrawingsUpLightAndHorizontalHeavy = 0x2537,
            /// <summary>
            /// BOX DRAWINGS UP HEAVY AND HORIZONTAL LIGHT ┸
            /// </summary>
            BoxDrawingsUpHeavyAndHorizontalLight = 0x2538,
            /// <summary>
            /// BOX DRAWINGS RIGHT LIGHT AND LEFT UP HEAVY ┹
            /// </summary>
            BoxDrawingsRightLightAndLeftUpHeavy = 0x2539,
            /// <summary>
            /// BOX DRAWINGS LEFT LIGHT AND RIGHT UP HEAVY ┺
            /// </summary>
            BoxDrawingsLeftLightAndRightUpHeavy = 0x253A,
            /// <summary>
            /// BOX DRAWINGS HEAVY UP AND HORIZONTAL ┻
            /// </summary>
            BoxDrawingsHeavyUpAndHorizontal = 0x253B,
            /// <summary>
            /// BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL ┼
            /// </summary>
            BoxDrawingsLightVerticalAndHorizontal = 0x253C,
            /// <summary>
            /// BOX DRAWINGS LEFT HEAVY AND RIGHT VERTICAL LIGHT ┽
            /// </summary>
            BoxDrawingsLeftHeavyAndRightVerticalLight = 0x253D,
            /// <summary>
            /// BOX DRAWINGS RIGHT HEAVY AND LEFT VERTICAL LIGHT ┾
            /// </summary>
            BoxDrawingsRightHeavyAndLeftVerticalLight = 0x253E,
            /// <summary>
            /// BOX DRAWINGS VERTICAL LIGHT AND HORIZONTAL HEAVY ┿
            /// </summary>
            BoxDrawingsVerticalLightAndHorizontalHeavy = 0x253F,
            /// <summary>
            /// BOX DRAWINGS UP HEAVY AND DOWN HORIZONTAL LIGHT ╀
            /// </summary>
            BoxDrawingsUpHeavyAndDownHorizontalLight = 0x2540,
            /// <summary>
            /// BOX DRAWINGS DOWN HEAVY AND UP HORIZONTAL LIGHT ╁
            /// </summary>
            BoxDrawingsDownHeavyAndUpHorizontalLight = 0x2541,
            /// <summary>
            /// BOX DRAWINGS VERTICAL HEAVY AND HORIZONTAL LIGHT ╂
            /// </summary>
            BoxDrawingsVerticalHeavyAndHorizontalLight = 0x2542,
            /// <summary>
            /// BOX DRAWINGS LEFT UP HEAVY AND RIGHT DOWN LIGHT ╃
            /// </summary>
            BoxDrawingsLeftUpHeavyAndRightDownLight = 0x2543,
            /// <summary>
            /// BOX DRAWINGS RIGHT UP HEAVY AND LEFT DOWN LIGHT ╄
            /// </summary>
            BoxDrawingsRightUpHeavyAndLeftDownLight = 0x2544,
            /// <summary>
            /// BOX DRAWINGS LEFT DOWN HEAVY AND RIGHT UP LIGHT ╅
            /// </summary>
            BoxDrawingsLeftDownHeavyAndRightUpLight = 0x2545,
            /// <summary>
            /// BOX DRAWINGS RIGHT DOWN HEAVY AND LEFT UP LIGHT ╆
            /// </summary>
            BoxDrawingsRightDownHeavyAndLeftUpLight = 0x2546,
            /// <summary>
            /// BOX DRAWINGS DOWN LIGHT AND UP HORIZONTAL HEAVY ╇
            /// </summary>
            BoxDrawingsDownLightAndUpHorizontalHeavy = 0x2547,
            /// <summary>
            /// BOX DRAWINGS UP LIGHT AND DOWN HORIZONTAL HEAVY ╈
            /// </summary>
            BoxDrawingsUpLightAndDownHorizontalHeavy = 0x2548,
            /// <summary>
            /// BOX DRAWINGS RIGHT LIGHT AND LEFT VERTICAL HEAVY ╉
            /// </summary>
            BoxDrawingsRightLightAndLeftVerticalHeavy = 0x2549,
            /// <summary>
            /// BOX DRAWINGS LEFT LIGHT AND RIGHT VERTICAL HEAVY ╊
            /// </summary>
            BoxDrawingsLeftLightAndRightVerticalHeavy = 0x254A,
            /// <summary>
            /// BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL ╋
            /// </summary>
            BoxDrawingsHeavyVerticalAndHorizontal = 0x254B,
            /// <summary>
            /// BOX DRAWINGS LIGHT DOUBLE DASH HORIZONTAL ╌
            /// </summary>
            BoxDrawingsLightDoubleDashHorizontal = 0x254C,
            /// <summary>
            /// BOX DRAWINGS HEAVY DOUBLE DASH HORIZONTAL ╍
            /// </summary>
            BoxDrawingsHeavyDoubleDashHorizontal = 0x254D,
            /// <summary>
            /// BOX DRAWINGS LIGHT DOUBLE DASH VERTICAL ╎
            /// </summary>
            BoxDrawingsLightDoubleDashVertical = 0x254E,
            /// <summary>
            /// BOX DRAWINGS HEAVY DOUBLE DASH VERTICAL ╏
            /// </summary>
            BoxDrawingsHeavyDoubleDashVertical = 0x254F,
            /// <summary>
            /// BOX DRAWINGS DOUBLE HORIZONTAL ═
            /// </summary>
            BoxDrawingsDoubleHorizontal = 0x2550,
            /// <summary>
            /// BOX DRAWINGS DOUBLE VERTICAL ║
            /// </summary>
            BoxDrawingsDoubleVertical = 0x2551,
            /// <summary>
            /// BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE ╒
            /// </summary>
            BoxDrawingsDownSingleAndRightDouble = 0x2552,
            /// <summary>
            /// BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE ╓
            /// </summary>
            BoxDrawingsDownDoubleAndRightSingle = 0x2553,
            /// <summary>
            /// BOX DRAWINGS DOUBLE DOWN AND RIGHT ╔
            /// </summary>
            BoxDrawingsDoubleDownAndRight = 0x2554,
            /// <summary>
            /// BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE ╕
            /// </summary>
            BoxDrawingsDownSingleAndLeftDouble = 0x2555,
            /// <summary>
            /// BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE ╖
            /// </summary>
            BoxDrawingsDownDoubleAndLeftSingle = 0x2556,
            /// <summary>
            /// BOX DRAWINGS DOUBLE DOWN AND LEFT ╗
            /// </summary>
            BoxDrawingsDoubleDownAndLeft = 0x2557,
            /// <summary>
            /// BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE ╘
            /// </summary>
            BoxDrawingsUpSingleAndRightDouble = 0x2558,
            /// <summary>
            /// BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE ╙
            /// </summary>
            BoxDrawingsUpDoubleAndRightSingle = 0x2559,
            /// <summary>
            /// BOX DRAWINGS DOUBLE UP AND RIGHT ╚
            /// </summary>
            BoxDrawingsDoubleUpAndRight = 0x255A,
            /// <summary>
            /// BOX DRAWINGS UP SINGLE AND LEFT DOUBLE ╛
            /// </summary>
            BoxDrawingsUpSingleAndLeftDouble = 0x255B,
            /// <summary>
            /// BOX DRAWINGS UP DOUBLE AND LEFT SINGLE ╜
            /// </summary>
            BoxDrawingsUpDoubleAndLeftSingle = 0x255C,
            /// <summary>
            /// BOX DRAWINGS DOUBLE UP AND LEFT ╝
            /// </summary>
            BoxDrawingsDoubleUpAndLeft = 0x255D,
            /// <summary>
            /// BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE ╞
            /// </summary>
            BoxDrawingsVerticalSingleAndRightDouble = 0x255E,
            /// <summary>
            /// BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE ╟
            /// </summary>
            BoxDrawingsVerticalDoubleAndRightSingle = 0x255F,
            /// <summary>
            /// BOX DRAWINGS DOUBLE VERTICAL AND RIGHT ╠
            /// </summary>
            BoxDrawingsDoubleVerticalAndRight = 0x2560,
            /// <summary>
            /// BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE ╡
            /// </summary>
            BoxDrawingsVerticalSingleAndLeftDouble = 0x2561,
            /// <summary>
            /// BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE ╢
            /// </summary>
            BoxDrawingsVerticalDoubleAndLeftSingle = 0x2562,
            /// <summary>
            /// BOX DRAWINGS DOUBLE VERTICAL AND LEFT ╣
            /// </summary>
            BoxDrawingsDoubleVerticalAndLeft = 0x2563,
            /// <summary>
            /// BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE ╤
            /// </summary>
            BoxDrawingsDownSingleAndHorizontalDouble = 0x2564,
            /// <summary>
            /// BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE ╥
            /// </summary>
            BoxDrawingsDownDoubleAndHorizontalSingle = 0x2565,
            /// <summary>
            /// BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL ╦
            /// </summary>
            BoxDrawingsDoubleDownAndHorizontal = 0x2566,
            /// <summary>
            /// BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE ╧
            /// </summary>
            BoxDrawingsUpSingleAndHorizontalDouble = 0x2567,
            /// <summary>
            /// BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE ╨
            /// </summary>
            BoxDrawingsUpDoubleAndHorizontalSingle = 0x2568,
            /// <summary>
            /// BOX DRAWINGS DOUBLE UP AND HORIZONTAL ╩
            /// </summary>
            BoxDrawingsDoubleUpAndHorizontal = 0x2569,
            /// <summary>
            /// BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE ╪
            /// </summary>
            BoxDrawingsVerticalSingleAndHorizontalDouble = 0x256A,
            /// <summary>
            /// BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE ╫
            /// </summary>
            BoxDrawingsVerticalDoubleAndHorizontalSingle = 0x256B,
            /// <summary>
            /// BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL ╬
            /// </summary>
            BoxDrawingsDoubleVerticalAndHorizontal = 0x256C,
            /// <summary>
            /// BOX DRAWINGS LIGHT ARC DOWN AND RIGHT ╭
            /// </summary>
            BoxDrawingsLightArcDownAndRight = 0x256D,
            /// <summary>
            /// BOX DRAWINGS LIGHT ARC DOWN AND LEFT ╮
            /// </summary>
            BoxDrawingsLightArcDownAndLeft = 0x256E,
            /// <summary>
            /// BOX DRAWINGS LIGHT ARC UP AND LEFT ╯
            /// </summary>
            BoxDrawingsLightArcUpAndLeft = 0x256F,
            /// <summary>
            /// BOX DRAWINGS LIGHT ARC UP AND RIGHT ╰
            /// </summary>
            BoxDrawingsLightArcUpAndRight = 0x2570,
            /// <summary>
            /// BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER LEFT ╱
            /// </summary>
            BoxDrawingsLightDiagonalUpperRightToLowerLeft = 0x2571,
            /// <summary>
            /// BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER RIGHT ╲
            /// </summary>
            BoxDrawingsLightDiagonalUpperLeftToLowerRight = 0x2572,
            /// <summary>
            /// BOX DRAWINGS LIGHT DIAGONAL CROSS ╳
            /// </summary>
            BoxDrawingsLightDiagonalCross = 0x2573,
            /// <summary>
            /// BOX DRAWINGS LIGHT LEFT ╴
            /// </summary>
            BoxDrawingsLightLeft = 0x2574,
            /// <summary>
            /// BOX DRAWINGS LIGHT UP ╵
            /// </summary>
            BoxDrawingsLightUp = 0x2575,
            /// <summary>
            /// BOX DRAWINGS LIGHT RIGHT ╶
            /// </summary>
            BoxDrawingsLightRight = 0x2576,
            /// <summary>
            /// BOX DRAWINGS LIGHT DOWN ╷
            /// </summary>
            BoxDrawingsLightDown = 0x2577,
            /// <summary>
            /// BOX DRAWINGS HEAVY LEFT ╸
            /// </summary>
            BoxDrawingsHeavyLeft = 0x2578,
            /// <summary>
            /// BOX DRAWINGS HEAVY UP ╹
            /// </summary>
            BoxDrawingsHeavyUp = 0x2579,
            /// <summary>
            /// BOX DRAWINGS HEAVY RIGHT ╺
            /// </summary>
            BoxDrawingsHeavyRight = 0x257A,
            /// <summary>
            /// BOX DRAWINGS HEAVY DOWN ╻
            /// </summary>
            BoxDrawingsHeavyDown = 0x257B,
            /// <summary>
            /// BOX DRAWINGS LIGHT LEFT AND HEAVY RIGHT ╼
            /// </summary>
            BoxDrawingsLightLeftAndHeavyRight = 0x257C,
            /// <summary>
            /// BOX DRAWINGS LIGHT UP AND HEAVY DOWN ╽
            /// </summary>
            BoxDrawingsLightUpAndHeavyDown = 0x257D,
            /// <summary>
            /// BOX DRAWINGS HEAVY LEFT AND LIGHT RIGHT ╾
            /// </summary>
            BoxDrawingsHeavyLeftAndLightRight = 0x257E,
            /// <summary>
            /// BOX DRAWINGS HEAVY UP AND LIGHT DOWN ╿
            /// </summary>
            BoxDrawingsHeavyUpAndLightDown = 0x257F
        }
    }
}
