// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    partial struct Char32
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Khojki.OtherLetter value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Khojki.OtherLetter(Char32 c)
        {
            return (Khojki.OtherLetter)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Khojki.SpacingCombiningMark value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Khojki.SpacingCombiningMark(Char32 c)
        {
            return (Khojki.SpacingCombiningMark)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Khojki.NonSpacingMark value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Khojki.NonSpacingMark(Char32 c)
        {
            return (Khojki.NonSpacingMark)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Khojki.OtherPunctuation value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Khojki.OtherPunctuation(Char32 c)
        {
            return (Khojki.OtherPunctuation)c.Value;
        }
    }
}
