// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class Mro
    {
        public enum OtherLetter : int
        {
            /// <summary>
            /// MRO LETTER TA 𖩀
            /// </summary>
            MroLetterTa = 0x16A40,
            /// <summary>
            /// MRO LETTER NGI 𖩁
            /// </summary>
            MroLetterNgi = 0x16A41,
            /// <summary>
            /// MRO LETTER YO 𖩂
            /// </summary>
            MroLetterYo = 0x16A42,
            /// <summary>
            /// MRO LETTER MIM 𖩃
            /// </summary>
            MroLetterMim = 0x16A43,
            /// <summary>
            /// MRO LETTER BA 𖩄
            /// </summary>
            MroLetterBa = 0x16A44,
            /// <summary>
            /// MRO LETTER DA 𖩅
            /// </summary>
            MroLetterDa = 0x16A45,
            /// <summary>
            /// MRO LETTER A 𖩆
            /// </summary>
            MroLetterA = 0x16A46,
            /// <summary>
            /// MRO LETTER PHI 𖩇
            /// </summary>
            MroLetterPhi = 0x16A47,
            /// <summary>
            /// MRO LETTER KHAI 𖩈
            /// </summary>
            MroLetterKhai = 0x16A48,
            /// <summary>
            /// MRO LETTER HAO 𖩉
            /// </summary>
            MroLetterHao = 0x16A49,
            /// <summary>
            /// MRO LETTER DAI 𖩊
            /// </summary>
            MroLetterDai = 0x16A4A,
            /// <summary>
            /// MRO LETTER CHU 𖩋
            /// </summary>
            MroLetterChu = 0x16A4B,
            /// <summary>
            /// MRO LETTER KEAAE 𖩌
            /// </summary>
            MroLetterKeaae = 0x16A4C,
            /// <summary>
            /// MRO LETTER OL 𖩍
            /// </summary>
            MroLetterOl = 0x16A4D,
            /// <summary>
            /// MRO LETTER MAEM 𖩎
            /// </summary>
            MroLetterMaem = 0x16A4E,
            /// <summary>
            /// MRO LETTER NIN 𖩏
            /// </summary>
            MroLetterNin = 0x16A4F,
            /// <summary>
            /// MRO LETTER PA 𖩐
            /// </summary>
            MroLetterPa = 0x16A50,
            /// <summary>
            /// MRO LETTER OO 𖩑
            /// </summary>
            MroLetterOo = 0x16A51,
            /// <summary>
            /// MRO LETTER O 𖩒
            /// </summary>
            MroLetterO = 0x16A52,
            /// <summary>
            /// MRO LETTER RO 𖩓
            /// </summary>
            MroLetterRo = 0x16A53,
            /// <summary>
            /// MRO LETTER SHI 𖩔
            /// </summary>
            MroLetterShi = 0x16A54,
            /// <summary>
            /// MRO LETTER THEA 𖩕
            /// </summary>
            MroLetterThea = 0x16A55,
            /// <summary>
            /// MRO LETTER EA 𖩖
            /// </summary>
            MroLetterEa = 0x16A56,
            /// <summary>
            /// MRO LETTER WA 𖩗
            /// </summary>
            MroLetterWa = 0x16A57,
            /// <summary>
            /// MRO LETTER E 𖩘
            /// </summary>
            MroLetterE = 0x16A58,
            /// <summary>
            /// MRO LETTER KO 𖩙
            /// </summary>
            MroLetterKo = 0x16A59,
            /// <summary>
            /// MRO LETTER LAN 𖩚
            /// </summary>
            MroLetterLan = 0x16A5A,
            /// <summary>
            /// MRO LETTER LA 𖩛
            /// </summary>
            MroLetterLa = 0x16A5B,
            /// <summary>
            /// MRO LETTER HAI 𖩜
            /// </summary>
            MroLetterHai = 0x16A5C,
            /// <summary>
            /// MRO LETTER RI 𖩝
            /// </summary>
            MroLetterRi = 0x16A5D,
            /// <summary>
            /// MRO LETTER TEK 𖩞
            /// </summary>
            MroLetterTek = 0x16A5E
        }
        public enum DecimalDigitNumber : int
        {
            /// <summary>
            /// MRO DIGIT ZERO 𖩠
            /// </summary>
            MroDigitZero = 0x16A60,
            /// <summary>
            /// MRO DIGIT ONE 𖩡
            /// </summary>
            MroDigitOne = 0x16A61,
            /// <summary>
            /// MRO DIGIT TWO 𖩢
            /// </summary>
            MroDigitTwo = 0x16A62,
            /// <summary>
            /// MRO DIGIT THREE 𖩣
            /// </summary>
            MroDigitThree = 0x16A63,
            /// <summary>
            /// MRO DIGIT FOUR 𖩤
            /// </summary>
            MroDigitFour = 0x16A64,
            /// <summary>
            /// MRO DIGIT FIVE 𖩥
            /// </summary>
            MroDigitFive = 0x16A65,
            /// <summary>
            /// MRO DIGIT SIX 𖩦
            /// </summary>
            MroDigitSix = 0x16A66,
            /// <summary>
            /// MRO DIGIT SEVEN 𖩧
            /// </summary>
            MroDigitSeven = 0x16A67,
            /// <summary>
            /// MRO DIGIT EIGHT 𖩨
            /// </summary>
            MroDigitEight = 0x16A68,
            /// <summary>
            /// MRO DIGIT NINE 𖩩
            /// </summary>
            MroDigitNine = 0x16A69
        }
        public enum OtherPunctuation : int
        {
            /// <summary>
            /// MRO DANDA 𖩮
            /// </summary>
            MroDanda = 0x16A6E,
            /// <summary>
            /// MRO DOUBLE DANDA 𖩯
            /// </summary>
            MroDoubleDanda = 0x16A6F
        }
    }
}
