// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class KanaSupplement
    {
        public enum OtherLetter : int
        {
            /// <summary>
            /// KATAKANA LETTER ARCHAIC E 𛀀
            /// </summary>
            KatakanaLetterArchaicE = 0x1B000,
            /// <summary>
            /// HIRAGANA LETTER ARCHAIC YE 𛀁
            /// </summary>
            HiraganaLetterArchaicYe = 0x1B001
        }
    }
}
