// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    partial struct Char32
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Mongolian.OtherPunctuation value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Mongolian.OtherPunctuation(Char32 c)
        {
            return (Mongolian.OtherPunctuation)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Mongolian.DashPunctuation value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Mongolian.DashPunctuation(Char32 c)
        {
            return (Mongolian.DashPunctuation)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Mongolian.NonSpacingMark value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Mongolian.NonSpacingMark(Char32 c)
        {
            return (Mongolian.NonSpacingMark)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Mongolian.Format value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Mongolian.Format(Char32 c)
        {
            return (Mongolian.Format)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Mongolian.DecimalDigitNumber value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Mongolian.DecimalDigitNumber(Char32 c)
        {
            return (Mongolian.DecimalDigitNumber)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Mongolian.OtherLetter value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Mongolian.OtherLetter(Char32 c)
        {
            return (Mongolian.OtherLetter)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Mongolian.ModifierLetter value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Mongolian.ModifierLetter(Char32 c)
        {
            return (Mongolian.ModifierLetter)c.Value;
        }
    }
}
