// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class Hanunoo
    {
        public enum OtherLetter : int
        {
            /// <summary>
            /// HANUNOO LETTER A ᜠ
            /// </summary>
            HanunooLetterA = 0x1720,
            /// <summary>
            /// HANUNOO LETTER I ᜡ
            /// </summary>
            HanunooLetterI = 0x1721,
            /// <summary>
            /// HANUNOO LETTER U ᜢ
            /// </summary>
            HanunooLetterU = 0x1722,
            /// <summary>
            /// HANUNOO LETTER KA ᜣ
            /// </summary>
            HanunooLetterKa = 0x1723,
            /// <summary>
            /// HANUNOO LETTER GA ᜤ
            /// </summary>
            HanunooLetterGa = 0x1724,
            /// <summary>
            /// HANUNOO LETTER NGA ᜥ
            /// </summary>
            HanunooLetterNga = 0x1725,
            /// <summary>
            /// HANUNOO LETTER TA ᜦ
            /// </summary>
            HanunooLetterTa = 0x1726,
            /// <summary>
            /// HANUNOO LETTER DA ᜧ
            /// </summary>
            HanunooLetterDa = 0x1727,
            /// <summary>
            /// HANUNOO LETTER NA ᜨ
            /// </summary>
            HanunooLetterNa = 0x1728,
            /// <summary>
            /// HANUNOO LETTER PA ᜩ
            /// </summary>
            HanunooLetterPa = 0x1729,
            /// <summary>
            /// HANUNOO LETTER BA ᜪ
            /// </summary>
            HanunooLetterBa = 0x172A,
            /// <summary>
            /// HANUNOO LETTER MA ᜫ
            /// </summary>
            HanunooLetterMa = 0x172B,
            /// <summary>
            /// HANUNOO LETTER YA ᜬ
            /// </summary>
            HanunooLetterYa = 0x172C,
            /// <summary>
            /// HANUNOO LETTER RA ᜭ
            /// </summary>
            HanunooLetterRa = 0x172D,
            /// <summary>
            /// HANUNOO LETTER LA ᜮ
            /// </summary>
            HanunooLetterLa = 0x172E,
            /// <summary>
            /// HANUNOO LETTER WA ᜯ
            /// </summary>
            HanunooLetterWa = 0x172F,
            /// <summary>
            /// HANUNOO LETTER SA ᜰ
            /// </summary>
            HanunooLetterSa = 0x1730,
            /// <summary>
            /// HANUNOO LETTER HA ᜱ
            /// </summary>
            HanunooLetterHa = 0x1731
        }
        public enum NonSpacingMark : int
        {
            /// <summary>
            /// HANUNOO VOWEL SIGN I ᜲ
            /// </summary>
            HanunooVowelSignI = 0x1732,
            /// <summary>
            /// HANUNOO VOWEL SIGN U ᜳ
            /// </summary>
            HanunooVowelSignU = 0x1733,
            /// <summary>
            /// HANUNOO SIGN PAMUDPOD ᜴
            /// </summary>
            HanunooSignPamudpod = 0x1734
        }
        public enum OtherPunctuation : int
        {
            /// <summary>
            /// PHILIPPINE SINGLE PUNCTUATION ᜵
            /// </summary>
            PhilippineSinglePunctuation = 0x1735,
            /// <summary>
            /// PHILIPPINE DOUBLE PUNCTUATION ᜶
            /// </summary>
            PhilippineDoublePunctuation = 0x1736
        }
    }
}
