// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class YiRadicals
    {
        public enum OtherSymbol : int
        {
            /// <summary>
            /// YI RADICAL QOT ꒐
            /// </summary>
            YiRadicalQot = 0xA490,
            /// <summary>
            /// YI RADICAL LI ꒑
            /// </summary>
            YiRadicalLi = 0xA491,
            /// <summary>
            /// YI RADICAL KIT ꒒
            /// </summary>
            YiRadicalKit = 0xA492,
            /// <summary>
            /// YI RADICAL NYIP ꒓
            /// </summary>
            YiRadicalNyip = 0xA493,
            /// <summary>
            /// YI RADICAL CYP ꒔
            /// </summary>
            YiRadicalCyp = 0xA494,
            /// <summary>
            /// YI RADICAL SSI ꒕
            /// </summary>
            YiRadicalSsi = 0xA495,
            /// <summary>
            /// YI RADICAL GGOP ꒖
            /// </summary>
            YiRadicalGgop = 0xA496,
            /// <summary>
            /// YI RADICAL GEP ꒗
            /// </summary>
            YiRadicalGep = 0xA497,
            /// <summary>
            /// YI RADICAL MI ꒘
            /// </summary>
            YiRadicalMi = 0xA498,
            /// <summary>
            /// YI RADICAL HXIT ꒙
            /// </summary>
            YiRadicalHxit = 0xA499,
            /// <summary>
            /// YI RADICAL LYR ꒚
            /// </summary>
            YiRadicalLyr = 0xA49A,
            /// <summary>
            /// YI RADICAL BBUT ꒛
            /// </summary>
            YiRadicalBbut = 0xA49B,
            /// <summary>
            /// YI RADICAL MOP ꒜
            /// </summary>
            YiRadicalMop = 0xA49C,
            /// <summary>
            /// YI RADICAL YO ꒝
            /// </summary>
            YiRadicalYo = 0xA49D,
            /// <summary>
            /// YI RADICAL PUT ꒞
            /// </summary>
            YiRadicalPut = 0xA49E,
            /// <summary>
            /// YI RADICAL HXUO ꒟
            /// </summary>
            YiRadicalHxuo = 0xA49F,
            /// <summary>
            /// YI RADICAL TAT ꒠
            /// </summary>
            YiRadicalTat = 0xA4A0,
            /// <summary>
            /// YI RADICAL GA ꒡
            /// </summary>
            YiRadicalGa = 0xA4A1,
            /// <summary>
            /// YI RADICAL ZUP ꒢
            /// </summary>
            YiRadicalZup = 0xA4A2,
            /// <summary>
            /// YI RADICAL CYT ꒣
            /// </summary>
            YiRadicalCyt = 0xA4A3,
            /// <summary>
            /// YI RADICAL DDUR ꒤
            /// </summary>
            YiRadicalDdur = 0xA4A4,
            /// <summary>
            /// YI RADICAL BUR ꒥
            /// </summary>
            YiRadicalBur = 0xA4A5,
            /// <summary>
            /// YI RADICAL GGUO ꒦
            /// </summary>
            YiRadicalGguo = 0xA4A6,
            /// <summary>
            /// YI RADICAL NYOP ꒧
            /// </summary>
            YiRadicalNyop = 0xA4A7,
            /// <summary>
            /// YI RADICAL TU ꒨
            /// </summary>
            YiRadicalTu = 0xA4A8,
            /// <summary>
            /// YI RADICAL OP ꒩
            /// </summary>
            YiRadicalOp = 0xA4A9,
            /// <summary>
            /// YI RADICAL JJUT ꒪
            /// </summary>
            YiRadicalJjut = 0xA4AA,
            /// <summary>
            /// YI RADICAL ZOT ꒫
            /// </summary>
            YiRadicalZot = 0xA4AB,
            /// <summary>
            /// YI RADICAL PYT ꒬
            /// </summary>
            YiRadicalPyt = 0xA4AC,
            /// <summary>
            /// YI RADICAL HMO ꒭
            /// </summary>
            YiRadicalHmo = 0xA4AD,
            /// <summary>
            /// YI RADICAL YIT ꒮
            /// </summary>
            YiRadicalYit = 0xA4AE,
            /// <summary>
            /// YI RADICAL VUR ꒯
            /// </summary>
            YiRadicalVur = 0xA4AF,
            /// <summary>
            /// YI RADICAL SHY ꒰
            /// </summary>
            YiRadicalShy = 0xA4B0,
            /// <summary>
            /// YI RADICAL VEP ꒱
            /// </summary>
            YiRadicalVep = 0xA4B1,
            /// <summary>
            /// YI RADICAL ZA ꒲
            /// </summary>
            YiRadicalZa = 0xA4B2,
            /// <summary>
            /// YI RADICAL JO ꒳
            /// </summary>
            YiRadicalJo = 0xA4B3,
            /// <summary>
            /// YI RADICAL NZUP ꒴
            /// </summary>
            YiRadicalNzup = 0xA4B4,
            /// <summary>
            /// YI RADICAL JJY ꒵
            /// </summary>
            YiRadicalJjy = 0xA4B5,
            /// <summary>
            /// YI RADICAL GOT ꒶
            /// </summary>
            YiRadicalGot = 0xA4B6,
            /// <summary>
            /// YI RADICAL JJIE ꒷
            /// </summary>
            YiRadicalJjie = 0xA4B7,
            /// <summary>
            /// YI RADICAL WO ꒸
            /// </summary>
            YiRadicalWo = 0xA4B8,
            /// <summary>
            /// YI RADICAL DU ꒹
            /// </summary>
            YiRadicalDu = 0xA4B9,
            /// <summary>
            /// YI RADICAL SHUR ꒺
            /// </summary>
            YiRadicalShur = 0xA4BA,
            /// <summary>
            /// YI RADICAL LIE ꒻
            /// </summary>
            YiRadicalLie = 0xA4BB,
            /// <summary>
            /// YI RADICAL CY ꒼
            /// </summary>
            YiRadicalCy = 0xA4BC,
            /// <summary>
            /// YI RADICAL CUOP ꒽
            /// </summary>
            YiRadicalCuop = 0xA4BD,
            /// <summary>
            /// YI RADICAL CIP ꒾
            /// </summary>
            YiRadicalCip = 0xA4BE,
            /// <summary>
            /// YI RADICAL HXOP ꒿
            /// </summary>
            YiRadicalHxop = 0xA4BF,
            /// <summary>
            /// YI RADICAL SHAT ꓀
            /// </summary>
            YiRadicalShat = 0xA4C0,
            /// <summary>
            /// YI RADICAL ZUR ꓁
            /// </summary>
            YiRadicalZur = 0xA4C1,
            /// <summary>
            /// YI RADICAL SHOP ꓂
            /// </summary>
            YiRadicalShop = 0xA4C2,
            /// <summary>
            /// YI RADICAL CHE ꓃
            /// </summary>
            YiRadicalChe = 0xA4C3,
            /// <summary>
            /// YI RADICAL ZZIET ꓄
            /// </summary>
            YiRadicalZziet = 0xA4C4,
            /// <summary>
            /// YI RADICAL NBIE ꓅
            /// </summary>
            YiRadicalNbie = 0xA4C5,
            /// <summary>
            /// YI RADICAL KE ꓆
            /// </summary>
            YiRadicalKe = 0xA4C6
        }
    }
}
