// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class Shavian
    {
        public enum OtherLetter : int
        {
            /// <summary>
            /// SHAVIAN LETTER PEEP 𐑐
            /// </summary>
            ShavianLetterPeep = 0x10450,
            /// <summary>
            /// SHAVIAN LETTER TOT 𐑑
            /// </summary>
            ShavianLetterTot = 0x10451,
            /// <summary>
            /// SHAVIAN LETTER KICK 𐑒
            /// </summary>
            ShavianLetterKick = 0x10452,
            /// <summary>
            /// SHAVIAN LETTER FEE 𐑓
            /// </summary>
            ShavianLetterFee = 0x10453,
            /// <summary>
            /// SHAVIAN LETTER THIGH 𐑔
            /// </summary>
            ShavianLetterThigh = 0x10454,
            /// <summary>
            /// SHAVIAN LETTER SO 𐑕
            /// </summary>
            ShavianLetterSo = 0x10455,
            /// <summary>
            /// SHAVIAN LETTER SURE 𐑖
            /// </summary>
            ShavianLetterSure = 0x10456,
            /// <summary>
            /// SHAVIAN LETTER CHURCH 𐑗
            /// </summary>
            ShavianLetterChurch = 0x10457,
            /// <summary>
            /// SHAVIAN LETTER YEA 𐑘
            /// </summary>
            ShavianLetterYea = 0x10458,
            /// <summary>
            /// SHAVIAN LETTER HUNG 𐑙
            /// </summary>
            ShavianLetterHung = 0x10459,
            /// <summary>
            /// SHAVIAN LETTER BIB 𐑚
            /// </summary>
            ShavianLetterBib = 0x1045A,
            /// <summary>
            /// SHAVIAN LETTER DEAD 𐑛
            /// </summary>
            ShavianLetterDead = 0x1045B,
            /// <summary>
            /// SHAVIAN LETTER GAG 𐑜
            /// </summary>
            ShavianLetterGag = 0x1045C,
            /// <summary>
            /// SHAVIAN LETTER VOW 𐑝
            /// </summary>
            ShavianLetterVow = 0x1045D,
            /// <summary>
            /// SHAVIAN LETTER THEY 𐑞
            /// </summary>
            ShavianLetterThey = 0x1045E,
            /// <summary>
            /// SHAVIAN LETTER ZOO 𐑟
            /// </summary>
            ShavianLetterZoo = 0x1045F,
            /// <summary>
            /// SHAVIAN LETTER MEASURE 𐑠
            /// </summary>
            ShavianLetterMeasure = 0x10460,
            /// <summary>
            /// SHAVIAN LETTER JUDGE 𐑡
            /// </summary>
            ShavianLetterJudge = 0x10461,
            /// <summary>
            /// SHAVIAN LETTER WOE 𐑢
            /// </summary>
            ShavianLetterWoe = 0x10462,
            /// <summary>
            /// SHAVIAN LETTER HA-HA 𐑣
            /// </summary>
            ShavianLetterHaHa = 0x10463,
            /// <summary>
            /// SHAVIAN LETTER LOLL 𐑤
            /// </summary>
            ShavianLetterLoll = 0x10464,
            /// <summary>
            /// SHAVIAN LETTER MIME 𐑥
            /// </summary>
            ShavianLetterMime = 0x10465,
            /// <summary>
            /// SHAVIAN LETTER IF 𐑦
            /// </summary>
            ShavianLetterIf = 0x10466,
            /// <summary>
            /// SHAVIAN LETTER EGG 𐑧
            /// </summary>
            ShavianLetterEgg = 0x10467,
            /// <summary>
            /// SHAVIAN LETTER ASH 𐑨
            /// </summary>
            ShavianLetterAsh = 0x10468,
            /// <summary>
            /// SHAVIAN LETTER ADO 𐑩
            /// </summary>
            ShavianLetterAdo = 0x10469,
            /// <summary>
            /// SHAVIAN LETTER ON 𐑪
            /// </summary>
            ShavianLetterOn = 0x1046A,
            /// <summary>
            /// SHAVIAN LETTER WOOL 𐑫
            /// </summary>
            ShavianLetterWool = 0x1046B,
            /// <summary>
            /// SHAVIAN LETTER OUT 𐑬
            /// </summary>
            ShavianLetterOut = 0x1046C,
            /// <summary>
            /// SHAVIAN LETTER AH 𐑭
            /// </summary>
            ShavianLetterAh = 0x1046D,
            /// <summary>
            /// SHAVIAN LETTER ROAR 𐑮
            /// </summary>
            ShavianLetterRoar = 0x1046E,
            /// <summary>
            /// SHAVIAN LETTER NUN 𐑯
            /// </summary>
            ShavianLetterNun = 0x1046F,
            /// <summary>
            /// SHAVIAN LETTER EAT 𐑰
            /// </summary>
            ShavianLetterEat = 0x10470,
            /// <summary>
            /// SHAVIAN LETTER AGE 𐑱
            /// </summary>
            ShavianLetterAge = 0x10471,
            /// <summary>
            /// SHAVIAN LETTER ICE 𐑲
            /// </summary>
            ShavianLetterIce = 0x10472,
            /// <summary>
            /// SHAVIAN LETTER UP 𐑳
            /// </summary>
            ShavianLetterUp = 0x10473,
            /// <summary>
            /// SHAVIAN LETTER OAK 𐑴
            /// </summary>
            ShavianLetterOak = 0x10474,
            /// <summary>
            /// SHAVIAN LETTER OOZE 𐑵
            /// </summary>
            ShavianLetterOoze = 0x10475,
            /// <summary>
            /// SHAVIAN LETTER OIL 𐑶
            /// </summary>
            ShavianLetterOil = 0x10476,
            /// <summary>
            /// SHAVIAN LETTER AWE 𐑷
            /// </summary>
            ShavianLetterAwe = 0x10477,
            /// <summary>
            /// SHAVIAN LETTER ARE 𐑸
            /// </summary>
            ShavianLetterAre = 0x10478,
            /// <summary>
            /// SHAVIAN LETTER OR 𐑹
            /// </summary>
            ShavianLetterOr = 0x10479,
            /// <summary>
            /// SHAVIAN LETTER AIR 𐑺
            /// </summary>
            ShavianLetterAir = 0x1047A,
            /// <summary>
            /// SHAVIAN LETTER ERR 𐑻
            /// </summary>
            ShavianLetterErr = 0x1047B,
            /// <summary>
            /// SHAVIAN LETTER ARRAY 𐑼
            /// </summary>
            ShavianLetterArray = 0x1047C,
            /// <summary>
            /// SHAVIAN LETTER EAR 𐑽
            /// </summary>
            ShavianLetterEar = 0x1047D,
            /// <summary>
            /// SHAVIAN LETTER IAN 𐑾
            /// </summary>
            ShavianLetterIan = 0x1047E,
            /// <summary>
            /// SHAVIAN LETTER YEW 𐑿
            /// </summary>
            ShavianLetterYew = 0x1047F
        }
    }
}
