// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class Katakana
    {
        public enum DashPunctuation : int
        {
            /// <summary>
            /// KATAKANA-HIRAGANA DOUBLE HYPHEN ゠
            /// </summary>
            KatakanaHiraganaDoubleHyphen = 0x30A0
        }
        public enum OtherLetter : int
        {
            /// <summary>
            /// KATAKANA LETTER SMALL A ァ
            /// </summary>
            KatakanaLetterSmallA = 0x30A1,
            /// <summary>
            /// KATAKANA LETTER A ア
            /// </summary>
            KatakanaLetterA = 0x30A2,
            /// <summary>
            /// KATAKANA LETTER SMALL I ィ
            /// </summary>
            KatakanaLetterSmallI = 0x30A3,
            /// <summary>
            /// KATAKANA LETTER I イ
            /// </summary>
            KatakanaLetterI = 0x30A4,
            /// <summary>
            /// KATAKANA LETTER SMALL U ゥ
            /// </summary>
            KatakanaLetterSmallU = 0x30A5,
            /// <summary>
            /// KATAKANA LETTER U ウ
            /// </summary>
            KatakanaLetterU = 0x30A6,
            /// <summary>
            /// KATAKANA LETTER SMALL E ェ
            /// </summary>
            KatakanaLetterSmallE = 0x30A7,
            /// <summary>
            /// KATAKANA LETTER E エ
            /// </summary>
            KatakanaLetterE = 0x30A8,
            /// <summary>
            /// KATAKANA LETTER SMALL O ォ
            /// </summary>
            KatakanaLetterSmallO = 0x30A9,
            /// <summary>
            /// KATAKANA LETTER O オ
            /// </summary>
            KatakanaLetterO = 0x30AA,
            /// <summary>
            /// KATAKANA LETTER KA カ
            /// </summary>
            KatakanaLetterKa = 0x30AB,
            /// <summary>
            /// KATAKANA LETTER GA ガ
            /// </summary>
            KatakanaLetterGa = 0x30AC,
            /// <summary>
            /// KATAKANA LETTER KI キ
            /// </summary>
            KatakanaLetterKi = 0x30AD,
            /// <summary>
            /// KATAKANA LETTER GI ギ
            /// </summary>
            KatakanaLetterGi = 0x30AE,
            /// <summary>
            /// KATAKANA LETTER KU ク
            /// </summary>
            KatakanaLetterKu = 0x30AF,
            /// <summary>
            /// KATAKANA LETTER GU グ
            /// </summary>
            KatakanaLetterGu = 0x30B0,
            /// <summary>
            /// KATAKANA LETTER KE ケ
            /// </summary>
            KatakanaLetterKe = 0x30B1,
            /// <summary>
            /// KATAKANA LETTER GE ゲ
            /// </summary>
            KatakanaLetterGe = 0x30B2,
            /// <summary>
            /// KATAKANA LETTER KO コ
            /// </summary>
            KatakanaLetterKo = 0x30B3,
            /// <summary>
            /// KATAKANA LETTER GO ゴ
            /// </summary>
            KatakanaLetterGo = 0x30B4,
            /// <summary>
            /// KATAKANA LETTER SA サ
            /// </summary>
            KatakanaLetterSa = 0x30B5,
            /// <summary>
            /// KATAKANA LETTER ZA ザ
            /// </summary>
            KatakanaLetterZa = 0x30B6,
            /// <summary>
            /// KATAKANA LETTER SI シ
            /// </summary>
            KatakanaLetterSi = 0x30B7,
            /// <summary>
            /// KATAKANA LETTER ZI ジ
            /// </summary>
            KatakanaLetterZi = 0x30B8,
            /// <summary>
            /// KATAKANA LETTER SU ス
            /// </summary>
            KatakanaLetterSu = 0x30B9,
            /// <summary>
            /// KATAKANA LETTER ZU ズ
            /// </summary>
            KatakanaLetterZu = 0x30BA,
            /// <summary>
            /// KATAKANA LETTER SE セ
            /// </summary>
            KatakanaLetterSe = 0x30BB,
            /// <summary>
            /// KATAKANA LETTER ZE ゼ
            /// </summary>
            KatakanaLetterZe = 0x30BC,
            /// <summary>
            /// KATAKANA LETTER SO ソ
            /// </summary>
            KatakanaLetterSo = 0x30BD,
            /// <summary>
            /// KATAKANA LETTER ZO ゾ
            /// </summary>
            KatakanaLetterZo = 0x30BE,
            /// <summary>
            /// KATAKANA LETTER TA タ
            /// </summary>
            KatakanaLetterTa = 0x30BF,
            /// <summary>
            /// KATAKANA LETTER DA ダ
            /// </summary>
            KatakanaLetterDa = 0x30C0,
            /// <summary>
            /// KATAKANA LETTER TI チ
            /// </summary>
            KatakanaLetterTi = 0x30C1,
            /// <summary>
            /// KATAKANA LETTER DI ヂ
            /// </summary>
            KatakanaLetterDi = 0x30C2,
            /// <summary>
            /// KATAKANA LETTER SMALL TU ッ
            /// </summary>
            KatakanaLetterSmallTu = 0x30C3,
            /// <summary>
            /// KATAKANA LETTER TU ツ
            /// </summary>
            KatakanaLetterTu = 0x30C4,
            /// <summary>
            /// KATAKANA LETTER DU ヅ
            /// </summary>
            KatakanaLetterDu = 0x30C5,
            /// <summary>
            /// KATAKANA LETTER TE テ
            /// </summary>
            KatakanaLetterTe = 0x30C6,
            /// <summary>
            /// KATAKANA LETTER DE デ
            /// </summary>
            KatakanaLetterDe = 0x30C7,
            /// <summary>
            /// KATAKANA LETTER TO ト
            /// </summary>
            KatakanaLetterTo = 0x30C8,
            /// <summary>
            /// KATAKANA LETTER DO ド
            /// </summary>
            KatakanaLetterDo = 0x30C9,
            /// <summary>
            /// KATAKANA LETTER NA ナ
            /// </summary>
            KatakanaLetterNa = 0x30CA,
            /// <summary>
            /// KATAKANA LETTER NI ニ
            /// </summary>
            KatakanaLetterNi = 0x30CB,
            /// <summary>
            /// KATAKANA LETTER NU ヌ
            /// </summary>
            KatakanaLetterNu = 0x30CC,
            /// <summary>
            /// KATAKANA LETTER NE ネ
            /// </summary>
            KatakanaLetterNe = 0x30CD,
            /// <summary>
            /// KATAKANA LETTER NO ノ
            /// </summary>
            KatakanaLetterNo = 0x30CE,
            /// <summary>
            /// KATAKANA LETTER HA ハ
            /// </summary>
            KatakanaLetterHa = 0x30CF,
            /// <summary>
            /// KATAKANA LETTER BA バ
            /// </summary>
            KatakanaLetterBa = 0x30D0,
            /// <summary>
            /// KATAKANA LETTER PA パ
            /// </summary>
            KatakanaLetterPa = 0x30D1,
            /// <summary>
            /// KATAKANA LETTER HI ヒ
            /// </summary>
            KatakanaLetterHi = 0x30D2,
            /// <summary>
            /// KATAKANA LETTER BI ビ
            /// </summary>
            KatakanaLetterBi = 0x30D3,
            /// <summary>
            /// KATAKANA LETTER PI ピ
            /// </summary>
            KatakanaLetterPi = 0x30D4,
            /// <summary>
            /// KATAKANA LETTER HU フ
            /// </summary>
            KatakanaLetterHu = 0x30D5,
            /// <summary>
            /// KATAKANA LETTER BU ブ
            /// </summary>
            KatakanaLetterBu = 0x30D6,
            /// <summary>
            /// KATAKANA LETTER PU プ
            /// </summary>
            KatakanaLetterPu = 0x30D7,
            /// <summary>
            /// KATAKANA LETTER HE ヘ
            /// </summary>
            KatakanaLetterHe = 0x30D8,
            /// <summary>
            /// KATAKANA LETTER BE ベ
            /// </summary>
            KatakanaLetterBe = 0x30D9,
            /// <summary>
            /// KATAKANA LETTER PE ペ
            /// </summary>
            KatakanaLetterPe = 0x30DA,
            /// <summary>
            /// KATAKANA LETTER HO ホ
            /// </summary>
            KatakanaLetterHo = 0x30DB,
            /// <summary>
            /// KATAKANA LETTER BO ボ
            /// </summary>
            KatakanaLetterBo = 0x30DC,
            /// <summary>
            /// KATAKANA LETTER PO ポ
            /// </summary>
            KatakanaLetterPo = 0x30DD,
            /// <summary>
            /// KATAKANA LETTER MA マ
            /// </summary>
            KatakanaLetterMa = 0x30DE,
            /// <summary>
            /// KATAKANA LETTER MI ミ
            /// </summary>
            KatakanaLetterMi = 0x30DF,
            /// <summary>
            /// KATAKANA LETTER MU ム
            /// </summary>
            KatakanaLetterMu = 0x30E0,
            /// <summary>
            /// KATAKANA LETTER ME メ
            /// </summary>
            KatakanaLetterMe = 0x30E1,
            /// <summary>
            /// KATAKANA LETTER MO モ
            /// </summary>
            KatakanaLetterMo = 0x30E2,
            /// <summary>
            /// KATAKANA LETTER SMALL YA ャ
            /// </summary>
            KatakanaLetterSmallYa = 0x30E3,
            /// <summary>
            /// KATAKANA LETTER YA ヤ
            /// </summary>
            KatakanaLetterYa = 0x30E4,
            /// <summary>
            /// KATAKANA LETTER SMALL YU ュ
            /// </summary>
            KatakanaLetterSmallYu = 0x30E5,
            /// <summary>
            /// KATAKANA LETTER YU ユ
            /// </summary>
            KatakanaLetterYu = 0x30E6,
            /// <summary>
            /// KATAKANA LETTER SMALL YO ョ
            /// </summary>
            KatakanaLetterSmallYo = 0x30E7,
            /// <summary>
            /// KATAKANA LETTER YO ヨ
            /// </summary>
            KatakanaLetterYo = 0x30E8,
            /// <summary>
            /// KATAKANA LETTER RA ラ
            /// </summary>
            KatakanaLetterRa = 0x30E9,
            /// <summary>
            /// KATAKANA LETTER RI リ
            /// </summary>
            KatakanaLetterRi = 0x30EA,
            /// <summary>
            /// KATAKANA LETTER RU ル
            /// </summary>
            KatakanaLetterRu = 0x30EB,
            /// <summary>
            /// KATAKANA LETTER RE レ
            /// </summary>
            KatakanaLetterRe = 0x30EC,
            /// <summary>
            /// KATAKANA LETTER RO ロ
            /// </summary>
            KatakanaLetterRo = 0x30ED,
            /// <summary>
            /// KATAKANA LETTER SMALL WA ヮ
            /// </summary>
            KatakanaLetterSmallWa = 0x30EE,
            /// <summary>
            /// KATAKANA LETTER WA ワ
            /// </summary>
            KatakanaLetterWa = 0x30EF,
            /// <summary>
            /// KATAKANA LETTER WI ヰ
            /// </summary>
            KatakanaLetterWi = 0x30F0,
            /// <summary>
            /// KATAKANA LETTER WE ヱ
            /// </summary>
            KatakanaLetterWe = 0x30F1,
            /// <summary>
            /// KATAKANA LETTER WO ヲ
            /// </summary>
            KatakanaLetterWo = 0x30F2,
            /// <summary>
            /// KATAKANA LETTER N ン
            /// </summary>
            KatakanaLetterN = 0x30F3,
            /// <summary>
            /// KATAKANA LETTER VU ヴ
            /// </summary>
            KatakanaLetterVu = 0x30F4,
            /// <summary>
            /// KATAKANA LETTER SMALL KA ヵ
            /// </summary>
            KatakanaLetterSmallKa = 0x30F5,
            /// <summary>
            /// KATAKANA LETTER SMALL KE ヶ
            /// </summary>
            KatakanaLetterSmallKe = 0x30F6,
            /// <summary>
            /// KATAKANA LETTER VA ヷ
            /// </summary>
            KatakanaLetterVa = 0x30F7,
            /// <summary>
            /// KATAKANA LETTER VI ヸ
            /// </summary>
            KatakanaLetterVi = 0x30F8,
            /// <summary>
            /// KATAKANA LETTER VE ヹ
            /// </summary>
            KatakanaLetterVe = 0x30F9,
            /// <summary>
            /// KATAKANA LETTER VO ヺ
            /// </summary>
            KatakanaLetterVo = 0x30FA,
            /// <summary>
            /// KATAKANA DIGRAPH KOTO ヿ
            /// </summary>
            KatakanaDigraphKoto = 0x30FF
        }
        public enum OtherPunctuation : int
        {
            /// <summary>
            /// KATAKANA MIDDLE DOT ・
            /// </summary>
            KatakanaMiddleDot = 0x30FB
        }
        public enum ModifierLetter : int
        {
            /// <summary>
            /// KATAKANA-HIRAGANA PROLONGED SOUND MARK ー
            /// </summary>
            KatakanaHiraganaProlongedSoundMark = 0x30FC,
            /// <summary>
            /// KATAKANA ITERATION MARK ヽ
            /// </summary>
            KatakanaIterationMark = 0x30FD,
            /// <summary>
            /// KATAKANA VOICED ITERATION MARK ヾ
            /// </summary>
            KatakanaVoicedIterationMark = 0x30FE
        }
    }
}
