// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    partial struct Char32
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(CJKSymbolsAndPunctuation.SpaceSeparator value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator CJKSymbolsAndPunctuation.SpaceSeparator(Char32 c)
        {
            return (CJKSymbolsAndPunctuation.SpaceSeparator)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(CJKSymbolsAndPunctuation.OtherPunctuation value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator CJKSymbolsAndPunctuation.OtherPunctuation(Char32 c)
        {
            return (CJKSymbolsAndPunctuation.OtherPunctuation)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(CJKSymbolsAndPunctuation.OtherSymbol value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator CJKSymbolsAndPunctuation.OtherSymbol(Char32 c)
        {
            return (CJKSymbolsAndPunctuation.OtherSymbol)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(CJKSymbolsAndPunctuation.ModifierLetter value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator CJKSymbolsAndPunctuation.ModifierLetter(Char32 c)
        {
            return (CJKSymbolsAndPunctuation.ModifierLetter)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(CJKSymbolsAndPunctuation.OtherLetter value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator CJKSymbolsAndPunctuation.OtherLetter(Char32 c)
        {
            return (CJKSymbolsAndPunctuation.OtherLetter)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(CJKSymbolsAndPunctuation.LetterNumber value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator CJKSymbolsAndPunctuation.LetterNumber(Char32 c)
        {
            return (CJKSymbolsAndPunctuation.LetterNumber)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(CJKSymbolsAndPunctuation.OpenPunctuation value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator CJKSymbolsAndPunctuation.OpenPunctuation(Char32 c)
        {
            return (CJKSymbolsAndPunctuation.OpenPunctuation)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(CJKSymbolsAndPunctuation.ClosePunctuation value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator CJKSymbolsAndPunctuation.ClosePunctuation(Char32 c)
        {
            return (CJKSymbolsAndPunctuation.ClosePunctuation)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(CJKSymbolsAndPunctuation.DashPunctuation value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator CJKSymbolsAndPunctuation.DashPunctuation(Char32 c)
        {
            return (CJKSymbolsAndPunctuation.DashPunctuation)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(CJKSymbolsAndPunctuation.NonSpacingMark value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator CJKSymbolsAndPunctuation.NonSpacingMark(Char32 c)
        {
            return (CJKSymbolsAndPunctuation.NonSpacingMark)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(CJKSymbolsAndPunctuation.SpacingCombiningMark value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator CJKSymbolsAndPunctuation.SpacingCombiningMark(Char32 c)
        {
            return (CJKSymbolsAndPunctuation.SpacingCombiningMark)c.Value;
        }
    }
}
