// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class Tibetan
    {
        public enum OtherLetter : int
        {
            /// <summary>
            /// TIBETAN SYLLABLE OM ༀ
            /// </summary>
            TibetanSyllableOm = 0x0F00,
            /// <summary>
            /// TIBETAN LETTER KA ཀ
            /// </summary>
            TibetanLetterKa = 0x0F40,
            /// <summary>
            /// TIBETAN LETTER KHA ཁ
            /// </summary>
            TibetanLetterKha = 0x0F41,
            /// <summary>
            /// TIBETAN LETTER GA ག
            /// </summary>
            TibetanLetterGa = 0x0F42,
            /// <summary>
            /// TIBETAN LETTER GHA གྷ
            /// </summary>
            TibetanLetterGha = 0x0F43,
            /// <summary>
            /// TIBETAN LETTER NGA ང
            /// </summary>
            TibetanLetterNga = 0x0F44,
            /// <summary>
            /// TIBETAN LETTER CA ཅ
            /// </summary>
            TibetanLetterCa = 0x0F45,
            /// <summary>
            /// TIBETAN LETTER CHA ཆ
            /// </summary>
            TibetanLetterCha = 0x0F46,
            /// <summary>
            /// TIBETAN LETTER JA ཇ
            /// </summary>
            TibetanLetterJa = 0x0F47,
            /// <summary>
            /// TIBETAN LETTER NYA ཉ
            /// </summary>
            TibetanLetterNya = 0x0F49,
            /// <summary>
            /// TIBETAN LETTER TTA ཊ
            /// </summary>
            TibetanLetterTta = 0x0F4A,
            /// <summary>
            /// TIBETAN LETTER TTHA ཋ
            /// </summary>
            TibetanLetterTtha = 0x0F4B,
            /// <summary>
            /// TIBETAN LETTER DDA ཌ
            /// </summary>
            TibetanLetterDda = 0x0F4C,
            /// <summary>
            /// TIBETAN LETTER DDHA ཌྷ
            /// </summary>
            TibetanLetterDdha = 0x0F4D,
            /// <summary>
            /// TIBETAN LETTER NNA ཎ
            /// </summary>
            TibetanLetterNna = 0x0F4E,
            /// <summary>
            /// TIBETAN LETTER TA ཏ
            /// </summary>
            TibetanLetterTa = 0x0F4F,
            /// <summary>
            /// TIBETAN LETTER THA ཐ
            /// </summary>
            TibetanLetterTha = 0x0F50,
            /// <summary>
            /// TIBETAN LETTER DA ད
            /// </summary>
            TibetanLetterDa = 0x0F51,
            /// <summary>
            /// TIBETAN LETTER DHA དྷ
            /// </summary>
            TibetanLetterDha = 0x0F52,
            /// <summary>
            /// TIBETAN LETTER NA ན
            /// </summary>
            TibetanLetterNa = 0x0F53,
            /// <summary>
            /// TIBETAN LETTER PA པ
            /// </summary>
            TibetanLetterPa = 0x0F54,
            /// <summary>
            /// TIBETAN LETTER PHA ཕ
            /// </summary>
            TibetanLetterPha = 0x0F55,
            /// <summary>
            /// TIBETAN LETTER BA བ
            /// </summary>
            TibetanLetterBa = 0x0F56,
            /// <summary>
            /// TIBETAN LETTER BHA བྷ
            /// </summary>
            TibetanLetterBha = 0x0F57,
            /// <summary>
            /// TIBETAN LETTER MA མ
            /// </summary>
            TibetanLetterMa = 0x0F58,
            /// <summary>
            /// TIBETAN LETTER TSA ཙ
            /// </summary>
            TibetanLetterTsa = 0x0F59,
            /// <summary>
            /// TIBETAN LETTER TSHA ཚ
            /// </summary>
            TibetanLetterTsha = 0x0F5A,
            /// <summary>
            /// TIBETAN LETTER DZA ཛ
            /// </summary>
            TibetanLetterDza = 0x0F5B,
            /// <summary>
            /// TIBETAN LETTER DZHA ཛྷ
            /// </summary>
            TibetanLetterDzha = 0x0F5C,
            /// <summary>
            /// TIBETAN LETTER WA ཝ
            /// </summary>
            TibetanLetterWa = 0x0F5D,
            /// <summary>
            /// TIBETAN LETTER ZHA ཞ
            /// </summary>
            TibetanLetterZha = 0x0F5E,
            /// <summary>
            /// TIBETAN LETTER ZA ཟ
            /// </summary>
            TibetanLetterZa = 0x0F5F,
            /// <summary>
            /// TIBETAN LETTER -A འ
            /// </summary>
            TibetanLetterDashA = 0x0F60,
            /// <summary>
            /// TIBETAN LETTER YA ཡ
            /// </summary>
            TibetanLetterYa = 0x0F61,
            /// <summary>
            /// TIBETAN LETTER RA ར
            /// </summary>
            TibetanLetterRa = 0x0F62,
            /// <summary>
            /// TIBETAN LETTER LA ལ
            /// </summary>
            TibetanLetterLa = 0x0F63,
            /// <summary>
            /// TIBETAN LETTER SHA ཤ
            /// </summary>
            TibetanLetterSha = 0x0F64,
            /// <summary>
            /// TIBETAN LETTER SSA ཥ
            /// </summary>
            TibetanLetterSsa = 0x0F65,
            /// <summary>
            /// TIBETAN LETTER SA ས
            /// </summary>
            TibetanLetterSa = 0x0F66,
            /// <summary>
            /// TIBETAN LETTER HA ཧ
            /// </summary>
            TibetanLetterHa = 0x0F67,
            /// <summary>
            /// TIBETAN LETTER A ཨ
            /// </summary>
            TibetanLetterA = 0x0F68,
            /// <summary>
            /// TIBETAN LETTER KSSA ཀྵ
            /// </summary>
            TibetanLetterKssa = 0x0F69,
            /// <summary>
            /// TIBETAN LETTER FIXED-FORM RA ཪ
            /// </summary>
            TibetanLetterFixedFormRa = 0x0F6A,
            /// <summary>
            /// TIBETAN LETTER KKA ཫ
            /// </summary>
            TibetanLetterKka = 0x0F6B,
            /// <summary>
            /// TIBETAN LETTER RRA ཬ
            /// </summary>
            TibetanLetterRra = 0x0F6C,
            /// <summary>
            /// TIBETAN SIGN LCE TSA CAN ྈ
            /// </summary>
            TibetanSignLceTsaCan = 0x0F88,
            /// <summary>
            /// TIBETAN SIGN MCHU CAN ྉ
            /// </summary>
            TibetanSignMchuCan = 0x0F89,
            /// <summary>
            /// TIBETAN SIGN GRU CAN RGYINGS ྊ
            /// </summary>
            TibetanSignGruCanRgyings = 0x0F8A,
            /// <summary>
            /// TIBETAN SIGN GRU MED RGYINGS ྋ
            /// </summary>
            TibetanSignGruMedRgyings = 0x0F8B,
            /// <summary>
            /// TIBETAN SIGN INVERTED MCHU CAN ྌ
            /// </summary>
            TibetanSignInvertedMchuCan = 0x0F8C
        }
        public enum OtherSymbol : int
        {
            /// <summary>
            /// TIBETAN MARK GTER YIG MGO TRUNCATED A ༁
            /// </summary>
            TibetanMarkGterYigMgoTruncatedA = 0x0F01,
            /// <summary>
            /// TIBETAN MARK GTER YIG MGO -UM RNAM BCAD MA ༂
            /// </summary>
            TibetanMarkGterYigMgoUmRnamBcadMa = 0x0F02,
            /// <summary>
            /// TIBETAN MARK GTER YIG MGO -UM GTER TSHEG MA ༃
            /// </summary>
            TibetanMarkGterYigMgoUmGterTshegMa = 0x0F03,
            /// <summary>
            /// TIBETAN MARK CARET -DZUD RTAGS ME LONG CAN ༓
            /// </summary>
            TibetanMarkCaretDzudRtagsMeLongCan = 0x0F13,
            /// <summary>
            /// TIBETAN LOGOTYPE SIGN CHAD RTAGS ༕
            /// </summary>
            TibetanLogotypeSignChadRtags = 0x0F15,
            /// <summary>
            /// TIBETAN LOGOTYPE SIGN LHAG RTAGS ༖
            /// </summary>
            TibetanLogotypeSignLhagRtags = 0x0F16,
            /// <summary>
            /// TIBETAN ASTROLOGICAL SIGN SGRA GCAN -CHAR RTAGS ༗
            /// </summary>
            TibetanAstrologicalSignSgraGcanCharRtags = 0x0F17,
            /// <summary>
            /// TIBETAN SIGN RDEL DKAR GCIG ༚
            /// </summary>
            TibetanSignRdelDkarGcig = 0x0F1A,
            /// <summary>
            /// TIBETAN SIGN RDEL DKAR GNYIS ༛
            /// </summary>
            TibetanSignRdelDkarGnyis = 0x0F1B,
            /// <summary>
            /// TIBETAN SIGN RDEL DKAR GSUM ༜
            /// </summary>
            TibetanSignRdelDkarGsum = 0x0F1C,
            /// <summary>
            /// TIBETAN SIGN RDEL NAG GCIG ༝
            /// </summary>
            TibetanSignRdelNagGcig = 0x0F1D,
            /// <summary>
            /// TIBETAN SIGN RDEL NAG GNYIS ༞
            /// </summary>
            TibetanSignRdelNagGnyis = 0x0F1E,
            /// <summary>
            /// TIBETAN SIGN RDEL DKAR RDEL NAG ༟
            /// </summary>
            TibetanSignRdelDkarRdelNag = 0x0F1F,
            /// <summary>
            /// TIBETAN MARK BSDUS RTAGS ༴
            /// </summary>
            TibetanMarkBsdusRtags = 0x0F34,
            /// <summary>
            /// TIBETAN MARK CARET -DZUD RTAGS BZHI MIG CAN ༶
            /// </summary>
            TibetanMarkCaretDzudRtagsBzhiMigCan = 0x0F36,
            /// <summary>
            /// TIBETAN MARK CHE MGO ༸
            /// </summary>
            TibetanMarkCheMgo = 0x0F38,
            /// <summary>
            /// TIBETAN KU RU KHA ྾
            /// </summary>
            TibetanKuRuKha = 0x0FBE,
            /// <summary>
            /// TIBETAN KU RU KHA BZHI MIG CAN ྿
            /// </summary>
            TibetanKuRuKhaBzhiMigCan = 0x0FBF,
            /// <summary>
            /// TIBETAN CANTILLATION SIGN HEAVY BEAT ࿀
            /// </summary>
            TibetanCantillationSignHeavyBeat = 0x0FC0,
            /// <summary>
            /// TIBETAN CANTILLATION SIGN LIGHT BEAT ࿁
            /// </summary>
            TibetanCantillationSignLightBeat = 0x0FC1,
            /// <summary>
            /// TIBETAN CANTILLATION SIGN CANG TE-U ࿂
            /// </summary>
            TibetanCantillationSignCangTeU = 0x0FC2,
            /// <summary>
            /// TIBETAN CANTILLATION SIGN SBUB -CHAL ࿃
            /// </summary>
            TibetanCantillationSignSbubChal = 0x0FC3,
            /// <summary>
            /// TIBETAN SYMBOL DRIL BU ࿄
            /// </summary>
            TibetanSymbolDrilBu = 0x0FC4,
            /// <summary>
            /// TIBETAN SYMBOL RDO RJE ࿅
            /// </summary>
            TibetanSymbolRdoRje = 0x0FC5,
            /// <summary>
            /// TIBETAN SYMBOL RDO RJE RGYA GRAM ࿇
            /// </summary>
            TibetanSymbolRdoRjeRgyaGram = 0x0FC7,
            /// <summary>
            /// TIBETAN SYMBOL PHUR PA ࿈
            /// </summary>
            TibetanSymbolPhurPa = 0x0FC8,
            /// <summary>
            /// TIBETAN SYMBOL NOR BU ࿉
            /// </summary>
            TibetanSymbolNorBu = 0x0FC9,
            /// <summary>
            /// TIBETAN SYMBOL NOR BU NYIS -KHYIL ࿊
            /// </summary>
            TibetanSymbolNorBuNyisKhyil = 0x0FCA,
            /// <summary>
            /// TIBETAN SYMBOL NOR BU GSUM -KHYIL ࿋
            /// </summary>
            TibetanSymbolNorBuGsumKhyil = 0x0FCB,
            /// <summary>
            /// TIBETAN SYMBOL NOR BU BZHI -KHYIL ࿌
            /// </summary>
            TibetanSymbolNorBuBzhiKhyil = 0x0FCC,
            /// <summary>
            /// TIBETAN SIGN RDEL NAG RDEL DKAR ࿎
            /// </summary>
            TibetanSignRdelNagRdelDkar = 0x0FCE,
            /// <summary>
            /// TIBETAN SIGN RDEL NAG GSUM ࿏
            /// </summary>
            TibetanSignRdelNagGsum = 0x0FCF,
            /// <summary>
            /// RIGHT-FACING SVASTI SIGN ࿕
            /// </summary>
            RightFacingSvastiSign = 0x0FD5,
            /// <summary>
            /// LEFT-FACING SVASTI SIGN ࿖
            /// </summary>
            LeftFacingSvastiSign = 0x0FD6,
            /// <summary>
            /// RIGHT-FACING SVASTI SIGN WITH DOTS ࿗
            /// </summary>
            RightFacingSvastiSignWithDots = 0x0FD7,
            /// <summary>
            /// LEFT-FACING SVASTI SIGN WITH DOTS ࿘
            /// </summary>
            LeftFacingSvastiSignWithDots = 0x0FD8
        }
        public enum OtherPunctuation : int
        {
            /// <summary>
            /// TIBETAN MARK INITIAL YIG MGO MDUN MA ༄
            /// </summary>
            TibetanMarkInitialYigMgoMdunMa = 0x0F04,
            /// <summary>
            /// TIBETAN MARK CLOSING YIG MGO SGAB MA ༅
            /// </summary>
            TibetanMarkClosingYigMgoSgabMa = 0x0F05,
            /// <summary>
            /// TIBETAN MARK CARET YIG MGO PHUR SHAD MA ༆
            /// </summary>
            TibetanMarkCaretYigMgoPhurShadMa = 0x0F06,
            /// <summary>
            /// TIBETAN MARK YIG MGO TSHEG SHAD MA ༇
            /// </summary>
            TibetanMarkYigMgoTshegShadMa = 0x0F07,
            /// <summary>
            /// TIBETAN MARK SBRUL SHAD ༈
            /// </summary>
            TibetanMarkSbrulShad = 0x0F08,
            /// <summary>
            /// TIBETAN MARK BSKUR YIG MGO ༉
            /// </summary>
            TibetanMarkBskurYigMgo = 0x0F09,
            /// <summary>
            /// TIBETAN MARK BKA- SHOG YIG MGO ༊
            /// </summary>
            TibetanMarkBkaShogYigMgo = 0x0F0A,
            /// <summary>
            /// TIBETAN MARK INTERSYLLABIC TSHEG ་
            /// </summary>
            TibetanMarkIntersyllabicTsheg = 0x0F0B,
            /// <summary>
            /// TIBETAN MARK DELIMITER TSHEG BSTAR ༌
            /// </summary>
            TibetanMarkDelimiterTshegBstar = 0x0F0C,
            /// <summary>
            /// TIBETAN MARK SHAD །
            /// </summary>
            TibetanMarkShad = 0x0F0D,
            /// <summary>
            /// TIBETAN MARK NYIS SHAD ༎
            /// </summary>
            TibetanMarkNyisShad = 0x0F0E,
            /// <summary>
            /// TIBETAN MARK TSHEG SHAD ༏
            /// </summary>
            TibetanMarkTshegShad = 0x0F0F,
            /// <summary>
            /// TIBETAN MARK NYIS TSHEG SHAD ༐
            /// </summary>
            TibetanMarkNyisTshegShad = 0x0F10,
            /// <summary>
            /// TIBETAN MARK RIN CHEN SPUNGS SHAD ༑
            /// </summary>
            TibetanMarkRinChenSpungsShad = 0x0F11,
            /// <summary>
            /// TIBETAN MARK RGYA GRAM SHAD ༒
            /// </summary>
            TibetanMarkRgyaGramShad = 0x0F12,
            /// <summary>
            /// TIBETAN MARK GTER TSHEG ༔
            /// </summary>
            TibetanMarkGterTsheg = 0x0F14,
            /// <summary>
            /// TIBETAN MARK PALUTA ྅
            /// </summary>
            TibetanMarkPaluta = 0x0F85,
            /// <summary>
            /// TIBETAN MARK BSKA- SHOG GI MGO RGYAN ࿐
            /// </summary>
            TibetanMarkBskaShogGiMgoRgyan = 0x0FD0,
            /// <summary>
            /// TIBETAN MARK MNYAM YIG GI MGO RGYAN ࿑
            /// </summary>
            TibetanMarkMnyamYigGiMgoRgyan = 0x0FD1,
            /// <summary>
            /// TIBETAN MARK NYIS TSHEG ࿒
            /// </summary>
            TibetanMarkNyisTsheg = 0x0FD2,
            /// <summary>
            /// TIBETAN MARK INITIAL BRDA RNYING YIG MGO MDUN MA ࿓
            /// </summary>
            TibetanMarkInitialBrdaRnyingYigMgoMdunMa = 0x0FD3,
            /// <summary>
            /// TIBETAN MARK CLOSING BRDA RNYING YIG MGO SGAB MA ࿔
            /// </summary>
            TibetanMarkClosingBrdaRnyingYigMgoSgabMa = 0x0FD4,
            /// <summary>
            /// TIBETAN MARK LEADING MCHAN RTAGS ࿙
            /// </summary>
            TibetanMarkLeadingMchanRtags = 0x0FD9,
            /// <summary>
            /// TIBETAN MARK TRAILING MCHAN RTAGS ࿚
            /// </summary>
            TibetanMarkTrailingMchanRtags = 0x0FDA
        }
        public enum NonSpacingMark : int
        {
            /// <summary>
            /// TIBETAN ASTROLOGICAL SIGN -KHYUD PA ༘
            /// </summary>
            TibetanAstrologicalSignKhyudPa = 0x0F18,
            /// <summary>
            /// TIBETAN ASTROLOGICAL SIGN SDONG TSHUGS ༙
            /// </summary>
            TibetanAstrologicalSignSdongTshugs = 0x0F19,
            /// <summary>
            /// TIBETAN MARK NGAS BZUNG NYI ZLA ༵
            /// </summary>
            TibetanMarkNgasBzungNyiZla = 0x0F35,
            /// <summary>
            /// TIBETAN MARK NGAS BZUNG SGOR RTAGS ༷
            /// </summary>
            TibetanMarkNgasBzungSgorRtags = 0x0F37,
            /// <summary>
            /// TIBETAN MARK TSA -PHRU ༹
            /// </summary>
            TibetanMarkTsaPhru = 0x0F39,
            /// <summary>
            /// TIBETAN VOWEL SIGN AA ཱ
            /// </summary>
            TibetanVowelSignAa = 0x0F71,
            /// <summary>
            /// TIBETAN VOWEL SIGN I ི
            /// </summary>
            TibetanVowelSignI = 0x0F72,
            /// <summary>
            /// TIBETAN VOWEL SIGN II ཱི
            /// </summary>
            TibetanVowelSignIi = 0x0F73,
            /// <summary>
            /// TIBETAN VOWEL SIGN U ུ
            /// </summary>
            TibetanVowelSignU = 0x0F74,
            /// <summary>
            /// TIBETAN VOWEL SIGN UU ཱུ
            /// </summary>
            TibetanVowelSignUu = 0x0F75,
            /// <summary>
            /// TIBETAN VOWEL SIGN VOCALIC R ྲྀ
            /// </summary>
            TibetanVowelSignVocalicR = 0x0F76,
            /// <summary>
            /// TIBETAN VOWEL SIGN VOCALIC RR ཷ
            /// </summary>
            TibetanVowelSignVocalicRr = 0x0F77,
            /// <summary>
            /// TIBETAN VOWEL SIGN VOCALIC L ླྀ
            /// </summary>
            TibetanVowelSignVocalicL = 0x0F78,
            /// <summary>
            /// TIBETAN VOWEL SIGN VOCALIC LL ཹ
            /// </summary>
            TibetanVowelSignVocalicLl = 0x0F79,
            /// <summary>
            /// TIBETAN VOWEL SIGN E ེ
            /// </summary>
            TibetanVowelSignE = 0x0F7A,
            /// <summary>
            /// TIBETAN VOWEL SIGN EE ཻ
            /// </summary>
            TibetanVowelSignEe = 0x0F7B,
            /// <summary>
            /// TIBETAN VOWEL SIGN O ོ
            /// </summary>
            TibetanVowelSignO = 0x0F7C,
            /// <summary>
            /// TIBETAN VOWEL SIGN OO ཽ
            /// </summary>
            TibetanVowelSignOo = 0x0F7D,
            /// <summary>
            /// TIBETAN SIGN RJES SU NGA RO ཾ
            /// </summary>
            TibetanSignRjesSuNgaRo = 0x0F7E,
            /// <summary>
            /// TIBETAN VOWEL SIGN REVERSED I ྀ
            /// </summary>
            TibetanVowelSignReversedI = 0x0F80,
            /// <summary>
            /// TIBETAN VOWEL SIGN REVERSED II ཱྀ
            /// </summary>
            TibetanVowelSignReversedIi = 0x0F81,
            /// <summary>
            /// TIBETAN SIGN NYI ZLA NAA DA ྂ
            /// </summary>
            TibetanSignNyiZlaNaaDa = 0x0F82,
            /// <summary>
            /// TIBETAN SIGN SNA LDAN ྃ
            /// </summary>
            TibetanSignSnaLdan = 0x0F83,
            /// <summary>
            /// TIBETAN MARK HALANTA ྄
            /// </summary>
            TibetanMarkHalanta = 0x0F84,
            /// <summary>
            /// TIBETAN SIGN LCI RTAGS ྆
            /// </summary>
            TibetanSignLciRtags = 0x0F86,
            /// <summary>
            /// TIBETAN SIGN YANG RTAGS ྇
            /// </summary>
            TibetanSignYangRtags = 0x0F87,
            /// <summary>
            /// TIBETAN SUBJOINED SIGN LCE TSA CAN ྍ
            /// </summary>
            TibetanSubjoinedSignLceTsaCan = 0x0F8D,
            /// <summary>
            /// TIBETAN SUBJOINED SIGN MCHU CAN ྎ
            /// </summary>
            TibetanSubjoinedSignMchuCan = 0x0F8E,
            /// <summary>
            /// TIBETAN SUBJOINED SIGN INVERTED MCHU CAN ྏ
            /// </summary>
            TibetanSubjoinedSignInvertedMchuCan = 0x0F8F,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER KA ྐ
            /// </summary>
            TibetanSubjoinedLetterKa = 0x0F90,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER KHA ྑ
            /// </summary>
            TibetanSubjoinedLetterKha = 0x0F91,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER GA ྒ
            /// </summary>
            TibetanSubjoinedLetterGa = 0x0F92,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER GHA ྒྷ
            /// </summary>
            TibetanSubjoinedLetterGha = 0x0F93,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER NGA ྔ
            /// </summary>
            TibetanSubjoinedLetterNga = 0x0F94,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER CA ྕ
            /// </summary>
            TibetanSubjoinedLetterCa = 0x0F95,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER CHA ྖ
            /// </summary>
            TibetanSubjoinedLetterCha = 0x0F96,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER JA ྗ
            /// </summary>
            TibetanSubjoinedLetterJa = 0x0F97,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER NYA ྙ
            /// </summary>
            TibetanSubjoinedLetterNya = 0x0F99,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER TTA ྚ
            /// </summary>
            TibetanSubjoinedLetterTta = 0x0F9A,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER TTHA ྛ
            /// </summary>
            TibetanSubjoinedLetterTtha = 0x0F9B,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER DDA ྜ
            /// </summary>
            TibetanSubjoinedLetterDda = 0x0F9C,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER DDHA ྜྷ
            /// </summary>
            TibetanSubjoinedLetterDdha = 0x0F9D,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER NNA ྞ
            /// </summary>
            TibetanSubjoinedLetterNna = 0x0F9E,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER TA ྟ
            /// </summary>
            TibetanSubjoinedLetterTa = 0x0F9F,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER THA ྠ
            /// </summary>
            TibetanSubjoinedLetterTha = 0x0FA0,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER DA ྡ
            /// </summary>
            TibetanSubjoinedLetterDa = 0x0FA1,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER DHA ྡྷ
            /// </summary>
            TibetanSubjoinedLetterDha = 0x0FA2,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER NA ྣ
            /// </summary>
            TibetanSubjoinedLetterNa = 0x0FA3,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER PA ྤ
            /// </summary>
            TibetanSubjoinedLetterPa = 0x0FA4,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER PHA ྥ
            /// </summary>
            TibetanSubjoinedLetterPha = 0x0FA5,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER BA ྦ
            /// </summary>
            TibetanSubjoinedLetterBa = 0x0FA6,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER BHA ྦྷ
            /// </summary>
            TibetanSubjoinedLetterBha = 0x0FA7,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER MA ྨ
            /// </summary>
            TibetanSubjoinedLetterMa = 0x0FA8,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER TSA ྩ
            /// </summary>
            TibetanSubjoinedLetterTsa = 0x0FA9,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER TSHA ྪ
            /// </summary>
            TibetanSubjoinedLetterTsha = 0x0FAA,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER DZA ྫ
            /// </summary>
            TibetanSubjoinedLetterDza = 0x0FAB,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER DZHA ྫྷ
            /// </summary>
            TibetanSubjoinedLetterDzha = 0x0FAC,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER WA ྭ
            /// </summary>
            TibetanSubjoinedLetterWa = 0x0FAD,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER ZHA ྮ
            /// </summary>
            TibetanSubjoinedLetterZha = 0x0FAE,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER ZA ྯ
            /// </summary>
            TibetanSubjoinedLetterZa = 0x0FAF,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER -A ྰ
            /// </summary>
            TibetanSubjoinedLetterDashA = 0x0FB0,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER YA ྱ
            /// </summary>
            TibetanSubjoinedLetterYa = 0x0FB1,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER RA ྲ
            /// </summary>
            TibetanSubjoinedLetterRa = 0x0FB2,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER LA ླ
            /// </summary>
            TibetanSubjoinedLetterLa = 0x0FB3,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER SHA ྴ
            /// </summary>
            TibetanSubjoinedLetterSha = 0x0FB4,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER SSA ྵ
            /// </summary>
            TibetanSubjoinedLetterSsa = 0x0FB5,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER SA ྶ
            /// </summary>
            TibetanSubjoinedLetterSa = 0x0FB6,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER HA ྷ
            /// </summary>
            TibetanSubjoinedLetterHa = 0x0FB7,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER A ྸ
            /// </summary>
            TibetanSubjoinedLetterA = 0x0FB8,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER KSSA ྐྵ
            /// </summary>
            TibetanSubjoinedLetterKssa = 0x0FB9,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER FIXED-FORM WA ྺ
            /// </summary>
            TibetanSubjoinedLetterFixedFormWa = 0x0FBA,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER FIXED-FORM YA ྻ
            /// </summary>
            TibetanSubjoinedLetterFixedFormYa = 0x0FBB,
            /// <summary>
            /// TIBETAN SUBJOINED LETTER FIXED-FORM RA ྼ
            /// </summary>
            TibetanSubjoinedLetterFixedFormRa = 0x0FBC,
            /// <summary>
            /// TIBETAN SYMBOL PADMA GDAN ࿆
            /// </summary>
            TibetanSymbolPadmaGdan = 0x0FC6
        }
        public enum DecimalDigitNumber : int
        {
            /// <summary>
            /// TIBETAN DIGIT ZERO ༠
            /// </summary>
            TibetanDigitZero = 0x0F20,
            /// <summary>
            /// TIBETAN DIGIT ONE ༡
            /// </summary>
            TibetanDigitOne = 0x0F21,
            /// <summary>
            /// TIBETAN DIGIT TWO ༢
            /// </summary>
            TibetanDigitTwo = 0x0F22,
            /// <summary>
            /// TIBETAN DIGIT THREE ༣
            /// </summary>
            TibetanDigitThree = 0x0F23,
            /// <summary>
            /// TIBETAN DIGIT FOUR ༤
            /// </summary>
            TibetanDigitFour = 0x0F24,
            /// <summary>
            /// TIBETAN DIGIT FIVE ༥
            /// </summary>
            TibetanDigitFive = 0x0F25,
            /// <summary>
            /// TIBETAN DIGIT SIX ༦
            /// </summary>
            TibetanDigitSix = 0x0F26,
            /// <summary>
            /// TIBETAN DIGIT SEVEN ༧
            /// </summary>
            TibetanDigitSeven = 0x0F27,
            /// <summary>
            /// TIBETAN DIGIT EIGHT ༨
            /// </summary>
            TibetanDigitEight = 0x0F28,
            /// <summary>
            /// TIBETAN DIGIT NINE ༩
            /// </summary>
            TibetanDigitNine = 0x0F29
        }
        public enum OtherNumber : int
        {
            /// <summary>
            /// TIBETAN DIGIT HALF ONE ༪
            /// </summary>
            TibetanDigitHalfOne = 0x0F2A,
            /// <summary>
            /// TIBETAN DIGIT HALF TWO ༫
            /// </summary>
            TibetanDigitHalfTwo = 0x0F2B,
            /// <summary>
            /// TIBETAN DIGIT HALF THREE ༬
            /// </summary>
            TibetanDigitHalfThree = 0x0F2C,
            /// <summary>
            /// TIBETAN DIGIT HALF FOUR ༭
            /// </summary>
            TibetanDigitHalfFour = 0x0F2D,
            /// <summary>
            /// TIBETAN DIGIT HALF FIVE ༮
            /// </summary>
            TibetanDigitHalfFive = 0x0F2E,
            /// <summary>
            /// TIBETAN DIGIT HALF SIX ༯
            /// </summary>
            TibetanDigitHalfSix = 0x0F2F,
            /// <summary>
            /// TIBETAN DIGIT HALF SEVEN ༰
            /// </summary>
            TibetanDigitHalfSeven = 0x0F30,
            /// <summary>
            /// TIBETAN DIGIT HALF EIGHT ༱
            /// </summary>
            TibetanDigitHalfEight = 0x0F31,
            /// <summary>
            /// TIBETAN DIGIT HALF NINE ༲
            /// </summary>
            TibetanDigitHalfNine = 0x0F32,
            /// <summary>
            /// TIBETAN DIGIT HALF ZERO ༳
            /// </summary>
            TibetanDigitHalfZero = 0x0F33
        }
        public enum OpenPunctuation : int
        {
            /// <summary>
            /// TIBETAN MARK GUG RTAGS GYON ༺
            /// </summary>
            TibetanMarkGugRtagsGyon = 0x0F3A,
            /// <summary>
            /// TIBETAN MARK ANG KHANG GYON ༼
            /// </summary>
            TibetanMarkAngKhangGyon = 0x0F3C
        }
        public enum ClosePunctuation : int
        {
            /// <summary>
            /// TIBETAN MARK GUG RTAGS GYAS ༻
            /// </summary>
            TibetanMarkGugRtagsGyas = 0x0F3B,
            /// <summary>
            /// TIBETAN MARK ANG KHANG GYAS ༽
            /// </summary>
            TibetanMarkAngKhangGyas = 0x0F3D
        }
        public enum SpacingCombiningMark : int
        {
            /// <summary>
            /// TIBETAN SIGN YAR TSHES ༾
            /// </summary>
            TibetanSignYarTshes = 0x0F3E,
            /// <summary>
            /// TIBETAN SIGN MAR TSHES ༿
            /// </summary>
            TibetanSignMarTshes = 0x0F3F,
            /// <summary>
            /// TIBETAN SIGN RNAM BCAD ཿ
            /// </summary>
            TibetanSignRnamBcad = 0x0F7F
        }
    }
}
