// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class Lycian
    {
        public enum OtherLetter : int
        {
            /// <summary>
            /// LYCIAN LETTER A 𐊀
            /// </summary>
            LycianLetterA = 0x10280,
            /// <summary>
            /// LYCIAN LETTER E 𐊁
            /// </summary>
            LycianLetterE = 0x10281,
            /// <summary>
            /// LYCIAN LETTER B 𐊂
            /// </summary>
            LycianLetterB = 0x10282,
            /// <summary>
            /// LYCIAN LETTER BH 𐊃
            /// </summary>
            LycianLetterBh = 0x10283,
            /// <summary>
            /// LYCIAN LETTER G 𐊄
            /// </summary>
            LycianLetterG = 0x10284,
            /// <summary>
            /// LYCIAN LETTER D 𐊅
            /// </summary>
            LycianLetterD = 0x10285,
            /// <summary>
            /// LYCIAN LETTER I 𐊆
            /// </summary>
            LycianLetterI = 0x10286,
            /// <summary>
            /// LYCIAN LETTER W 𐊇
            /// </summary>
            LycianLetterW = 0x10287,
            /// <summary>
            /// LYCIAN LETTER Z 𐊈
            /// </summary>
            LycianLetterZ = 0x10288,
            /// <summary>
            /// LYCIAN LETTER TH 𐊉
            /// </summary>
            LycianLetterTh = 0x10289,
            /// <summary>
            /// LYCIAN LETTER J 𐊊
            /// </summary>
            LycianLetterJ = 0x1028A,
            /// <summary>
            /// LYCIAN LETTER K 𐊋
            /// </summary>
            LycianLetterK = 0x1028B,
            /// <summary>
            /// LYCIAN LETTER Q 𐊌
            /// </summary>
            LycianLetterQ = 0x1028C,
            /// <summary>
            /// LYCIAN LETTER L 𐊍
            /// </summary>
            LycianLetterL = 0x1028D,
            /// <summary>
            /// LYCIAN LETTER M 𐊎
            /// </summary>
            LycianLetterM = 0x1028E,
            /// <summary>
            /// LYCIAN LETTER N 𐊏
            /// </summary>
            LycianLetterN = 0x1028F,
            /// <summary>
            /// LYCIAN LETTER MM 𐊐
            /// </summary>
            LycianLetterMm = 0x10290,
            /// <summary>
            /// LYCIAN LETTER NN 𐊑
            /// </summary>
            LycianLetterNn = 0x10291,
            /// <summary>
            /// LYCIAN LETTER U 𐊒
            /// </summary>
            LycianLetterU = 0x10292,
            /// <summary>
            /// LYCIAN LETTER P 𐊓
            /// </summary>
            LycianLetterP = 0x10293,
            /// <summary>
            /// LYCIAN LETTER KK 𐊔
            /// </summary>
            LycianLetterKk = 0x10294,
            /// <summary>
            /// LYCIAN LETTER R 𐊕
            /// </summary>
            LycianLetterR = 0x10295,
            /// <summary>
            /// LYCIAN LETTER S 𐊖
            /// </summary>
            LycianLetterS = 0x10296,
            /// <summary>
            /// LYCIAN LETTER T 𐊗
            /// </summary>
            LycianLetterT = 0x10297,
            /// <summary>
            /// LYCIAN LETTER TT 𐊘
            /// </summary>
            LycianLetterTt = 0x10298,
            /// <summary>
            /// LYCIAN LETTER AN 𐊙
            /// </summary>
            LycianLetterAn = 0x10299,
            /// <summary>
            /// LYCIAN LETTER EN 𐊚
            /// </summary>
            LycianLetterEn = 0x1029A,
            /// <summary>
            /// LYCIAN LETTER H 𐊛
            /// </summary>
            LycianLetterH = 0x1029B,
            /// <summary>
            /// LYCIAN LETTER X 𐊜
            /// </summary>
            LycianLetterX = 0x1029C
        }
    }
}
