// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class MeroiticHieroglyphs
    {
        public enum OtherLetter : int
        {
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER A 𐦀
            /// </summary>
            MeroiticHieroglyphicLetterA = 0x10980,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER E 𐦁
            /// </summary>
            MeroiticHieroglyphicLetterE = 0x10981,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER I 𐦂
            /// </summary>
            MeroiticHieroglyphicLetterI = 0x10982,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER O 𐦃
            /// </summary>
            MeroiticHieroglyphicLetterO = 0x10983,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER YA 𐦄
            /// </summary>
            MeroiticHieroglyphicLetterYa = 0x10984,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER WA 𐦅
            /// </summary>
            MeroiticHieroglyphicLetterWa = 0x10985,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER BA 𐦆
            /// </summary>
            MeroiticHieroglyphicLetterBa = 0x10986,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER BA-2 𐦇
            /// </summary>
            MeroiticHieroglyphicLetterBa2 = 0x10987,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER PA 𐦈
            /// </summary>
            MeroiticHieroglyphicLetterPa = 0x10988,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER MA 𐦉
            /// </summary>
            MeroiticHieroglyphicLetterMa = 0x10989,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER NA 𐦊
            /// </summary>
            MeroiticHieroglyphicLetterNa = 0x1098A,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER NA-2 𐦋
            /// </summary>
            MeroiticHieroglyphicLetterNa2 = 0x1098B,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER NE 𐦌
            /// </summary>
            MeroiticHieroglyphicLetterNe = 0x1098C,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER NE-2 𐦍
            /// </summary>
            MeroiticHieroglyphicLetterNe2 = 0x1098D,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER RA 𐦎
            /// </summary>
            MeroiticHieroglyphicLetterRa = 0x1098E,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER RA-2 𐦏
            /// </summary>
            MeroiticHieroglyphicLetterRa2 = 0x1098F,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER LA 𐦐
            /// </summary>
            MeroiticHieroglyphicLetterLa = 0x10990,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER KHA 𐦑
            /// </summary>
            MeroiticHieroglyphicLetterKha = 0x10991,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER HHA 𐦒
            /// </summary>
            MeroiticHieroglyphicLetterHha = 0x10992,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER SA 𐦓
            /// </summary>
            MeroiticHieroglyphicLetterSa = 0x10993,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER SA-2 𐦔
            /// </summary>
            MeroiticHieroglyphicLetterSa2 = 0x10994,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER SE 𐦕
            /// </summary>
            MeroiticHieroglyphicLetterSe = 0x10995,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER KA 𐦖
            /// </summary>
            MeroiticHieroglyphicLetterKa = 0x10996,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER QA 𐦗
            /// </summary>
            MeroiticHieroglyphicLetterQa = 0x10997,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER TA 𐦘
            /// </summary>
            MeroiticHieroglyphicLetterTa = 0x10998,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER TA-2 𐦙
            /// </summary>
            MeroiticHieroglyphicLetterTa2 = 0x10999,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER TE 𐦚
            /// </summary>
            MeroiticHieroglyphicLetterTe = 0x1099A,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER TE-2 𐦛
            /// </summary>
            MeroiticHieroglyphicLetterTe2 = 0x1099B,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER TO 𐦜
            /// </summary>
            MeroiticHieroglyphicLetterTo = 0x1099C,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC LETTER DA 𐦝
            /// </summary>
            MeroiticHieroglyphicLetterDa = 0x1099D,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC SYMBOL VIDJ 𐦞
            /// </summary>
            MeroiticHieroglyphicSymbolVidj = 0x1099E,
            /// <summary>
            /// MEROITIC HIEROGLYPHIC SYMBOL VIDJ-2 𐦟
            /// </summary>
            MeroiticHieroglyphicSymbolVidj2 = 0x1099F
        }
    }
}
