// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class Syriac
    {
        public enum OtherPunctuation : int
        {
            /// <summary>
            /// SYRIAC END OF PARAGRAPH ܀
            /// </summary>
            SyriacEndOfParagraph = 0x0700,
            /// <summary>
            /// SYRIAC SUPRALINEAR FULL STOP ܁
            /// </summary>
            SyriacSupralinearFullStop = 0x0701,
            /// <summary>
            /// SYRIAC SUBLINEAR FULL STOP ܂
            /// </summary>
            SyriacSublinearFullStop = 0x0702,
            /// <summary>
            /// SYRIAC SUPRALINEAR COLON ܃
            /// </summary>
            SyriacSupralinearColon = 0x0703,
            /// <summary>
            /// SYRIAC SUBLINEAR COLON ܄
            /// </summary>
            SyriacSublinearColon = 0x0704,
            /// <summary>
            /// SYRIAC HORIZONTAL COLON ܅
            /// </summary>
            SyriacHorizontalColon = 0x0705,
            /// <summary>
            /// SYRIAC COLON SKEWED LEFT ܆
            /// </summary>
            SyriacColonSkewedLeft = 0x0706,
            /// <summary>
            /// SYRIAC COLON SKEWED RIGHT ܇
            /// </summary>
            SyriacColonSkewedRight = 0x0707,
            /// <summary>
            /// SYRIAC SUPRALINEAR COLON SKEWED LEFT ܈
            /// </summary>
            SyriacSupralinearColonSkewedLeft = 0x0708,
            /// <summary>
            /// SYRIAC SUBLINEAR COLON SKEWED RIGHT ܉
            /// </summary>
            SyriacSublinearColonSkewedRight = 0x0709,
            /// <summary>
            /// SYRIAC CONTRACTION ܊
            /// </summary>
            SyriacContraction = 0x070A,
            /// <summary>
            /// SYRIAC HARKLEAN OBELUS ܋
            /// </summary>
            SyriacHarkleanObelus = 0x070B,
            /// <summary>
            /// SYRIAC HARKLEAN METOBELUS ܌
            /// </summary>
            SyriacHarkleanMetobelus = 0x070C,
            /// <summary>
            /// SYRIAC HARKLEAN ASTERISCUS ܍
            /// </summary>
            SyriacHarkleanAsteriscus = 0x070D
        }
        public enum Format : int
        {
            /// <summary>
            /// SYRIAC ABBREVIATION MARK ܏
            /// </summary>
            SyriacAbbreviationMark = 0x070F
        }
        public enum OtherLetter : int
        {
            /// <summary>
            /// SYRIAC LETTER ALAPH ܐ
            /// </summary>
            SyriacLetterAlaph = 0x0710,
            /// <summary>
            /// SYRIAC LETTER BETH ܒ
            /// </summary>
            SyriacLetterBeth = 0x0712,
            /// <summary>
            /// SYRIAC LETTER GAMAL ܓ
            /// </summary>
            SyriacLetterGamal = 0x0713,
            /// <summary>
            /// SYRIAC LETTER GAMAL GARSHUNI ܔ
            /// </summary>
            SyriacLetterGamalGarshuni = 0x0714,
            /// <summary>
            /// SYRIAC LETTER DALATH ܕ
            /// </summary>
            SyriacLetterDalath = 0x0715,
            /// <summary>
            /// SYRIAC LETTER DOTLESS DALATH RISH ܖ
            /// </summary>
            SyriacLetterDotlessDalathRish = 0x0716,
            /// <summary>
            /// SYRIAC LETTER HE ܗ
            /// </summary>
            SyriacLetterHe = 0x0717,
            /// <summary>
            /// SYRIAC LETTER WAW ܘ
            /// </summary>
            SyriacLetterWaw = 0x0718,
            /// <summary>
            /// SYRIAC LETTER ZAIN ܙ
            /// </summary>
            SyriacLetterZain = 0x0719,
            /// <summary>
            /// SYRIAC LETTER HETH ܚ
            /// </summary>
            SyriacLetterHeth = 0x071A,
            /// <summary>
            /// SYRIAC LETTER TETH ܛ
            /// </summary>
            SyriacLetterTeth = 0x071B,
            /// <summary>
            /// SYRIAC LETTER TETH GARSHUNI ܜ
            /// </summary>
            SyriacLetterTethGarshuni = 0x071C,
            /// <summary>
            /// SYRIAC LETTER YUDH ܝ
            /// </summary>
            SyriacLetterYudh = 0x071D,
            /// <summary>
            /// SYRIAC LETTER YUDH HE ܞ
            /// </summary>
            SyriacLetterYudhHe = 0x071E,
            /// <summary>
            /// SYRIAC LETTER KAPH ܟ
            /// </summary>
            SyriacLetterKaph = 0x071F,
            /// <summary>
            /// SYRIAC LETTER LAMADH ܠ
            /// </summary>
            SyriacLetterLamadh = 0x0720,
            /// <summary>
            /// SYRIAC LETTER MIM ܡ
            /// </summary>
            SyriacLetterMim = 0x0721,
            /// <summary>
            /// SYRIAC LETTER NUN ܢ
            /// </summary>
            SyriacLetterNun = 0x0722,
            /// <summary>
            /// SYRIAC LETTER SEMKATH ܣ
            /// </summary>
            SyriacLetterSemkath = 0x0723,
            /// <summary>
            /// SYRIAC LETTER FINAL SEMKATH ܤ
            /// </summary>
            SyriacLetterFinalSemkath = 0x0724,
            /// <summary>
            /// SYRIAC LETTER E ܥ
            /// </summary>
            SyriacLetterE = 0x0725,
            /// <summary>
            /// SYRIAC LETTER PE ܦ
            /// </summary>
            SyriacLetterPe = 0x0726,
            /// <summary>
            /// SYRIAC LETTER REVERSED PE ܧ
            /// </summary>
            SyriacLetterReversedPe = 0x0727,
            /// <summary>
            /// SYRIAC LETTER SADHE ܨ
            /// </summary>
            SyriacLetterSadhe = 0x0728,
            /// <summary>
            /// SYRIAC LETTER QAPH ܩ
            /// </summary>
            SyriacLetterQaph = 0x0729,
            /// <summary>
            /// SYRIAC LETTER RISH ܪ
            /// </summary>
            SyriacLetterRish = 0x072A,
            /// <summary>
            /// SYRIAC LETTER SHIN ܫ
            /// </summary>
            SyriacLetterShin = 0x072B,
            /// <summary>
            /// SYRIAC LETTER TAW ܬ
            /// </summary>
            SyriacLetterTaw = 0x072C,
            /// <summary>
            /// SYRIAC LETTER PERSIAN BHETH ܭ
            /// </summary>
            SyriacLetterPersianBheth = 0x072D,
            /// <summary>
            /// SYRIAC LETTER PERSIAN GHAMAL ܮ
            /// </summary>
            SyriacLetterPersianGhamal = 0x072E,
            /// <summary>
            /// SYRIAC LETTER PERSIAN DHALATH ܯ
            /// </summary>
            SyriacLetterPersianDhalath = 0x072F,
            /// <summary>
            /// SYRIAC LETTER SOGDIAN ZHAIN ݍ
            /// </summary>
            SyriacLetterSogdianZhain = 0x074D,
            /// <summary>
            /// SYRIAC LETTER SOGDIAN KHAPH ݎ
            /// </summary>
            SyriacLetterSogdianKhaph = 0x074E,
            /// <summary>
            /// SYRIAC LETTER SOGDIAN FE ݏ
            /// </summary>
            SyriacLetterSogdianFe = 0x074F
        }
        public enum NonSpacingMark : int
        {
            /// <summary>
            /// SYRIAC LETTER SUPERSCRIPT ALAPH ܑ
            /// </summary>
            SyriacLetterSuperscriptAlaph = 0x0711,
            /// <summary>
            /// SYRIAC PTHAHA ABOVE ܰ
            /// </summary>
            SyriacPthahaAbove = 0x0730,
            /// <summary>
            /// SYRIAC PTHAHA BELOW ܱ
            /// </summary>
            SyriacPthahaBelow = 0x0731,
            /// <summary>
            /// SYRIAC PTHAHA DOTTED ܲ
            /// </summary>
            SyriacPthahaDotted = 0x0732,
            /// <summary>
            /// SYRIAC ZQAPHA ABOVE ܳ
            /// </summary>
            SyriacZqaphaAbove = 0x0733,
            /// <summary>
            /// SYRIAC ZQAPHA BELOW ܴ
            /// </summary>
            SyriacZqaphaBelow = 0x0734,
            /// <summary>
            /// SYRIAC ZQAPHA DOTTED ܵ
            /// </summary>
            SyriacZqaphaDotted = 0x0735,
            /// <summary>
            /// SYRIAC RBASA ABOVE ܶ
            /// </summary>
            SyriacRbasaAbove = 0x0736,
            /// <summary>
            /// SYRIAC RBASA BELOW ܷ
            /// </summary>
            SyriacRbasaBelow = 0x0737,
            /// <summary>
            /// SYRIAC DOTTED ZLAMA HORIZONTAL ܸ
            /// </summary>
            SyriacDottedZlamaHorizontal = 0x0738,
            /// <summary>
            /// SYRIAC DOTTED ZLAMA ANGULAR ܹ
            /// </summary>
            SyriacDottedZlamaAngular = 0x0739,
            /// <summary>
            /// SYRIAC HBASA ABOVE ܺ
            /// </summary>
            SyriacHbasaAbove = 0x073A,
            /// <summary>
            /// SYRIAC HBASA BELOW ܻ
            /// </summary>
            SyriacHbasaBelow = 0x073B,
            /// <summary>
            /// SYRIAC HBASA-ESASA DOTTED ܼ
            /// </summary>
            SyriacHbasaEsasaDotted = 0x073C,
            /// <summary>
            /// SYRIAC ESASA ABOVE ܽ
            /// </summary>
            SyriacEsasaAbove = 0x073D,
            /// <summary>
            /// SYRIAC ESASA BELOW ܾ
            /// </summary>
            SyriacEsasaBelow = 0x073E,
            /// <summary>
            /// SYRIAC RWAHA ܿ
            /// </summary>
            SyriacRwaha = 0x073F,
            /// <summary>
            /// SYRIAC FEMININE DOT ݀
            /// </summary>
            SyriacFeminineDot = 0x0740,
            /// <summary>
            /// SYRIAC QUSHSHAYA ݁
            /// </summary>
            SyriacQushshaya = 0x0741,
            /// <summary>
            /// SYRIAC RUKKAKHA ݂
            /// </summary>
            SyriacRukkakha = 0x0742,
            /// <summary>
            /// SYRIAC TWO VERTICAL DOTS ABOVE ݃
            /// </summary>
            SyriacTwoVerticalDotsAbove = 0x0743,
            /// <summary>
            /// SYRIAC TWO VERTICAL DOTS BELOW ݄
            /// </summary>
            SyriacTwoVerticalDotsBelow = 0x0744,
            /// <summary>
            /// SYRIAC THREE DOTS ABOVE ݅
            /// </summary>
            SyriacThreeDotsAbove = 0x0745,
            /// <summary>
            /// SYRIAC THREE DOTS BELOW ݆
            /// </summary>
            SyriacThreeDotsBelow = 0x0746,
            /// <summary>
            /// SYRIAC OBLIQUE LINE ABOVE ݇
            /// </summary>
            SyriacObliqueLineAbove = 0x0747,
            /// <summary>
            /// SYRIAC OBLIQUE LINE BELOW ݈
            /// </summary>
            SyriacObliqueLineBelow = 0x0748,
            /// <summary>
            /// SYRIAC MUSIC ݉
            /// </summary>
            SyriacMusic = 0x0749,
            /// <summary>
            /// SYRIAC BARREKH ݊
            /// </summary>
            SyriacBarrekh = 0x074A
        }
    }
}
