// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class EthiopicSupplement
    {
        public enum OtherLetter : int
        {
            /// <summary>
            /// ETHIOPIC SYLLABLE SEBATBEIT MWA ᎀ
            /// </summary>
            EthiopicSyllableSebatbeitMwa = 0x1380,
            /// <summary>
            /// ETHIOPIC SYLLABLE MWI ᎁ
            /// </summary>
            EthiopicSyllableMwi = 0x1381,
            /// <summary>
            /// ETHIOPIC SYLLABLE MWEE ᎂ
            /// </summary>
            EthiopicSyllableMwee = 0x1382,
            /// <summary>
            /// ETHIOPIC SYLLABLE MWE ᎃ
            /// </summary>
            EthiopicSyllableMwe = 0x1383,
            /// <summary>
            /// ETHIOPIC SYLLABLE SEBATBEIT BWA ᎄ
            /// </summary>
            EthiopicSyllableSebatbeitBwa = 0x1384,
            /// <summary>
            /// ETHIOPIC SYLLABLE BWI ᎅ
            /// </summary>
            EthiopicSyllableBwi = 0x1385,
            /// <summary>
            /// ETHIOPIC SYLLABLE BWEE ᎆ
            /// </summary>
            EthiopicSyllableBwee = 0x1386,
            /// <summary>
            /// ETHIOPIC SYLLABLE BWE ᎇ
            /// </summary>
            EthiopicSyllableBwe = 0x1387,
            /// <summary>
            /// ETHIOPIC SYLLABLE SEBATBEIT FWA ᎈ
            /// </summary>
            EthiopicSyllableSebatbeitFwa = 0x1388,
            /// <summary>
            /// ETHIOPIC SYLLABLE FWI ᎉ
            /// </summary>
            EthiopicSyllableFwi = 0x1389,
            /// <summary>
            /// ETHIOPIC SYLLABLE FWEE ᎊ
            /// </summary>
            EthiopicSyllableFwee = 0x138A,
            /// <summary>
            /// ETHIOPIC SYLLABLE FWE ᎋ
            /// </summary>
            EthiopicSyllableFwe = 0x138B,
            /// <summary>
            /// ETHIOPIC SYLLABLE SEBATBEIT PWA ᎌ
            /// </summary>
            EthiopicSyllableSebatbeitPwa = 0x138C,
            /// <summary>
            /// ETHIOPIC SYLLABLE PWI ᎍ
            /// </summary>
            EthiopicSyllablePwi = 0x138D,
            /// <summary>
            /// ETHIOPIC SYLLABLE PWEE ᎎ
            /// </summary>
            EthiopicSyllablePwee = 0x138E,
            /// <summary>
            /// ETHIOPIC SYLLABLE PWE ᎏ
            /// </summary>
            EthiopicSyllablePwe = 0x138F
        }
        public enum OtherSymbol : int
        {
            /// <summary>
            /// ETHIOPIC TONAL MARK YIZET ᎐
            /// </summary>
            EthiopicTonalMarkYizet = 0x1390,
            /// <summary>
            /// ETHIOPIC TONAL MARK DERET ᎑
            /// </summary>
            EthiopicTonalMarkDeret = 0x1391,
            /// <summary>
            /// ETHIOPIC TONAL MARK RIKRIK ᎒
            /// </summary>
            EthiopicTonalMarkRikrik = 0x1392,
            /// <summary>
            /// ETHIOPIC TONAL MARK SHORT RIKRIK ᎓
            /// </summary>
            EthiopicTonalMarkShortRikrik = 0x1393,
            /// <summary>
            /// ETHIOPIC TONAL MARK DIFAT ᎔
            /// </summary>
            EthiopicTonalMarkDifat = 0x1394,
            /// <summary>
            /// ETHIOPIC TONAL MARK KENAT ᎕
            /// </summary>
            EthiopicTonalMarkKenat = 0x1395,
            /// <summary>
            /// ETHIOPIC TONAL MARK CHIRET ᎖
            /// </summary>
            EthiopicTonalMarkChiret = 0x1396,
            /// <summary>
            /// ETHIOPIC TONAL MARK HIDET ᎗
            /// </summary>
            EthiopicTonalMarkHidet = 0x1397,
            /// <summary>
            /// ETHIOPIC TONAL MARK DERET-HIDET ᎘
            /// </summary>
            EthiopicTonalMarkDeretHidet = 0x1398,
            /// <summary>
            /// ETHIOPIC TONAL MARK KURT ᎙
            /// </summary>
            EthiopicTonalMarkKurt = 0x1399
        }
    }
}
