// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class Khmer
    {
        public enum OtherLetter : int
        {
            /// <summary>
            /// KHMER LETTER KA ក
            /// </summary>
            KhmerLetterKa = 0x1780,
            /// <summary>
            /// KHMER LETTER KHA ខ
            /// </summary>
            KhmerLetterKha = 0x1781,
            /// <summary>
            /// KHMER LETTER KO គ
            /// </summary>
            KhmerLetterKo = 0x1782,
            /// <summary>
            /// KHMER LETTER KHO ឃ
            /// </summary>
            KhmerLetterKho = 0x1783,
            /// <summary>
            /// KHMER LETTER NGO ង
            /// </summary>
            KhmerLetterNgo = 0x1784,
            /// <summary>
            /// KHMER LETTER CA ច
            /// </summary>
            KhmerLetterCa = 0x1785,
            /// <summary>
            /// KHMER LETTER CHA ឆ
            /// </summary>
            KhmerLetterCha = 0x1786,
            /// <summary>
            /// KHMER LETTER CO ជ
            /// </summary>
            KhmerLetterCo = 0x1787,
            /// <summary>
            /// KHMER LETTER CHO ឈ
            /// </summary>
            KhmerLetterCho = 0x1788,
            /// <summary>
            /// KHMER LETTER NYO ញ
            /// </summary>
            KhmerLetterNyo = 0x1789,
            /// <summary>
            /// KHMER LETTER DA ដ
            /// </summary>
            KhmerLetterDa = 0x178A,
            /// <summary>
            /// KHMER LETTER TTHA ឋ
            /// </summary>
            KhmerLetterTtha = 0x178B,
            /// <summary>
            /// KHMER LETTER DO ឌ
            /// </summary>
            KhmerLetterDo = 0x178C,
            /// <summary>
            /// KHMER LETTER TTHO ឍ
            /// </summary>
            KhmerLetterTtho = 0x178D,
            /// <summary>
            /// KHMER LETTER NNO ណ
            /// </summary>
            KhmerLetterNno = 0x178E,
            /// <summary>
            /// KHMER LETTER TA ត
            /// </summary>
            KhmerLetterTa = 0x178F,
            /// <summary>
            /// KHMER LETTER THA ថ
            /// </summary>
            KhmerLetterTha = 0x1790,
            /// <summary>
            /// KHMER LETTER TO ទ
            /// </summary>
            KhmerLetterTo = 0x1791,
            /// <summary>
            /// KHMER LETTER THO ធ
            /// </summary>
            KhmerLetterTho = 0x1792,
            /// <summary>
            /// KHMER LETTER NO ន
            /// </summary>
            KhmerLetterNo = 0x1793,
            /// <summary>
            /// KHMER LETTER BA ប
            /// </summary>
            KhmerLetterBa = 0x1794,
            /// <summary>
            /// KHMER LETTER PHA ផ
            /// </summary>
            KhmerLetterPha = 0x1795,
            /// <summary>
            /// KHMER LETTER PO ព
            /// </summary>
            KhmerLetterPo = 0x1796,
            /// <summary>
            /// KHMER LETTER PHO ភ
            /// </summary>
            KhmerLetterPho = 0x1797,
            /// <summary>
            /// KHMER LETTER MO ម
            /// </summary>
            KhmerLetterMo = 0x1798,
            /// <summary>
            /// KHMER LETTER YO យ
            /// </summary>
            KhmerLetterYo = 0x1799,
            /// <summary>
            /// KHMER LETTER RO រ
            /// </summary>
            KhmerLetterRo = 0x179A,
            /// <summary>
            /// KHMER LETTER LO ល
            /// </summary>
            KhmerLetterLo = 0x179B,
            /// <summary>
            /// KHMER LETTER VO វ
            /// </summary>
            KhmerLetterVo = 0x179C,
            /// <summary>
            /// KHMER LETTER SHA ឝ
            /// </summary>
            KhmerLetterSha = 0x179D,
            /// <summary>
            /// KHMER LETTER SSO ឞ
            /// </summary>
            KhmerLetterSso = 0x179E,
            /// <summary>
            /// KHMER LETTER SA ស
            /// </summary>
            KhmerLetterSa = 0x179F,
            /// <summary>
            /// KHMER LETTER HA ហ
            /// </summary>
            KhmerLetterHa = 0x17A0,
            /// <summary>
            /// KHMER LETTER LA ឡ
            /// </summary>
            KhmerLetterLa = 0x17A1,
            /// <summary>
            /// KHMER LETTER QA អ
            /// </summary>
            KhmerLetterQa = 0x17A2,
            /// <summary>
            /// KHMER INDEPENDENT VOWEL QAQ ឣ
            /// </summary>
            KhmerIndependentVowelQaq = 0x17A3,
            /// <summary>
            /// KHMER INDEPENDENT VOWEL QAA ឤ
            /// </summary>
            KhmerIndependentVowelQaa = 0x17A4,
            /// <summary>
            /// KHMER INDEPENDENT VOWEL QI ឥ
            /// </summary>
            KhmerIndependentVowelQi = 0x17A5,
            /// <summary>
            /// KHMER INDEPENDENT VOWEL QII ឦ
            /// </summary>
            KhmerIndependentVowelQii = 0x17A6,
            /// <summary>
            /// KHMER INDEPENDENT VOWEL QU ឧ
            /// </summary>
            KhmerIndependentVowelQu = 0x17A7,
            /// <summary>
            /// KHMER INDEPENDENT VOWEL QUK ឨ
            /// </summary>
            KhmerIndependentVowelQuk = 0x17A8,
            /// <summary>
            /// KHMER INDEPENDENT VOWEL QUU ឩ
            /// </summary>
            KhmerIndependentVowelQuu = 0x17A9,
            /// <summary>
            /// KHMER INDEPENDENT VOWEL QUUV ឪ
            /// </summary>
            KhmerIndependentVowelQuuv = 0x17AA,
            /// <summary>
            /// KHMER INDEPENDENT VOWEL RY ឫ
            /// </summary>
            KhmerIndependentVowelRy = 0x17AB,
            /// <summary>
            /// KHMER INDEPENDENT VOWEL RYY ឬ
            /// </summary>
            KhmerIndependentVowelRyy = 0x17AC,
            /// <summary>
            /// KHMER INDEPENDENT VOWEL LY ឭ
            /// </summary>
            KhmerIndependentVowelLy = 0x17AD,
            /// <summary>
            /// KHMER INDEPENDENT VOWEL LYY ឮ
            /// </summary>
            KhmerIndependentVowelLyy = 0x17AE,
            /// <summary>
            /// KHMER INDEPENDENT VOWEL QE ឯ
            /// </summary>
            KhmerIndependentVowelQe = 0x17AF,
            /// <summary>
            /// KHMER INDEPENDENT VOWEL QAI ឰ
            /// </summary>
            KhmerIndependentVowelQai = 0x17B0,
            /// <summary>
            /// KHMER INDEPENDENT VOWEL QOO TYPE ONE ឱ
            /// </summary>
            KhmerIndependentVowelQooTypeOne = 0x17B1,
            /// <summary>
            /// KHMER INDEPENDENT VOWEL QOO TYPE TWO ឲ
            /// </summary>
            KhmerIndependentVowelQooTypeTwo = 0x17B2,
            /// <summary>
            /// KHMER INDEPENDENT VOWEL QAU ឳ
            /// </summary>
            KhmerIndependentVowelQau = 0x17B3,
            /// <summary>
            /// KHMER SIGN AVAKRAHASANYA ៜ
            /// </summary>
            KhmerSignAvakrahasanya = 0x17DC
        }
        public enum NonSpacingMark : int
        {
            /// <summary>
            /// KHMER VOWEL INHERENT AQ ឴
            /// </summary>
            KhmerVowelInherentAq = 0x17B4,
            /// <summary>
            /// KHMER VOWEL INHERENT AA ឵
            /// </summary>
            KhmerVowelInherentAa = 0x17B5,
            /// <summary>
            /// KHMER VOWEL SIGN I ិ
            /// </summary>
            KhmerVowelSignI = 0x17B7,
            /// <summary>
            /// KHMER VOWEL SIGN II ី
            /// </summary>
            KhmerVowelSignIi = 0x17B8,
            /// <summary>
            /// KHMER VOWEL SIGN Y ឹ
            /// </summary>
            KhmerVowelSignY = 0x17B9,
            /// <summary>
            /// KHMER VOWEL SIGN YY ឺ
            /// </summary>
            KhmerVowelSignYy = 0x17BA,
            /// <summary>
            /// KHMER VOWEL SIGN U ុ
            /// </summary>
            KhmerVowelSignU = 0x17BB,
            /// <summary>
            /// KHMER VOWEL SIGN UU ូ
            /// </summary>
            KhmerVowelSignUu = 0x17BC,
            /// <summary>
            /// KHMER VOWEL SIGN UA ួ
            /// </summary>
            KhmerVowelSignUa = 0x17BD,
            /// <summary>
            /// KHMER SIGN NIKAHIT ំ
            /// </summary>
            KhmerSignNikahit = 0x17C6,
            /// <summary>
            /// KHMER SIGN MUUSIKATOAN ៉
            /// </summary>
            KhmerSignMuusikatoan = 0x17C9,
            /// <summary>
            /// KHMER SIGN TRIISAP ៊
            /// </summary>
            KhmerSignTriisap = 0x17CA,
            /// <summary>
            /// KHMER SIGN BANTOC ់
            /// </summary>
            KhmerSignBantoc = 0x17CB,
            /// <summary>
            /// KHMER SIGN ROBAT ៌
            /// </summary>
            KhmerSignRobat = 0x17CC,
            /// <summary>
            /// KHMER SIGN TOANDAKHIAT ៍
            /// </summary>
            KhmerSignToandakhiat = 0x17CD,
            /// <summary>
            /// KHMER SIGN KAKABAT ៎
            /// </summary>
            KhmerSignKakabat = 0x17CE,
            /// <summary>
            /// KHMER SIGN AHSDA ៏
            /// </summary>
            KhmerSignAhsda = 0x17CF,
            /// <summary>
            /// KHMER SIGN SAMYOK SANNYA ័
            /// </summary>
            KhmerSignSamyokSannya = 0x17D0,
            /// <summary>
            /// KHMER SIGN VIRIAM ៑
            /// </summary>
            KhmerSignViriam = 0x17D1,
            /// <summary>
            /// KHMER SIGN COENG ្
            /// </summary>
            KhmerSignCoeng = 0x17D2,
            /// <summary>
            /// KHMER SIGN BATHAMASAT ៓
            /// </summary>
            KhmerSignBathamasat = 0x17D3,
            /// <summary>
            /// KHMER SIGN ATTHACAN ៝
            /// </summary>
            KhmerSignAtthacan = 0x17DD
        }
        public enum SpacingCombiningMark : int
        {
            /// <summary>
            /// KHMER VOWEL SIGN AA ា
            /// </summary>
            KhmerVowelSignAa = 0x17B6,
            /// <summary>
            /// KHMER VOWEL SIGN OE ើ
            /// </summary>
            KhmerVowelSignOe = 0x17BE,
            /// <summary>
            /// KHMER VOWEL SIGN YA ឿ
            /// </summary>
            KhmerVowelSignYa = 0x17BF,
            /// <summary>
            /// KHMER VOWEL SIGN IE ៀ
            /// </summary>
            KhmerVowelSignIe = 0x17C0,
            /// <summary>
            /// KHMER VOWEL SIGN E េ
            /// </summary>
            KhmerVowelSignE = 0x17C1,
            /// <summary>
            /// KHMER VOWEL SIGN AE ែ
            /// </summary>
            KhmerVowelSignAe = 0x17C2,
            /// <summary>
            /// KHMER VOWEL SIGN AI ៃ
            /// </summary>
            KhmerVowelSignAi = 0x17C3,
            /// <summary>
            /// KHMER VOWEL SIGN OO ោ
            /// </summary>
            KhmerVowelSignOo = 0x17C4,
            /// <summary>
            /// KHMER VOWEL SIGN AU ៅ
            /// </summary>
            KhmerVowelSignAu = 0x17C5,
            /// <summary>
            /// KHMER SIGN REAHMUK ះ
            /// </summary>
            KhmerSignReahmuk = 0x17C7,
            /// <summary>
            /// KHMER SIGN YUUKALEAPINTU ៈ
            /// </summary>
            KhmerSignYuukaleapintu = 0x17C8
        }
        public enum OtherPunctuation : int
        {
            /// <summary>
            /// KHMER SIGN KHAN ។
            /// </summary>
            KhmerSignKhan = 0x17D4,
            /// <summary>
            /// KHMER SIGN BARIYOOSAN ៕
            /// </summary>
            KhmerSignBariyoosan = 0x17D5,
            /// <summary>
            /// KHMER SIGN CAMNUC PII KUUH ៖
            /// </summary>
            KhmerSignCamnucPiiKuuh = 0x17D6,
            /// <summary>
            /// KHMER SIGN BEYYAL ៘
            /// </summary>
            KhmerSignBeyyal = 0x17D8,
            /// <summary>
            /// KHMER SIGN PHNAEK MUAN ៙
            /// </summary>
            KhmerSignPhnaekMuan = 0x17D9,
            /// <summary>
            /// KHMER SIGN KOOMUUT ៚
            /// </summary>
            KhmerSignKoomuut = 0x17DA
        }
        public enum ModifierLetter : int
        {
            /// <summary>
            /// KHMER SIGN LEK TOO ៗ
            /// </summary>
            KhmerSignLekToo = 0x17D7
        }
        public enum CurrencySymbol : int
        {
            /// <summary>
            /// KHMER CURRENCY SYMBOL RIEL ៛
            /// </summary>
            KhmerCurrencySymbolRiel = 0x17DB
        }
        public enum DecimalDigitNumber : int
        {
            /// <summary>
            /// KHMER DIGIT ZERO ០
            /// </summary>
            KhmerDigitZero = 0x17E0,
            /// <summary>
            /// KHMER DIGIT ONE ១
            /// </summary>
            KhmerDigitOne = 0x17E1,
            /// <summary>
            /// KHMER DIGIT TWO ២
            /// </summary>
            KhmerDigitTwo = 0x17E2,
            /// <summary>
            /// KHMER DIGIT THREE ៣
            /// </summary>
            KhmerDigitThree = 0x17E3,
            /// <summary>
            /// KHMER DIGIT FOUR ៤
            /// </summary>
            KhmerDigitFour = 0x17E4,
            /// <summary>
            /// KHMER DIGIT FIVE ៥
            /// </summary>
            KhmerDigitFive = 0x17E5,
            /// <summary>
            /// KHMER DIGIT SIX ៦
            /// </summary>
            KhmerDigitSix = 0x17E6,
            /// <summary>
            /// KHMER DIGIT SEVEN ៧
            /// </summary>
            KhmerDigitSeven = 0x17E7,
            /// <summary>
            /// KHMER DIGIT EIGHT ៨
            /// </summary>
            KhmerDigitEight = 0x17E8,
            /// <summary>
            /// KHMER DIGIT NINE ៩
            /// </summary>
            KhmerDigitNine = 0x17E9
        }
        public enum OtherNumber : int
        {
            /// <summary>
            /// KHMER SYMBOL LEK ATTAK SON ៰
            /// </summary>
            KhmerSymbolLekAttakSon = 0x17F0,
            /// <summary>
            /// KHMER SYMBOL LEK ATTAK MUOY ៱
            /// </summary>
            KhmerSymbolLekAttakMuoy = 0x17F1,
            /// <summary>
            /// KHMER SYMBOL LEK ATTAK PII ៲
            /// </summary>
            KhmerSymbolLekAttakPii = 0x17F2,
            /// <summary>
            /// KHMER SYMBOL LEK ATTAK BEI ៳
            /// </summary>
            KhmerSymbolLekAttakBei = 0x17F3,
            /// <summary>
            /// KHMER SYMBOL LEK ATTAK BUON ៴
            /// </summary>
            KhmerSymbolLekAttakBuon = 0x17F4,
            /// <summary>
            /// KHMER SYMBOL LEK ATTAK PRAM ៵
            /// </summary>
            KhmerSymbolLekAttakPram = 0x17F5,
            /// <summary>
            /// KHMER SYMBOL LEK ATTAK PRAM-MUOY ៶
            /// </summary>
            KhmerSymbolLekAttakPramMuoy = 0x17F6,
            /// <summary>
            /// KHMER SYMBOL LEK ATTAK PRAM-PII ៷
            /// </summary>
            KhmerSymbolLekAttakPramPii = 0x17F7,
            /// <summary>
            /// KHMER SYMBOL LEK ATTAK PRAM-BEI ៸
            /// </summary>
            KhmerSymbolLekAttakPramBei = 0x17F8,
            /// <summary>
            /// KHMER SYMBOL LEK ATTAK PRAM-BUON ៹
            /// </summary>
            KhmerSymbolLekAttakPramBuon = 0x17F9
        }
    }
}
