// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    partial struct Char32
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Cham.OtherLetter value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Cham.OtherLetter(Char32 c)
        {
            return (Cham.OtherLetter)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Cham.NonSpacingMark value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Cham.NonSpacingMark(Char32 c)
        {
            return (Cham.NonSpacingMark)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Cham.SpacingCombiningMark value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Cham.SpacingCombiningMark(Char32 c)
        {
            return (Cham.SpacingCombiningMark)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Cham.DecimalDigitNumber value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Cham.DecimalDigitNumber(Char32 c)
        {
            return (Cham.DecimalDigitNumber)c.Value;
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Char32(Cham.OtherPunctuation value)
        {
            return new Char32((UInt32)value);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Cham.OtherPunctuation(Char32 c)
        {
            return (Cham.OtherPunctuation)c.Value;
        }
    }
}
