// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class HalfwidthandFullwidthForms
    {
        public enum OtherPunctuation : int
        {
            /// <summary>
            /// FULLWIDTH EXCLAMATION MARK ！
            /// </summary>
            FullwidthExclamationMark = 0xFF01,
            /// <summary>
            /// FULLWIDTH QUOTATION MARK ＂
            /// </summary>
            FullwidthQuotationMark = 0xFF02,
            /// <summary>
            /// FULLWIDTH NUMBER SIGN ＃
            /// </summary>
            FullwidthNumberSign = 0xFF03,
            /// <summary>
            /// FULLWIDTH PERCENT SIGN ％
            /// </summary>
            FullwidthPercentSign = 0xFF05,
            /// <summary>
            /// FULLWIDTH AMPERSAND ＆
            /// </summary>
            FullwidthAmpersand = 0xFF06,
            /// <summary>
            /// FULLWIDTH APOSTROPHE ＇
            /// </summary>
            FullwidthApostrophe = 0xFF07,
            /// <summary>
            /// FULLWIDTH ASTERISK ＊
            /// </summary>
            FullwidthAsterisk = 0xFF0A,
            /// <summary>
            /// FULLWIDTH COMMA ，
            /// </summary>
            FullwidthComma = 0xFF0C,
            /// <summary>
            /// FULLWIDTH FULL STOP ．
            /// </summary>
            FullwidthFullStop = 0xFF0E,
            /// <summary>
            /// FULLWIDTH SOLIDUS ／
            /// </summary>
            FullwidthSolidus = 0xFF0F,
            /// <summary>
            /// FULLWIDTH COLON ：
            /// </summary>
            FullwidthColon = 0xFF1A,
            /// <summary>
            /// FULLWIDTH SEMICOLON ；
            /// </summary>
            FullwidthSemicolon = 0xFF1B,
            /// <summary>
            /// FULLWIDTH QUESTION MARK ？
            /// </summary>
            FullwidthQuestionMark = 0xFF1F,
            /// <summary>
            /// FULLWIDTH COMMERCIAL AT ＠
            /// </summary>
            FullwidthCommercialAt = 0xFF20,
            /// <summary>
            /// FULLWIDTH REVERSE SOLIDUS ＼
            /// </summary>
            FullwidthReverseSolidus = 0xFF3C,
            /// <summary>
            /// HALFWIDTH IDEOGRAPHIC FULL STOP ｡
            /// </summary>
            HalfwidthIdeographicFullStop = 0xFF61,
            /// <summary>
            /// HALFWIDTH IDEOGRAPHIC COMMA ､
            /// </summary>
            HalfwidthIdeographicComma = 0xFF64,
            /// <summary>
            /// HALFWIDTH KATAKANA MIDDLE DOT ･
            /// </summary>
            HalfwidthKatakanaMiddleDot = 0xFF65
        }
        public enum CurrencySymbol : int
        {
            /// <summary>
            /// FULLWIDTH DOLLAR SIGN ＄
            /// </summary>
            FullwidthDollarSign = 0xFF04,
            /// <summary>
            /// FULLWIDTH CENT SIGN ￠
            /// </summary>
            FullwidthCentSign = 0xFFE0,
            /// <summary>
            /// FULLWIDTH POUND SIGN ￡
            /// </summary>
            FullwidthPoundSign = 0xFFE1,
            /// <summary>
            /// FULLWIDTH YEN SIGN ￥
            /// </summary>
            FullwidthYenSign = 0xFFE5,
            /// <summary>
            /// FULLWIDTH WON SIGN ￦
            /// </summary>
            FullwidthWonSign = 0xFFE6
        }
        public enum OpenPunctuation : int
        {
            /// <summary>
            /// FULLWIDTH LEFT PARENTHESIS （
            /// </summary>
            FullwidthLeftParenthesis = 0xFF08,
            /// <summary>
            /// FULLWIDTH LEFT SQUARE BRACKET ［
            /// </summary>
            FullwidthLeftSquareBracket = 0xFF3B,
            /// <summary>
            /// FULLWIDTH LEFT CURLY BRACKET ｛
            /// </summary>
            FullwidthLeftCurlyBracket = 0xFF5B,
            /// <summary>
            /// FULLWIDTH LEFT WHITE PARENTHESIS ｟
            /// </summary>
            FullwidthLeftWhiteParenthesis = 0xFF5F,
            /// <summary>
            /// HALFWIDTH LEFT CORNER BRACKET ｢
            /// </summary>
            HalfwidthLeftCornerBracket = 0xFF62
        }
        public enum ClosePunctuation : int
        {
            /// <summary>
            /// FULLWIDTH RIGHT PARENTHESIS ）
            /// </summary>
            FullwidthRightParenthesis = 0xFF09,
            /// <summary>
            /// FULLWIDTH RIGHT SQUARE BRACKET ］
            /// </summary>
            FullwidthRightSquareBracket = 0xFF3D,
            /// <summary>
            /// FULLWIDTH RIGHT CURLY BRACKET ｝
            /// </summary>
            FullwidthRightCurlyBracket = 0xFF5D,
            /// <summary>
            /// FULLWIDTH RIGHT WHITE PARENTHESIS ｠
            /// </summary>
            FullwidthRightWhiteParenthesis = 0xFF60,
            /// <summary>
            /// HALFWIDTH RIGHT CORNER BRACKET ｣
            /// </summary>
            HalfwidthRightCornerBracket = 0xFF63
        }
        public enum MathSymbol : int
        {
            /// <summary>
            /// FULLWIDTH PLUS SIGN ＋
            /// </summary>
            FullwidthPlusSign = 0xFF0B,
            /// <summary>
            /// FULLWIDTH LESS-THAN SIGN ＜
            /// </summary>
            FullwidthLessThanSign = 0xFF1C,
            /// <summary>
            /// FULLWIDTH EQUALS SIGN ＝
            /// </summary>
            FullwidthEqualsSign = 0xFF1D,
            /// <summary>
            /// FULLWIDTH GREATER-THAN SIGN ＞
            /// </summary>
            FullwidthGreaterThanSign = 0xFF1E,
            /// <summary>
            /// FULLWIDTH VERTICAL LINE ｜
            /// </summary>
            FullwidthVerticalLine = 0xFF5C,
            /// <summary>
            /// FULLWIDTH TILDE ～
            /// </summary>
            FullwidthTilde = 0xFF5E,
            /// <summary>
            /// FULLWIDTH NOT SIGN ￢
            /// </summary>
            FullwidthNotSign = 0xFFE2,
            /// <summary>
            /// HALFWIDTH LEFTWARDS ARROW ￩
            /// </summary>
            HalfwidthLeftwardsArrow = 0xFFE9,
            /// <summary>
            /// HALFWIDTH UPWARDS ARROW ￪
            /// </summary>
            HalfwidthUpwardsArrow = 0xFFEA,
            /// <summary>
            /// HALFWIDTH RIGHTWARDS ARROW ￫
            /// </summary>
            HalfwidthRightwardsArrow = 0xFFEB,
            /// <summary>
            /// HALFWIDTH DOWNWARDS ARROW ￬
            /// </summary>
            HalfwidthDownwardsArrow = 0xFFEC
        }
        public enum DashPunctuation : int
        {
            /// <summary>
            /// FULLWIDTH HYPHEN-MINUS －
            /// </summary>
            FullwidthHyphenMinus = 0xFF0D
        }
        public enum DecimalDigitNumber : int
        {
            /// <summary>
            /// FULLWIDTH DIGIT ZERO ０
            /// </summary>
            FullwidthDigitZero = 0xFF10,
            /// <summary>
            /// FULLWIDTH DIGIT ONE １
            /// </summary>
            FullwidthDigitOne = 0xFF11,
            /// <summary>
            /// FULLWIDTH DIGIT TWO ２
            /// </summary>
            FullwidthDigitTwo = 0xFF12,
            /// <summary>
            /// FULLWIDTH DIGIT THREE ３
            /// </summary>
            FullwidthDigitThree = 0xFF13,
            /// <summary>
            /// FULLWIDTH DIGIT FOUR ４
            /// </summary>
            FullwidthDigitFour = 0xFF14,
            /// <summary>
            /// FULLWIDTH DIGIT FIVE ５
            /// </summary>
            FullwidthDigitFive = 0xFF15,
            /// <summary>
            /// FULLWIDTH DIGIT SIX ６
            /// </summary>
            FullwidthDigitSix = 0xFF16,
            /// <summary>
            /// FULLWIDTH DIGIT SEVEN ７
            /// </summary>
            FullwidthDigitSeven = 0xFF17,
            /// <summary>
            /// FULLWIDTH DIGIT EIGHT ８
            /// </summary>
            FullwidthDigitEight = 0xFF18,
            /// <summary>
            /// FULLWIDTH DIGIT NINE ９
            /// </summary>
            FullwidthDigitNine = 0xFF19
        }
        public enum UppercaseLetter : int
        {
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER A Ａ
            /// </summary>
            FullwidthLatinCapitalLetterA = 0xFF21,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER B Ｂ
            /// </summary>
            FullwidthLatinCapitalLetterB = 0xFF22,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER C Ｃ
            /// </summary>
            FullwidthLatinCapitalLetterC = 0xFF23,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER D Ｄ
            /// </summary>
            FullwidthLatinCapitalLetterD = 0xFF24,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER E Ｅ
            /// </summary>
            FullwidthLatinCapitalLetterE = 0xFF25,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER F Ｆ
            /// </summary>
            FullwidthLatinCapitalLetterF = 0xFF26,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER G Ｇ
            /// </summary>
            FullwidthLatinCapitalLetterG = 0xFF27,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER H Ｈ
            /// </summary>
            FullwidthLatinCapitalLetterH = 0xFF28,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER I Ｉ
            /// </summary>
            FullwidthLatinCapitalLetterI = 0xFF29,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER J Ｊ
            /// </summary>
            FullwidthLatinCapitalLetterJ = 0xFF2A,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER K Ｋ
            /// </summary>
            FullwidthLatinCapitalLetterK = 0xFF2B,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER L Ｌ
            /// </summary>
            FullwidthLatinCapitalLetterL = 0xFF2C,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER M Ｍ
            /// </summary>
            FullwidthLatinCapitalLetterM = 0xFF2D,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER N Ｎ
            /// </summary>
            FullwidthLatinCapitalLetterN = 0xFF2E,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER O Ｏ
            /// </summary>
            FullwidthLatinCapitalLetterO = 0xFF2F,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER P Ｐ
            /// </summary>
            FullwidthLatinCapitalLetterP = 0xFF30,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER Q Ｑ
            /// </summary>
            FullwidthLatinCapitalLetterQ = 0xFF31,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER R Ｒ
            /// </summary>
            FullwidthLatinCapitalLetterR = 0xFF32,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER S Ｓ
            /// </summary>
            FullwidthLatinCapitalLetterS = 0xFF33,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER T Ｔ
            /// </summary>
            FullwidthLatinCapitalLetterT = 0xFF34,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER U Ｕ
            /// </summary>
            FullwidthLatinCapitalLetterU = 0xFF35,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER V Ｖ
            /// </summary>
            FullwidthLatinCapitalLetterV = 0xFF36,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER W Ｗ
            /// </summary>
            FullwidthLatinCapitalLetterW = 0xFF37,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER X Ｘ
            /// </summary>
            FullwidthLatinCapitalLetterX = 0xFF38,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER Y Ｙ
            /// </summary>
            FullwidthLatinCapitalLetterY = 0xFF39,
            /// <summary>
            /// FULLWIDTH LATIN CAPITAL LETTER Z Ｚ
            /// </summary>
            FullwidthLatinCapitalLetterZ = 0xFF3A
        }
        public enum ModifierSymbol : int
        {
            /// <summary>
            /// FULLWIDTH CIRCUMFLEX ACCENT ＾
            /// </summary>
            FullwidthCircumflexAccent = 0xFF3E,
            /// <summary>
            /// FULLWIDTH GRAVE ACCENT ｀
            /// </summary>
            FullwidthGraveAccent = 0xFF40,
            /// <summary>
            /// FULLWIDTH MACRON ￣
            /// </summary>
            FullwidthMacron = 0xFFE3
        }
        public enum ConnectorPunctuation : int
        {
            /// <summary>
            /// FULLWIDTH LOW LINE ＿
            /// </summary>
            FullwidthLowLine = 0xFF3F
        }
        public enum LowercaseLetter : int
        {
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER A ａ
            /// </summary>
            FullwidthLatinSmallLetterA = 0xFF41,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER B ｂ
            /// </summary>
            FullwidthLatinSmallLetterB = 0xFF42,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER C ｃ
            /// </summary>
            FullwidthLatinSmallLetterC = 0xFF43,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER D ｄ
            /// </summary>
            FullwidthLatinSmallLetterD = 0xFF44,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER E ｅ
            /// </summary>
            FullwidthLatinSmallLetterE = 0xFF45,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER F ｆ
            /// </summary>
            FullwidthLatinSmallLetterF = 0xFF46,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER G ｇ
            /// </summary>
            FullwidthLatinSmallLetterG = 0xFF47,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER H ｈ
            /// </summary>
            FullwidthLatinSmallLetterH = 0xFF48,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER I ｉ
            /// </summary>
            FullwidthLatinSmallLetterI = 0xFF49,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER J ｊ
            /// </summary>
            FullwidthLatinSmallLetterJ = 0xFF4A,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER K ｋ
            /// </summary>
            FullwidthLatinSmallLetterK = 0xFF4B,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER L ｌ
            /// </summary>
            FullwidthLatinSmallLetterL = 0xFF4C,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER M ｍ
            /// </summary>
            FullwidthLatinSmallLetterM = 0xFF4D,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER N ｎ
            /// </summary>
            FullwidthLatinSmallLetterN = 0xFF4E,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER O ｏ
            /// </summary>
            FullwidthLatinSmallLetterO = 0xFF4F,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER P ｐ
            /// </summary>
            FullwidthLatinSmallLetterP = 0xFF50,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER Q ｑ
            /// </summary>
            FullwidthLatinSmallLetterQ = 0xFF51,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER R ｒ
            /// </summary>
            FullwidthLatinSmallLetterR = 0xFF52,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER S ｓ
            /// </summary>
            FullwidthLatinSmallLetterS = 0xFF53,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER T ｔ
            /// </summary>
            FullwidthLatinSmallLetterT = 0xFF54,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER U ｕ
            /// </summary>
            FullwidthLatinSmallLetterU = 0xFF55,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER V ｖ
            /// </summary>
            FullwidthLatinSmallLetterV = 0xFF56,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER W ｗ
            /// </summary>
            FullwidthLatinSmallLetterW = 0xFF57,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER X ｘ
            /// </summary>
            FullwidthLatinSmallLetterX = 0xFF58,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER Y ｙ
            /// </summary>
            FullwidthLatinSmallLetterY = 0xFF59,
            /// <summary>
            /// FULLWIDTH LATIN SMALL LETTER Z ｚ
            /// </summary>
            FullwidthLatinSmallLetterZ = 0xFF5A
        }
        public enum OtherLetter : int
        {
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER WO ｦ
            /// </summary>
            HalfwidthKatakanaLetterWo = 0xFF66,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER SMALL A ｧ
            /// </summary>
            HalfwidthKatakanaLetterSmallA = 0xFF67,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER SMALL I ｨ
            /// </summary>
            HalfwidthKatakanaLetterSmallI = 0xFF68,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER SMALL U ｩ
            /// </summary>
            HalfwidthKatakanaLetterSmallU = 0xFF69,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER SMALL E ｪ
            /// </summary>
            HalfwidthKatakanaLetterSmallE = 0xFF6A,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER SMALL O ｫ
            /// </summary>
            HalfwidthKatakanaLetterSmallO = 0xFF6B,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER SMALL YA ｬ
            /// </summary>
            HalfwidthKatakanaLetterSmallYa = 0xFF6C,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER SMALL YU ｭ
            /// </summary>
            HalfwidthKatakanaLetterSmallYu = 0xFF6D,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER SMALL YO ｮ
            /// </summary>
            HalfwidthKatakanaLetterSmallYo = 0xFF6E,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER SMALL TU ｯ
            /// </summary>
            HalfwidthKatakanaLetterSmallTu = 0xFF6F,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER A ｱ
            /// </summary>
            HalfwidthKatakanaLetterA = 0xFF71,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER I ｲ
            /// </summary>
            HalfwidthKatakanaLetterI = 0xFF72,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER U ｳ
            /// </summary>
            HalfwidthKatakanaLetterU = 0xFF73,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER E ｴ
            /// </summary>
            HalfwidthKatakanaLetterE = 0xFF74,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER O ｵ
            /// </summary>
            HalfwidthKatakanaLetterO = 0xFF75,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER KA ｶ
            /// </summary>
            HalfwidthKatakanaLetterKa = 0xFF76,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER KI ｷ
            /// </summary>
            HalfwidthKatakanaLetterKi = 0xFF77,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER KU ｸ
            /// </summary>
            HalfwidthKatakanaLetterKu = 0xFF78,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER KE ｹ
            /// </summary>
            HalfwidthKatakanaLetterKe = 0xFF79,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER KO ｺ
            /// </summary>
            HalfwidthKatakanaLetterKo = 0xFF7A,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER SA ｻ
            /// </summary>
            HalfwidthKatakanaLetterSa = 0xFF7B,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER SI ｼ
            /// </summary>
            HalfwidthKatakanaLetterSi = 0xFF7C,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER SU ｽ
            /// </summary>
            HalfwidthKatakanaLetterSu = 0xFF7D,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER SE ｾ
            /// </summary>
            HalfwidthKatakanaLetterSe = 0xFF7E,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER SO ｿ
            /// </summary>
            HalfwidthKatakanaLetterSo = 0xFF7F,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER TA ﾀ
            /// </summary>
            HalfwidthKatakanaLetterTa = 0xFF80,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER TI ﾁ
            /// </summary>
            HalfwidthKatakanaLetterTi = 0xFF81,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER TU ﾂ
            /// </summary>
            HalfwidthKatakanaLetterTu = 0xFF82,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER TE ﾃ
            /// </summary>
            HalfwidthKatakanaLetterTe = 0xFF83,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER TO ﾄ
            /// </summary>
            HalfwidthKatakanaLetterTo = 0xFF84,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER NA ﾅ
            /// </summary>
            HalfwidthKatakanaLetterNa = 0xFF85,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER NI ﾆ
            /// </summary>
            HalfwidthKatakanaLetterNi = 0xFF86,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER NU ﾇ
            /// </summary>
            HalfwidthKatakanaLetterNu = 0xFF87,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER NE ﾈ
            /// </summary>
            HalfwidthKatakanaLetterNe = 0xFF88,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER NO ﾉ
            /// </summary>
            HalfwidthKatakanaLetterNo = 0xFF89,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER HA ﾊ
            /// </summary>
            HalfwidthKatakanaLetterHa = 0xFF8A,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER HI ﾋ
            /// </summary>
            HalfwidthKatakanaLetterHi = 0xFF8B,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER HU ﾌ
            /// </summary>
            HalfwidthKatakanaLetterHu = 0xFF8C,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER HE ﾍ
            /// </summary>
            HalfwidthKatakanaLetterHe = 0xFF8D,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER HO ﾎ
            /// </summary>
            HalfwidthKatakanaLetterHo = 0xFF8E,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER MA ﾏ
            /// </summary>
            HalfwidthKatakanaLetterMa = 0xFF8F,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER MI ﾐ
            /// </summary>
            HalfwidthKatakanaLetterMi = 0xFF90,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER MU ﾑ
            /// </summary>
            HalfwidthKatakanaLetterMu = 0xFF91,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER ME ﾒ
            /// </summary>
            HalfwidthKatakanaLetterMe = 0xFF92,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER MO ﾓ
            /// </summary>
            HalfwidthKatakanaLetterMo = 0xFF93,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER YA ﾔ
            /// </summary>
            HalfwidthKatakanaLetterYa = 0xFF94,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER YU ﾕ
            /// </summary>
            HalfwidthKatakanaLetterYu = 0xFF95,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER YO ﾖ
            /// </summary>
            HalfwidthKatakanaLetterYo = 0xFF96,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER RA ﾗ
            /// </summary>
            HalfwidthKatakanaLetterRa = 0xFF97,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER RI ﾘ
            /// </summary>
            HalfwidthKatakanaLetterRi = 0xFF98,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER RU ﾙ
            /// </summary>
            HalfwidthKatakanaLetterRu = 0xFF99,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER RE ﾚ
            /// </summary>
            HalfwidthKatakanaLetterRe = 0xFF9A,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER RO ﾛ
            /// </summary>
            HalfwidthKatakanaLetterRo = 0xFF9B,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER WA ﾜ
            /// </summary>
            HalfwidthKatakanaLetterWa = 0xFF9C,
            /// <summary>
            /// HALFWIDTH KATAKANA LETTER N ﾝ
            /// </summary>
            HalfwidthKatakanaLetterN = 0xFF9D,
            /// <summary>
            /// HALFWIDTH HANGUL FILLER ﾠ
            /// </summary>
            HalfwidthHangulFiller = 0xFFA0,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER KIYEOK ﾡ
            /// </summary>
            HalfwidthHangulLetterKiyeok = 0xFFA1,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER SSANGKIYEOK ﾢ
            /// </summary>
            HalfwidthHangulLetterSsangkiyeok = 0xFFA2,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER KIYEOK-SIOS ﾣ
            /// </summary>
            HalfwidthHangulLetterKiyeokSios = 0xFFA3,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER NIEUN ﾤ
            /// </summary>
            HalfwidthHangulLetterNieun = 0xFFA4,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER NIEUN-CIEUC ﾥ
            /// </summary>
            HalfwidthHangulLetterNieunCieuc = 0xFFA5,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER NIEUN-HIEUH ﾦ
            /// </summary>
            HalfwidthHangulLetterNieunHieuh = 0xFFA6,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER TIKEUT ﾧ
            /// </summary>
            HalfwidthHangulLetterTikeut = 0xFFA7,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER SSANGTIKEUT ﾨ
            /// </summary>
            HalfwidthHangulLetterSsangtikeut = 0xFFA8,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER RIEUL ﾩ
            /// </summary>
            HalfwidthHangulLetterRieul = 0xFFA9,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER RIEUL-KIYEOK ﾪ
            /// </summary>
            HalfwidthHangulLetterRieulKiyeok = 0xFFAA,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER RIEUL-MIEUM ﾫ
            /// </summary>
            HalfwidthHangulLetterRieulMieum = 0xFFAB,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER RIEUL-PIEUP ﾬ
            /// </summary>
            HalfwidthHangulLetterRieulPieup = 0xFFAC,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER RIEUL-SIOS ﾭ
            /// </summary>
            HalfwidthHangulLetterRieulSios = 0xFFAD,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER RIEUL-THIEUTH ﾮ
            /// </summary>
            HalfwidthHangulLetterRieulThieuth = 0xFFAE,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER RIEUL-PHIEUPH ﾯ
            /// </summary>
            HalfwidthHangulLetterRieulPhieuph = 0xFFAF,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER RIEUL-HIEUH ﾰ
            /// </summary>
            HalfwidthHangulLetterRieulHieuh = 0xFFB0,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER MIEUM ﾱ
            /// </summary>
            HalfwidthHangulLetterMieum = 0xFFB1,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER PIEUP ﾲ
            /// </summary>
            HalfwidthHangulLetterPieup = 0xFFB2,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER SSANGPIEUP ﾳ
            /// </summary>
            HalfwidthHangulLetterSsangpieup = 0xFFB3,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER PIEUP-SIOS ﾴ
            /// </summary>
            HalfwidthHangulLetterPieupSios = 0xFFB4,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER SIOS ﾵ
            /// </summary>
            HalfwidthHangulLetterSios = 0xFFB5,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER SSANGSIOS ﾶ
            /// </summary>
            HalfwidthHangulLetterSsangsios = 0xFFB6,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER IEUNG ﾷ
            /// </summary>
            HalfwidthHangulLetterIeung = 0xFFB7,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER CIEUC ﾸ
            /// </summary>
            HalfwidthHangulLetterCieuc = 0xFFB8,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER SSANGCIEUC ﾹ
            /// </summary>
            HalfwidthHangulLetterSsangcieuc = 0xFFB9,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER CHIEUCH ﾺ
            /// </summary>
            HalfwidthHangulLetterChieuch = 0xFFBA,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER KHIEUKH ﾻ
            /// </summary>
            HalfwidthHangulLetterKhieukh = 0xFFBB,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER THIEUTH ﾼ
            /// </summary>
            HalfwidthHangulLetterThieuth = 0xFFBC,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER PHIEUPH ﾽ
            /// </summary>
            HalfwidthHangulLetterPhieuph = 0xFFBD,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER HIEUH ﾾ
            /// </summary>
            HalfwidthHangulLetterHieuh = 0xFFBE,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER A ￂ
            /// </summary>
            HalfwidthHangulLetterA = 0xFFC2,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER AE ￃ
            /// </summary>
            HalfwidthHangulLetterAe = 0xFFC3,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER YA ￄ
            /// </summary>
            HalfwidthHangulLetterYa = 0xFFC4,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER YAE ￅ
            /// </summary>
            HalfwidthHangulLetterYae = 0xFFC5,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER EO ￆ
            /// </summary>
            HalfwidthHangulLetterEo = 0xFFC6,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER E ￇ
            /// </summary>
            HalfwidthHangulLetterE = 0xFFC7,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER YEO ￊ
            /// </summary>
            HalfwidthHangulLetterYeo = 0xFFCA,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER YE ￋ
            /// </summary>
            HalfwidthHangulLetterYe = 0xFFCB,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER O ￌ
            /// </summary>
            HalfwidthHangulLetterO = 0xFFCC,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER WA ￍ
            /// </summary>
            HalfwidthHangulLetterWa = 0xFFCD,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER WAE ￎ
            /// </summary>
            HalfwidthHangulLetterWae = 0xFFCE,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER OE ￏ
            /// </summary>
            HalfwidthHangulLetterOe = 0xFFCF,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER YO ￒ
            /// </summary>
            HalfwidthHangulLetterYo = 0xFFD2,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER U ￓ
            /// </summary>
            HalfwidthHangulLetterU = 0xFFD3,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER WEO ￔ
            /// </summary>
            HalfwidthHangulLetterWeo = 0xFFD4,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER WE ￕ
            /// </summary>
            HalfwidthHangulLetterWe = 0xFFD5,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER WI ￖ
            /// </summary>
            HalfwidthHangulLetterWi = 0xFFD6,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER YU ￗ
            /// </summary>
            HalfwidthHangulLetterYu = 0xFFD7,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER EU ￚ
            /// </summary>
            HalfwidthHangulLetterEu = 0xFFDA,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER YI ￛ
            /// </summary>
            HalfwidthHangulLetterYi = 0xFFDB,
            /// <summary>
            /// HALFWIDTH HANGUL LETTER I ￜ
            /// </summary>
            HalfwidthHangulLetterI = 0xFFDC
        }
        public enum ModifierLetter : int
        {
            /// <summary>
            /// HALFWIDTH KATAKANA-HIRAGANA PROLONGED SOUND MARK ｰ
            /// </summary>
            HalfwidthKatakanaHiraganaProlongedSoundMark = 0xFF70,
            /// <summary>
            /// HALFWIDTH KATAKANA VOICED SOUND MARK ﾞ
            /// </summary>
            HalfwidthKatakanaVoicedSoundMark = 0xFF9E,
            /// <summary>
            /// HALFWIDTH KATAKANA SEMI-VOICED SOUND MARK ﾟ
            /// </summary>
            HalfwidthKatakanaSemiVoicedSoundMark = 0xFF9F
        }
        public enum OtherSymbol : int
        {
            /// <summary>
            /// FULLWIDTH BROKEN BAR ￤
            /// </summary>
            FullwidthBrokenBar = 0xFFE4,
            /// <summary>
            /// HALFWIDTH FORMS LIGHT VERTICAL ￨
            /// </summary>
            HalfwidthFormsLightVertical = 0xFFE8,
            /// <summary>
            /// HALFWIDTH BLACK SQUARE ￭
            /// </summary>
            HalfwidthBlackSquare = 0xFFED,
            /// <summary>
            /// HALFWIDTH WHITE CIRCLE ￮
            /// </summary>
            HalfwidthWhiteCircle = 0xFFEE
        }
    }
}
