// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class MyanmarExtendedB
    {
        public enum OtherLetter : int
        {
            /// <summary>
            /// MYANMAR LETTER SHAN GHA ꧠ
            /// </summary>
            MyanmarLetterShanGha = 0xA9E0,
            /// <summary>
            /// MYANMAR LETTER SHAN CHA ꧡ
            /// </summary>
            MyanmarLetterShanCha = 0xA9E1,
            /// <summary>
            /// MYANMAR LETTER SHAN JHA ꧢ
            /// </summary>
            MyanmarLetterShanJha = 0xA9E2,
            /// <summary>
            /// MYANMAR LETTER SHAN NNA ꧣ
            /// </summary>
            MyanmarLetterShanNna = 0xA9E3,
            /// <summary>
            /// MYANMAR LETTER SHAN BHA ꧤ
            /// </summary>
            MyanmarLetterShanBha = 0xA9E4,
            /// <summary>
            /// MYANMAR LETTER TAI LAING NYA ꧧ
            /// </summary>
            MyanmarLetterTaiLaingNya = 0xA9E7,
            /// <summary>
            /// MYANMAR LETTER TAI LAING FA ꧨ
            /// </summary>
            MyanmarLetterTaiLaingFa = 0xA9E8,
            /// <summary>
            /// MYANMAR LETTER TAI LAING GA ꧩ
            /// </summary>
            MyanmarLetterTaiLaingGa = 0xA9E9,
            /// <summary>
            /// MYANMAR LETTER TAI LAING GHA ꧪ
            /// </summary>
            MyanmarLetterTaiLaingGha = 0xA9EA,
            /// <summary>
            /// MYANMAR LETTER TAI LAING JA ꧫ
            /// </summary>
            MyanmarLetterTaiLaingJa = 0xA9EB,
            /// <summary>
            /// MYANMAR LETTER TAI LAING JHA ꧬ
            /// </summary>
            MyanmarLetterTaiLaingJha = 0xA9EC,
            /// <summary>
            /// MYANMAR LETTER TAI LAING DDA ꧭ
            /// </summary>
            MyanmarLetterTaiLaingDda = 0xA9ED,
            /// <summary>
            /// MYANMAR LETTER TAI LAING DDHA ꧮ
            /// </summary>
            MyanmarLetterTaiLaingDdha = 0xA9EE,
            /// <summary>
            /// MYANMAR LETTER TAI LAING NNA ꧯ
            /// </summary>
            MyanmarLetterTaiLaingNna = 0xA9EF,
            /// <summary>
            /// MYANMAR LETTER TAI LAING LLA ꧺ
            /// </summary>
            MyanmarLetterTaiLaingLla = 0xA9FA,
            /// <summary>
            /// MYANMAR LETTER TAI LAING DA ꧻ
            /// </summary>
            MyanmarLetterTaiLaingDa = 0xA9FB,
            /// <summary>
            /// MYANMAR LETTER TAI LAING DHA ꧼ
            /// </summary>
            MyanmarLetterTaiLaingDha = 0xA9FC,
            /// <summary>
            /// MYANMAR LETTER TAI LAING BA ꧽ
            /// </summary>
            MyanmarLetterTaiLaingBa = 0xA9FD,
            /// <summary>
            /// MYANMAR LETTER TAI LAING BHA ꧾ
            /// </summary>
            MyanmarLetterTaiLaingBha = 0xA9FE
        }
        public enum NonSpacingMark : int
        {
            /// <summary>
            /// MYANMAR SIGN SHAN SAW ꧥ
            /// </summary>
            MyanmarSignShanSaw = 0xA9E5
        }
        public enum ModifierLetter : int
        {
            /// <summary>
            /// MYANMAR MODIFIER LETTER SHAN REDUPLICATION ꧦ
            /// </summary>
            MyanmarModifierLetterShanReduplication = 0xA9E6
        }
        public enum DecimalDigitNumber : int
        {
            /// <summary>
            /// MYANMAR TAI LAING DIGIT ZERO ꧰
            /// </summary>
            MyanmarTaiLaingDigitZero = 0xA9F0,
            /// <summary>
            /// MYANMAR TAI LAING DIGIT ONE ꧱
            /// </summary>
            MyanmarTaiLaingDigitOne = 0xA9F1,
            /// <summary>
            /// MYANMAR TAI LAING DIGIT TWO ꧲
            /// </summary>
            MyanmarTaiLaingDigitTwo = 0xA9F2,
            /// <summary>
            /// MYANMAR TAI LAING DIGIT THREE ꧳
            /// </summary>
            MyanmarTaiLaingDigitThree = 0xA9F3,
            /// <summary>
            /// MYANMAR TAI LAING DIGIT FOUR ꧴
            /// </summary>
            MyanmarTaiLaingDigitFour = 0xA9F4,
            /// <summary>
            /// MYANMAR TAI LAING DIGIT FIVE ꧵
            /// </summary>
            MyanmarTaiLaingDigitFive = 0xA9F5,
            /// <summary>
            /// MYANMAR TAI LAING DIGIT SIX ꧶
            /// </summary>
            MyanmarTaiLaingDigitSix = 0xA9F6,
            /// <summary>
            /// MYANMAR TAI LAING DIGIT SEVEN ꧷
            /// </summary>
            MyanmarTaiLaingDigitSeven = 0xA9F7,
            /// <summary>
            /// MYANMAR TAI LAING DIGIT EIGHT ꧸
            /// </summary>
            MyanmarTaiLaingDigitEight = 0xA9F8,
            /// <summary>
            /// MYANMAR TAI LAING DIGIT NINE ꧹
            /// </summary>
            MyanmarTaiLaingDigitNine = 0xA9F9
        }
    }
}
