// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class EnclosedCJKLettersandMonths
    {
        public enum OtherSymbol : int
        {
            /// <summary>
            /// PARENTHESIZED HANGUL KIYEOK ㈀
            /// </summary>
            ParenthesizedHangulKiyeok = 0x3200,
            /// <summary>
            /// PARENTHESIZED HANGUL NIEUN ㈁
            /// </summary>
            ParenthesizedHangulNieun = 0x3201,
            /// <summary>
            /// PARENTHESIZED HANGUL TIKEUT ㈂
            /// </summary>
            ParenthesizedHangulTikeut = 0x3202,
            /// <summary>
            /// PARENTHESIZED HANGUL RIEUL ㈃
            /// </summary>
            ParenthesizedHangulRieul = 0x3203,
            /// <summary>
            /// PARENTHESIZED HANGUL MIEUM ㈄
            /// </summary>
            ParenthesizedHangulMieum = 0x3204,
            /// <summary>
            /// PARENTHESIZED HANGUL PIEUP ㈅
            /// </summary>
            ParenthesizedHangulPieup = 0x3205,
            /// <summary>
            /// PARENTHESIZED HANGUL SIOS ㈆
            /// </summary>
            ParenthesizedHangulSios = 0x3206,
            /// <summary>
            /// PARENTHESIZED HANGUL IEUNG ㈇
            /// </summary>
            ParenthesizedHangulIeung = 0x3207,
            /// <summary>
            /// PARENTHESIZED HANGUL CIEUC ㈈
            /// </summary>
            ParenthesizedHangulCieuc = 0x3208,
            /// <summary>
            /// PARENTHESIZED HANGUL CHIEUCH ㈉
            /// </summary>
            ParenthesizedHangulChieuch = 0x3209,
            /// <summary>
            /// PARENTHESIZED HANGUL KHIEUKH ㈊
            /// </summary>
            ParenthesizedHangulKhieukh = 0x320A,
            /// <summary>
            /// PARENTHESIZED HANGUL THIEUTH ㈋
            /// </summary>
            ParenthesizedHangulThieuth = 0x320B,
            /// <summary>
            /// PARENTHESIZED HANGUL PHIEUPH ㈌
            /// </summary>
            ParenthesizedHangulPhieuph = 0x320C,
            /// <summary>
            /// PARENTHESIZED HANGUL HIEUH ㈍
            /// </summary>
            ParenthesizedHangulHieuh = 0x320D,
            /// <summary>
            /// PARENTHESIZED HANGUL KIYEOK A ㈎
            /// </summary>
            ParenthesizedHangulKiyeokA = 0x320E,
            /// <summary>
            /// PARENTHESIZED HANGUL NIEUN A ㈏
            /// </summary>
            ParenthesizedHangulNieunA = 0x320F,
            /// <summary>
            /// PARENTHESIZED HANGUL TIKEUT A ㈐
            /// </summary>
            ParenthesizedHangulTikeutA = 0x3210,
            /// <summary>
            /// PARENTHESIZED HANGUL RIEUL A ㈑
            /// </summary>
            ParenthesizedHangulRieulA = 0x3211,
            /// <summary>
            /// PARENTHESIZED HANGUL MIEUM A ㈒
            /// </summary>
            ParenthesizedHangulMieumA = 0x3212,
            /// <summary>
            /// PARENTHESIZED HANGUL PIEUP A ㈓
            /// </summary>
            ParenthesizedHangulPieupA = 0x3213,
            /// <summary>
            /// PARENTHESIZED HANGUL SIOS A ㈔
            /// </summary>
            ParenthesizedHangulSiosA = 0x3214,
            /// <summary>
            /// PARENTHESIZED HANGUL IEUNG A ㈕
            /// </summary>
            ParenthesizedHangulIeungA = 0x3215,
            /// <summary>
            /// PARENTHESIZED HANGUL CIEUC A ㈖
            /// </summary>
            ParenthesizedHangulCieucA = 0x3216,
            /// <summary>
            /// PARENTHESIZED HANGUL CHIEUCH A ㈗
            /// </summary>
            ParenthesizedHangulChieuchA = 0x3217,
            /// <summary>
            /// PARENTHESIZED HANGUL KHIEUKH A ㈘
            /// </summary>
            ParenthesizedHangulKhieukhA = 0x3218,
            /// <summary>
            /// PARENTHESIZED HANGUL THIEUTH A ㈙
            /// </summary>
            ParenthesizedHangulThieuthA = 0x3219,
            /// <summary>
            /// PARENTHESIZED HANGUL PHIEUPH A ㈚
            /// </summary>
            ParenthesizedHangulPhieuphA = 0x321A,
            /// <summary>
            /// PARENTHESIZED HANGUL HIEUH A ㈛
            /// </summary>
            ParenthesizedHangulHieuhA = 0x321B,
            /// <summary>
            /// PARENTHESIZED HANGUL CIEUC U ㈜
            /// </summary>
            ParenthesizedHangulCieucU = 0x321C,
            /// <summary>
            /// PARENTHESIZED KOREAN CHARACTER OJEON ㈝
            /// </summary>
            ParenthesizedKoreanCharacterOjeon = 0x321D,
            /// <summary>
            /// PARENTHESIZED KOREAN CHARACTER O HU ㈞
            /// </summary>
            ParenthesizedKoreanCharacterOHu = 0x321E,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH MOON ㈪
            /// </summary>
            ParenthesizedIdeographMoon = 0x322A,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH FIRE ㈫
            /// </summary>
            ParenthesizedIdeographFire = 0x322B,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH WATER ㈬
            /// </summary>
            ParenthesizedIdeographWater = 0x322C,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH WOOD ㈭
            /// </summary>
            ParenthesizedIdeographWood = 0x322D,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH METAL ㈮
            /// </summary>
            ParenthesizedIdeographMetal = 0x322E,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH EARTH ㈯
            /// </summary>
            ParenthesizedIdeographEarth = 0x322F,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH SUN ㈰
            /// </summary>
            ParenthesizedIdeographSun = 0x3230,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH STOCK ㈱
            /// </summary>
            ParenthesizedIdeographStock = 0x3231,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH HAVE ㈲
            /// </summary>
            ParenthesizedIdeographHave = 0x3232,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH SOCIETY ㈳
            /// </summary>
            ParenthesizedIdeographSociety = 0x3233,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH NAME ㈴
            /// </summary>
            ParenthesizedIdeographName = 0x3234,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH SPECIAL ㈵
            /// </summary>
            ParenthesizedIdeographSpecial = 0x3235,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH FINANCIAL ㈶
            /// </summary>
            ParenthesizedIdeographFinancial = 0x3236,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH CONGRATULATION ㈷
            /// </summary>
            ParenthesizedIdeographCongratulation = 0x3237,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH LABOR ㈸
            /// </summary>
            ParenthesizedIdeographLabor = 0x3238,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH REPRESENT ㈹
            /// </summary>
            ParenthesizedIdeographRepresent = 0x3239,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH CALL ㈺
            /// </summary>
            ParenthesizedIdeographCall = 0x323A,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH STUDY ㈻
            /// </summary>
            ParenthesizedIdeographStudy = 0x323B,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH SUPERVISE ㈼
            /// </summary>
            ParenthesizedIdeographSupervise = 0x323C,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH ENTERPRISE ㈽
            /// </summary>
            ParenthesizedIdeographEnterprise = 0x323D,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH RESOURCE ㈾
            /// </summary>
            ParenthesizedIdeographResource = 0x323E,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH ALLIANCE ㈿
            /// </summary>
            ParenthesizedIdeographAlliance = 0x323F,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH FESTIVAL ㉀
            /// </summary>
            ParenthesizedIdeographFestival = 0x3240,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH REST ㉁
            /// </summary>
            ParenthesizedIdeographRest = 0x3241,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH SELF ㉂
            /// </summary>
            ParenthesizedIdeographSelf = 0x3242,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH REACH ㉃
            /// </summary>
            ParenthesizedIdeographReach = 0x3243,
            /// <summary>
            /// CIRCLED IDEOGRAPH QUESTION ㉄
            /// </summary>
            CircledIdeographQuestion = 0x3244,
            /// <summary>
            /// CIRCLED IDEOGRAPH KINDERGARTEN ㉅
            /// </summary>
            CircledIdeographKindergarten = 0x3245,
            /// <summary>
            /// CIRCLED IDEOGRAPH SCHOOL ㉆
            /// </summary>
            CircledIdeographSchool = 0x3246,
            /// <summary>
            /// CIRCLED IDEOGRAPH KOTO ㉇
            /// </summary>
            CircledIdeographKoto = 0x3247,
            /// <summary>
            /// PARTNERSHIP SIGN ㉐
            /// </summary>
            PartnershipSign = 0x3250,
            /// <summary>
            /// CIRCLED HANGUL KIYEOK ㉠
            /// </summary>
            CircledHangulKiyeok = 0x3260,
            /// <summary>
            /// CIRCLED HANGUL NIEUN ㉡
            /// </summary>
            CircledHangulNieun = 0x3261,
            /// <summary>
            /// CIRCLED HANGUL TIKEUT ㉢
            /// </summary>
            CircledHangulTikeut = 0x3262,
            /// <summary>
            /// CIRCLED HANGUL RIEUL ㉣
            /// </summary>
            CircledHangulRieul = 0x3263,
            /// <summary>
            /// CIRCLED HANGUL MIEUM ㉤
            /// </summary>
            CircledHangulMieum = 0x3264,
            /// <summary>
            /// CIRCLED HANGUL PIEUP ㉥
            /// </summary>
            CircledHangulPieup = 0x3265,
            /// <summary>
            /// CIRCLED HANGUL SIOS ㉦
            /// </summary>
            CircledHangulSios = 0x3266,
            /// <summary>
            /// CIRCLED HANGUL IEUNG ㉧
            /// </summary>
            CircledHangulIeung = 0x3267,
            /// <summary>
            /// CIRCLED HANGUL CIEUC ㉨
            /// </summary>
            CircledHangulCieuc = 0x3268,
            /// <summary>
            /// CIRCLED HANGUL CHIEUCH ㉩
            /// </summary>
            CircledHangulChieuch = 0x3269,
            /// <summary>
            /// CIRCLED HANGUL KHIEUKH ㉪
            /// </summary>
            CircledHangulKhieukh = 0x326A,
            /// <summary>
            /// CIRCLED HANGUL THIEUTH ㉫
            /// </summary>
            CircledHangulThieuth = 0x326B,
            /// <summary>
            /// CIRCLED HANGUL PHIEUPH ㉬
            /// </summary>
            CircledHangulPhieuph = 0x326C,
            /// <summary>
            /// CIRCLED HANGUL HIEUH ㉭
            /// </summary>
            CircledHangulHieuh = 0x326D,
            /// <summary>
            /// CIRCLED HANGUL KIYEOK A ㉮
            /// </summary>
            CircledHangulKiyeokA = 0x326E,
            /// <summary>
            /// CIRCLED HANGUL NIEUN A ㉯
            /// </summary>
            CircledHangulNieunA = 0x326F,
            /// <summary>
            /// CIRCLED HANGUL TIKEUT A ㉰
            /// </summary>
            CircledHangulTikeutA = 0x3270,
            /// <summary>
            /// CIRCLED HANGUL RIEUL A ㉱
            /// </summary>
            CircledHangulRieulA = 0x3271,
            /// <summary>
            /// CIRCLED HANGUL MIEUM A ㉲
            /// </summary>
            CircledHangulMieumA = 0x3272,
            /// <summary>
            /// CIRCLED HANGUL PIEUP A ㉳
            /// </summary>
            CircledHangulPieupA = 0x3273,
            /// <summary>
            /// CIRCLED HANGUL SIOS A ㉴
            /// </summary>
            CircledHangulSiosA = 0x3274,
            /// <summary>
            /// CIRCLED HANGUL IEUNG A ㉵
            /// </summary>
            CircledHangulIeungA = 0x3275,
            /// <summary>
            /// CIRCLED HANGUL CIEUC A ㉶
            /// </summary>
            CircledHangulCieucA = 0x3276,
            /// <summary>
            /// CIRCLED HANGUL CHIEUCH A ㉷
            /// </summary>
            CircledHangulChieuchA = 0x3277,
            /// <summary>
            /// CIRCLED HANGUL KHIEUKH A ㉸
            /// </summary>
            CircledHangulKhieukhA = 0x3278,
            /// <summary>
            /// CIRCLED HANGUL THIEUTH A ㉹
            /// </summary>
            CircledHangulThieuthA = 0x3279,
            /// <summary>
            /// CIRCLED HANGUL PHIEUPH A ㉺
            /// </summary>
            CircledHangulPhieuphA = 0x327A,
            /// <summary>
            /// CIRCLED HANGUL HIEUH A ㉻
            /// </summary>
            CircledHangulHieuhA = 0x327B,
            /// <summary>
            /// CIRCLED KOREAN CHARACTER CHAMKO ㉼
            /// </summary>
            CircledKoreanCharacterChamko = 0x327C,
            /// <summary>
            /// CIRCLED KOREAN CHARACTER JUEUI ㉽
            /// </summary>
            CircledKoreanCharacterJueui = 0x327D,
            /// <summary>
            /// CIRCLED HANGUL IEUNG U ㉾
            /// </summary>
            CircledHangulIeungU = 0x327E,
            /// <summary>
            /// KOREAN STANDARD SYMBOL ㉿
            /// </summary>
            KoreanStandardSymbol = 0x327F,
            /// <summary>
            /// CIRCLED IDEOGRAPH MOON ㊊
            /// </summary>
            CircledIdeographMoon = 0x328A,
            /// <summary>
            /// CIRCLED IDEOGRAPH FIRE ㊋
            /// </summary>
            CircledIdeographFire = 0x328B,
            /// <summary>
            /// CIRCLED IDEOGRAPH WATER ㊌
            /// </summary>
            CircledIdeographWater = 0x328C,
            /// <summary>
            /// CIRCLED IDEOGRAPH WOOD ㊍
            /// </summary>
            CircledIdeographWood = 0x328D,
            /// <summary>
            /// CIRCLED IDEOGRAPH METAL ㊎
            /// </summary>
            CircledIdeographMetal = 0x328E,
            /// <summary>
            /// CIRCLED IDEOGRAPH EARTH ㊏
            /// </summary>
            CircledIdeographEarth = 0x328F,
            /// <summary>
            /// CIRCLED IDEOGRAPH SUN ㊐
            /// </summary>
            CircledIdeographSun = 0x3290,
            /// <summary>
            /// CIRCLED IDEOGRAPH STOCK ㊑
            /// </summary>
            CircledIdeographStock = 0x3291,
            /// <summary>
            /// CIRCLED IDEOGRAPH HAVE ㊒
            /// </summary>
            CircledIdeographHave = 0x3292,
            /// <summary>
            /// CIRCLED IDEOGRAPH SOCIETY ㊓
            /// </summary>
            CircledIdeographSociety = 0x3293,
            /// <summary>
            /// CIRCLED IDEOGRAPH NAME ㊔
            /// </summary>
            CircledIdeographName = 0x3294,
            /// <summary>
            /// CIRCLED IDEOGRAPH SPECIAL ㊕
            /// </summary>
            CircledIdeographSpecial = 0x3295,
            /// <summary>
            /// CIRCLED IDEOGRAPH FINANCIAL ㊖
            /// </summary>
            CircledIdeographFinancial = 0x3296,
            /// <summary>
            /// CIRCLED IDEOGRAPH CONGRATULATION ㊗
            /// </summary>
            CircledIdeographCongratulation = 0x3297,
            /// <summary>
            /// CIRCLED IDEOGRAPH LABOR ㊘
            /// </summary>
            CircledIdeographLabor = 0x3298,
            /// <summary>
            /// CIRCLED IDEOGRAPH SECRET ㊙
            /// </summary>
            CircledIdeographSecret = 0x3299,
            /// <summary>
            /// CIRCLED IDEOGRAPH MALE ㊚
            /// </summary>
            CircledIdeographMale = 0x329A,
            /// <summary>
            /// CIRCLED IDEOGRAPH FEMALE ㊛
            /// </summary>
            CircledIdeographFemale = 0x329B,
            /// <summary>
            /// CIRCLED IDEOGRAPH SUITABLE ㊜
            /// </summary>
            CircledIdeographSuitable = 0x329C,
            /// <summary>
            /// CIRCLED IDEOGRAPH EXCELLENT ㊝
            /// </summary>
            CircledIdeographExcellent = 0x329D,
            /// <summary>
            /// CIRCLED IDEOGRAPH PRINT ㊞
            /// </summary>
            CircledIdeographPrint = 0x329E,
            /// <summary>
            /// CIRCLED IDEOGRAPH ATTENTION ㊟
            /// </summary>
            CircledIdeographAttention = 0x329F,
            /// <summary>
            /// CIRCLED IDEOGRAPH ITEM ㊠
            /// </summary>
            CircledIdeographItem = 0x32A0,
            /// <summary>
            /// CIRCLED IDEOGRAPH REST ㊡
            /// </summary>
            CircledIdeographRest = 0x32A1,
            /// <summary>
            /// CIRCLED IDEOGRAPH COPY ㊢
            /// </summary>
            CircledIdeographCopy = 0x32A2,
            /// <summary>
            /// CIRCLED IDEOGRAPH CORRECT ㊣
            /// </summary>
            CircledIdeographCorrect = 0x32A3,
            /// <summary>
            /// CIRCLED IDEOGRAPH HIGH ㊤
            /// </summary>
            CircledIdeographHigh = 0x32A4,
            /// <summary>
            /// CIRCLED IDEOGRAPH CENTRE ㊥
            /// </summary>
            CircledIdeographCentre = 0x32A5,
            /// <summary>
            /// CIRCLED IDEOGRAPH LOW ㊦
            /// </summary>
            CircledIdeographLow = 0x32A6,
            /// <summary>
            /// CIRCLED IDEOGRAPH LEFT ㊧
            /// </summary>
            CircledIdeographLeft = 0x32A7,
            /// <summary>
            /// CIRCLED IDEOGRAPH RIGHT ㊨
            /// </summary>
            CircledIdeographRight = 0x32A8,
            /// <summary>
            /// CIRCLED IDEOGRAPH MEDICINE ㊩
            /// </summary>
            CircledIdeographMedicine = 0x32A9,
            /// <summary>
            /// CIRCLED IDEOGRAPH RELIGION ㊪
            /// </summary>
            CircledIdeographReligion = 0x32AA,
            /// <summary>
            /// CIRCLED IDEOGRAPH STUDY ㊫
            /// </summary>
            CircledIdeographStudy = 0x32AB,
            /// <summary>
            /// CIRCLED IDEOGRAPH SUPERVISE ㊬
            /// </summary>
            CircledIdeographSupervise = 0x32AC,
            /// <summary>
            /// CIRCLED IDEOGRAPH ENTERPRISE ㊭
            /// </summary>
            CircledIdeographEnterprise = 0x32AD,
            /// <summary>
            /// CIRCLED IDEOGRAPH RESOURCE ㊮
            /// </summary>
            CircledIdeographResource = 0x32AE,
            /// <summary>
            /// CIRCLED IDEOGRAPH ALLIANCE ㊯
            /// </summary>
            CircledIdeographAlliance = 0x32AF,
            /// <summary>
            /// CIRCLED IDEOGRAPH NIGHT ㊰
            /// </summary>
            CircledIdeographNight = 0x32B0,
            /// <summary>
            /// IDEOGRAPHIC TELEGRAPH SYMBOL FOR JANUARY ㋀
            /// </summary>
            IdeographicTelegraphSymbolForJanuary = 0x32C0,
            /// <summary>
            /// IDEOGRAPHIC TELEGRAPH SYMBOL FOR FEBRUARY ㋁
            /// </summary>
            IdeographicTelegraphSymbolForFebruary = 0x32C1,
            /// <summary>
            /// IDEOGRAPHIC TELEGRAPH SYMBOL FOR MARCH ㋂
            /// </summary>
            IdeographicTelegraphSymbolForMarch = 0x32C2,
            /// <summary>
            /// IDEOGRAPHIC TELEGRAPH SYMBOL FOR APRIL ㋃
            /// </summary>
            IdeographicTelegraphSymbolForApril = 0x32C3,
            /// <summary>
            /// IDEOGRAPHIC TELEGRAPH SYMBOL FOR MAY ㋄
            /// </summary>
            IdeographicTelegraphSymbolForMay = 0x32C4,
            /// <summary>
            /// IDEOGRAPHIC TELEGRAPH SYMBOL FOR JUNE ㋅
            /// </summary>
            IdeographicTelegraphSymbolForJune = 0x32C5,
            /// <summary>
            /// IDEOGRAPHIC TELEGRAPH SYMBOL FOR JULY ㋆
            /// </summary>
            IdeographicTelegraphSymbolForJuly = 0x32C6,
            /// <summary>
            /// IDEOGRAPHIC TELEGRAPH SYMBOL FOR AUGUST ㋇
            /// </summary>
            IdeographicTelegraphSymbolForAugust = 0x32C7,
            /// <summary>
            /// IDEOGRAPHIC TELEGRAPH SYMBOL FOR SEPTEMBER ㋈
            /// </summary>
            IdeographicTelegraphSymbolForSeptember = 0x32C8,
            /// <summary>
            /// IDEOGRAPHIC TELEGRAPH SYMBOL FOR OCTOBER ㋉
            /// </summary>
            IdeographicTelegraphSymbolForOctober = 0x32C9,
            /// <summary>
            /// IDEOGRAPHIC TELEGRAPH SYMBOL FOR NOVEMBER ㋊
            /// </summary>
            IdeographicTelegraphSymbolForNovember = 0x32CA,
            /// <summary>
            /// IDEOGRAPHIC TELEGRAPH SYMBOL FOR DECEMBER ㋋
            /// </summary>
            IdeographicTelegraphSymbolForDecember = 0x32CB,
            /// <summary>
            /// SQUARE HG ㋌
            /// </summary>
            SquareHg = 0x32CC,
            /// <summary>
            /// SQUARE ERG ㋍
            /// </summary>
            SquareErg = 0x32CD,
            /// <summary>
            /// SQUARE EV ㋎
            /// </summary>
            SquareEv = 0x32CE,
            /// <summary>
            /// LIMITED LIABILITY SIGN ㋏
            /// </summary>
            LimitedLiabilitySign = 0x32CF,
            /// <summary>
            /// CIRCLED KATAKANA A ㋐
            /// </summary>
            CircledKatakanaA = 0x32D0,
            /// <summary>
            /// CIRCLED KATAKANA I ㋑
            /// </summary>
            CircledKatakanaI = 0x32D1,
            /// <summary>
            /// CIRCLED KATAKANA U ㋒
            /// </summary>
            CircledKatakanaU = 0x32D2,
            /// <summary>
            /// CIRCLED KATAKANA E ㋓
            /// </summary>
            CircledKatakanaE = 0x32D3,
            /// <summary>
            /// CIRCLED KATAKANA O ㋔
            /// </summary>
            CircledKatakanaO = 0x32D4,
            /// <summary>
            /// CIRCLED KATAKANA KA ㋕
            /// </summary>
            CircledKatakanaKa = 0x32D5,
            /// <summary>
            /// CIRCLED KATAKANA KI ㋖
            /// </summary>
            CircledKatakanaKi = 0x32D6,
            /// <summary>
            /// CIRCLED KATAKANA KU ㋗
            /// </summary>
            CircledKatakanaKu = 0x32D7,
            /// <summary>
            /// CIRCLED KATAKANA KE ㋘
            /// </summary>
            CircledKatakanaKe = 0x32D8,
            /// <summary>
            /// CIRCLED KATAKANA KO ㋙
            /// </summary>
            CircledKatakanaKo = 0x32D9,
            /// <summary>
            /// CIRCLED KATAKANA SA ㋚
            /// </summary>
            CircledKatakanaSa = 0x32DA,
            /// <summary>
            /// CIRCLED KATAKANA SI ㋛
            /// </summary>
            CircledKatakanaSi = 0x32DB,
            /// <summary>
            /// CIRCLED KATAKANA SU ㋜
            /// </summary>
            CircledKatakanaSu = 0x32DC,
            /// <summary>
            /// CIRCLED KATAKANA SE ㋝
            /// </summary>
            CircledKatakanaSe = 0x32DD,
            /// <summary>
            /// CIRCLED KATAKANA SO ㋞
            /// </summary>
            CircledKatakanaSo = 0x32DE,
            /// <summary>
            /// CIRCLED KATAKANA TA ㋟
            /// </summary>
            CircledKatakanaTa = 0x32DF,
            /// <summary>
            /// CIRCLED KATAKANA TI ㋠
            /// </summary>
            CircledKatakanaTi = 0x32E0,
            /// <summary>
            /// CIRCLED KATAKANA TU ㋡
            /// </summary>
            CircledKatakanaTu = 0x32E1,
            /// <summary>
            /// CIRCLED KATAKANA TE ㋢
            /// </summary>
            CircledKatakanaTe = 0x32E2,
            /// <summary>
            /// CIRCLED KATAKANA TO ㋣
            /// </summary>
            CircledKatakanaTo = 0x32E3,
            /// <summary>
            /// CIRCLED KATAKANA NA ㋤
            /// </summary>
            CircledKatakanaNa = 0x32E4,
            /// <summary>
            /// CIRCLED KATAKANA NI ㋥
            /// </summary>
            CircledKatakanaNi = 0x32E5,
            /// <summary>
            /// CIRCLED KATAKANA NU ㋦
            /// </summary>
            CircledKatakanaNu = 0x32E6,
            /// <summary>
            /// CIRCLED KATAKANA NE ㋧
            /// </summary>
            CircledKatakanaNe = 0x32E7,
            /// <summary>
            /// CIRCLED KATAKANA NO ㋨
            /// </summary>
            CircledKatakanaNo = 0x32E8,
            /// <summary>
            /// CIRCLED KATAKANA HA ㋩
            /// </summary>
            CircledKatakanaHa = 0x32E9,
            /// <summary>
            /// CIRCLED KATAKANA HI ㋪
            /// </summary>
            CircledKatakanaHi = 0x32EA,
            /// <summary>
            /// CIRCLED KATAKANA HU ㋫
            /// </summary>
            CircledKatakanaHu = 0x32EB,
            /// <summary>
            /// CIRCLED KATAKANA HE ㋬
            /// </summary>
            CircledKatakanaHe = 0x32EC,
            /// <summary>
            /// CIRCLED KATAKANA HO ㋭
            /// </summary>
            CircledKatakanaHo = 0x32ED,
            /// <summary>
            /// CIRCLED KATAKANA MA ㋮
            /// </summary>
            CircledKatakanaMa = 0x32EE,
            /// <summary>
            /// CIRCLED KATAKANA MI ㋯
            /// </summary>
            CircledKatakanaMi = 0x32EF,
            /// <summary>
            /// CIRCLED KATAKANA MU ㋰
            /// </summary>
            CircledKatakanaMu = 0x32F0,
            /// <summary>
            /// CIRCLED KATAKANA ME ㋱
            /// </summary>
            CircledKatakanaMe = 0x32F1,
            /// <summary>
            /// CIRCLED KATAKANA MO ㋲
            /// </summary>
            CircledKatakanaMo = 0x32F2,
            /// <summary>
            /// CIRCLED KATAKANA YA ㋳
            /// </summary>
            CircledKatakanaYa = 0x32F3,
            /// <summary>
            /// CIRCLED KATAKANA YU ㋴
            /// </summary>
            CircledKatakanaYu = 0x32F4,
            /// <summary>
            /// CIRCLED KATAKANA YO ㋵
            /// </summary>
            CircledKatakanaYo = 0x32F5,
            /// <summary>
            /// CIRCLED KATAKANA RA ㋶
            /// </summary>
            CircledKatakanaRa = 0x32F6,
            /// <summary>
            /// CIRCLED KATAKANA RI ㋷
            /// </summary>
            CircledKatakanaRi = 0x32F7,
            /// <summary>
            /// CIRCLED KATAKANA RU ㋸
            /// </summary>
            CircledKatakanaRu = 0x32F8,
            /// <summary>
            /// CIRCLED KATAKANA RE ㋹
            /// </summary>
            CircledKatakanaRe = 0x32F9,
            /// <summary>
            /// CIRCLED KATAKANA RO ㋺
            /// </summary>
            CircledKatakanaRo = 0x32FA,
            /// <summary>
            /// CIRCLED KATAKANA WA ㋻
            /// </summary>
            CircledKatakanaWa = 0x32FB,
            /// <summary>
            /// CIRCLED KATAKANA WI ㋼
            /// </summary>
            CircledKatakanaWi = 0x32FC,
            /// <summary>
            /// CIRCLED KATAKANA WE ㋽
            /// </summary>
            CircledKatakanaWe = 0x32FD,
            /// <summary>
            /// CIRCLED KATAKANA WO ㋾
            /// </summary>
            CircledKatakanaWo = 0x32FE
        }
        public enum OtherNumber : int
        {
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH ONE ㈠
            /// </summary>
            ParenthesizedIdeographOne = 0x3220,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH TWO ㈡
            /// </summary>
            ParenthesizedIdeographTwo = 0x3221,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH THREE ㈢
            /// </summary>
            ParenthesizedIdeographThree = 0x3222,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH FOUR ㈣
            /// </summary>
            ParenthesizedIdeographFour = 0x3223,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH FIVE ㈤
            /// </summary>
            ParenthesizedIdeographFive = 0x3224,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH SIX ㈥
            /// </summary>
            ParenthesizedIdeographSix = 0x3225,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH SEVEN ㈦
            /// </summary>
            ParenthesizedIdeographSeven = 0x3226,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH EIGHT ㈧
            /// </summary>
            ParenthesizedIdeographEight = 0x3227,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH NINE ㈨
            /// </summary>
            ParenthesizedIdeographNine = 0x3228,
            /// <summary>
            /// PARENTHESIZED IDEOGRAPH TEN ㈩
            /// </summary>
            ParenthesizedIdeographTen = 0x3229,
            /// <summary>
            /// CIRCLED NUMBER TEN ON BLACK SQUARE ㉈
            /// </summary>
            CircledNumberTenOnBlackSquare = 0x3248,
            /// <summary>
            /// CIRCLED NUMBER TWENTY ON BLACK SQUARE ㉉
            /// </summary>
            CircledNumberTwentyOnBlackSquare = 0x3249,
            /// <summary>
            /// CIRCLED NUMBER THIRTY ON BLACK SQUARE ㉊
            /// </summary>
            CircledNumberThirtyOnBlackSquare = 0x324A,
            /// <summary>
            /// CIRCLED NUMBER FORTY ON BLACK SQUARE ㉋
            /// </summary>
            CircledNumberFortyOnBlackSquare = 0x324B,
            /// <summary>
            /// CIRCLED NUMBER FIFTY ON BLACK SQUARE ㉌
            /// </summary>
            CircledNumberFiftyOnBlackSquare = 0x324C,
            /// <summary>
            /// CIRCLED NUMBER SIXTY ON BLACK SQUARE ㉍
            /// </summary>
            CircledNumberSixtyOnBlackSquare = 0x324D,
            /// <summary>
            /// CIRCLED NUMBER SEVENTY ON BLACK SQUARE ㉎
            /// </summary>
            CircledNumberSeventyOnBlackSquare = 0x324E,
            /// <summary>
            /// CIRCLED NUMBER EIGHTY ON BLACK SQUARE ㉏
            /// </summary>
            CircledNumberEightyOnBlackSquare = 0x324F,
            /// <summary>
            /// CIRCLED NUMBER TWENTY ONE ㉑
            /// </summary>
            CircledNumberTwentyOne = 0x3251,
            /// <summary>
            /// CIRCLED NUMBER TWENTY TWO ㉒
            /// </summary>
            CircledNumberTwentyTwo = 0x3252,
            /// <summary>
            /// CIRCLED NUMBER TWENTY THREE ㉓
            /// </summary>
            CircledNumberTwentyThree = 0x3253,
            /// <summary>
            /// CIRCLED NUMBER TWENTY FOUR ㉔
            /// </summary>
            CircledNumberTwentyFour = 0x3254,
            /// <summary>
            /// CIRCLED NUMBER TWENTY FIVE ㉕
            /// </summary>
            CircledNumberTwentyFive = 0x3255,
            /// <summary>
            /// CIRCLED NUMBER TWENTY SIX ㉖
            /// </summary>
            CircledNumberTwentySix = 0x3256,
            /// <summary>
            /// CIRCLED NUMBER TWENTY SEVEN ㉗
            /// </summary>
            CircledNumberTwentySeven = 0x3257,
            /// <summary>
            /// CIRCLED NUMBER TWENTY EIGHT ㉘
            /// </summary>
            CircledNumberTwentyEight = 0x3258,
            /// <summary>
            /// CIRCLED NUMBER TWENTY NINE ㉙
            /// </summary>
            CircledNumberTwentyNine = 0x3259,
            /// <summary>
            /// CIRCLED NUMBER THIRTY ㉚
            /// </summary>
            CircledNumberThirty = 0x325A,
            /// <summary>
            /// CIRCLED NUMBER THIRTY ONE ㉛
            /// </summary>
            CircledNumberThirtyOne = 0x325B,
            /// <summary>
            /// CIRCLED NUMBER THIRTY TWO ㉜
            /// </summary>
            CircledNumberThirtyTwo = 0x325C,
            /// <summary>
            /// CIRCLED NUMBER THIRTY THREE ㉝
            /// </summary>
            CircledNumberThirtyThree = 0x325D,
            /// <summary>
            /// CIRCLED NUMBER THIRTY FOUR ㉞
            /// </summary>
            CircledNumberThirtyFour = 0x325E,
            /// <summary>
            /// CIRCLED NUMBER THIRTY FIVE ㉟
            /// </summary>
            CircledNumberThirtyFive = 0x325F,
            /// <summary>
            /// CIRCLED IDEOGRAPH ONE ㊀
            /// </summary>
            CircledIdeographOne = 0x3280,
            /// <summary>
            /// CIRCLED IDEOGRAPH TWO ㊁
            /// </summary>
            CircledIdeographTwo = 0x3281,
            /// <summary>
            /// CIRCLED IDEOGRAPH THREE ㊂
            /// </summary>
            CircledIdeographThree = 0x3282,
            /// <summary>
            /// CIRCLED IDEOGRAPH FOUR ㊃
            /// </summary>
            CircledIdeographFour = 0x3283,
            /// <summary>
            /// CIRCLED IDEOGRAPH FIVE ㊄
            /// </summary>
            CircledIdeographFive = 0x3284,
            /// <summary>
            /// CIRCLED IDEOGRAPH SIX ㊅
            /// </summary>
            CircledIdeographSix = 0x3285,
            /// <summary>
            /// CIRCLED IDEOGRAPH SEVEN ㊆
            /// </summary>
            CircledIdeographSeven = 0x3286,
            /// <summary>
            /// CIRCLED IDEOGRAPH EIGHT ㊇
            /// </summary>
            CircledIdeographEight = 0x3287,
            /// <summary>
            /// CIRCLED IDEOGRAPH NINE ㊈
            /// </summary>
            CircledIdeographNine = 0x3288,
            /// <summary>
            /// CIRCLED IDEOGRAPH TEN ㊉
            /// </summary>
            CircledIdeographTen = 0x3289,
            /// <summary>
            /// CIRCLED NUMBER THIRTY SIX ㊱
            /// </summary>
            CircledNumberThirtySix = 0x32B1,
            /// <summary>
            /// CIRCLED NUMBER THIRTY SEVEN ㊲
            /// </summary>
            CircledNumberThirtySeven = 0x32B2,
            /// <summary>
            /// CIRCLED NUMBER THIRTY EIGHT ㊳
            /// </summary>
            CircledNumberThirtyEight = 0x32B3,
            /// <summary>
            /// CIRCLED NUMBER THIRTY NINE ㊴
            /// </summary>
            CircledNumberThirtyNine = 0x32B4,
            /// <summary>
            /// CIRCLED NUMBER FORTY ㊵
            /// </summary>
            CircledNumberForty = 0x32B5,
            /// <summary>
            /// CIRCLED NUMBER FORTY ONE ㊶
            /// </summary>
            CircledNumberFortyOne = 0x32B6,
            /// <summary>
            /// CIRCLED NUMBER FORTY TWO ㊷
            /// </summary>
            CircledNumberFortyTwo = 0x32B7,
            /// <summary>
            /// CIRCLED NUMBER FORTY THREE ㊸
            /// </summary>
            CircledNumberFortyThree = 0x32B8,
            /// <summary>
            /// CIRCLED NUMBER FORTY FOUR ㊹
            /// </summary>
            CircledNumberFortyFour = 0x32B9,
            /// <summary>
            /// CIRCLED NUMBER FORTY FIVE ㊺
            /// </summary>
            CircledNumberFortyFive = 0x32BA,
            /// <summary>
            /// CIRCLED NUMBER FORTY SIX ㊻
            /// </summary>
            CircledNumberFortySix = 0x32BB,
            /// <summary>
            /// CIRCLED NUMBER FORTY SEVEN ㊼
            /// </summary>
            CircledNumberFortySeven = 0x32BC,
            /// <summary>
            /// CIRCLED NUMBER FORTY EIGHT ㊽
            /// </summary>
            CircledNumberFortyEight = 0x32BD,
            /// <summary>
            /// CIRCLED NUMBER FORTY NINE ㊾
            /// </summary>
            CircledNumberFortyNine = 0x32BE,
            /// <summary>
            /// CIRCLED NUMBER FIFTY ㊿
            /// </summary>
            CircledNumberFifty = 0x32BF
        }
    }
}
