// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static partial class MeeteiMayekExtension
    {

        /// <summary>
        /// Converts this value to a multibyte char
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string ToMultibyteChar(this MeeteiMayek.OtherLetter value)
        {
            return Char.ConvertFromUtf32((int)value);
        }

        /// <summary>
        /// Converts this value to a multibyte char
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string ToMultibyteChar(this MeeteiMayek.SpacingCombiningMark value)
        {
            return Char.ConvertFromUtf32((int)value);
        }

        /// <summary>
        /// Converts this value to a multibyte char
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string ToMultibyteChar(this MeeteiMayek.NonSpacingMark value)
        {
            return Char.ConvertFromUtf32((int)value);
        }

        /// <summary>
        /// Converts this value to a multibyte char
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string ToMultibyteChar(this MeeteiMayek.OtherPunctuation value)
        {
            return Char.ConvertFromUtf32((int)value);
        }

        /// <summary>
        /// Converts this value to a multibyte char
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static string ToMultibyteChar(this MeeteiMayek.DecimalDigitNumber value)
        {
            return Char.ConvertFromUtf32((int)value);
        }
    }
}
