// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class Rejang
    {
        public enum OtherLetter : int
        {
            /// <summary>
            /// REJANG LETTER KA ꤰ
            /// </summary>
            RejangLetterKa = 0xA930,
            /// <summary>
            /// REJANG LETTER GA ꤱ
            /// </summary>
            RejangLetterGa = 0xA931,
            /// <summary>
            /// REJANG LETTER NGA ꤲ
            /// </summary>
            RejangLetterNga = 0xA932,
            /// <summary>
            /// REJANG LETTER TA ꤳ
            /// </summary>
            RejangLetterTa = 0xA933,
            /// <summary>
            /// REJANG LETTER DA ꤴ
            /// </summary>
            RejangLetterDa = 0xA934,
            /// <summary>
            /// REJANG LETTER NA ꤵ
            /// </summary>
            RejangLetterNa = 0xA935,
            /// <summary>
            /// REJANG LETTER PA ꤶ
            /// </summary>
            RejangLetterPa = 0xA936,
            /// <summary>
            /// REJANG LETTER BA ꤷ
            /// </summary>
            RejangLetterBa = 0xA937,
            /// <summary>
            /// REJANG LETTER MA ꤸ
            /// </summary>
            RejangLetterMa = 0xA938,
            /// <summary>
            /// REJANG LETTER CA ꤹ
            /// </summary>
            RejangLetterCa = 0xA939,
            /// <summary>
            /// REJANG LETTER JA ꤺ
            /// </summary>
            RejangLetterJa = 0xA93A,
            /// <summary>
            /// REJANG LETTER NYA ꤻ
            /// </summary>
            RejangLetterNya = 0xA93B,
            /// <summary>
            /// REJANG LETTER SA ꤼ
            /// </summary>
            RejangLetterSa = 0xA93C,
            /// <summary>
            /// REJANG LETTER RA ꤽ
            /// </summary>
            RejangLetterRa = 0xA93D,
            /// <summary>
            /// REJANG LETTER LA ꤾ
            /// </summary>
            RejangLetterLa = 0xA93E,
            /// <summary>
            /// REJANG LETTER YA ꤿ
            /// </summary>
            RejangLetterYa = 0xA93F,
            /// <summary>
            /// REJANG LETTER WA ꥀ
            /// </summary>
            RejangLetterWa = 0xA940,
            /// <summary>
            /// REJANG LETTER HA ꥁ
            /// </summary>
            RejangLetterHa = 0xA941,
            /// <summary>
            /// REJANG LETTER MBA ꥂ
            /// </summary>
            RejangLetterMba = 0xA942,
            /// <summary>
            /// REJANG LETTER NGGA ꥃ
            /// </summary>
            RejangLetterNgga = 0xA943,
            /// <summary>
            /// REJANG LETTER NDA ꥄ
            /// </summary>
            RejangLetterNda = 0xA944,
            /// <summary>
            /// REJANG LETTER NYJA ꥅ
            /// </summary>
            RejangLetterNyja = 0xA945,
            /// <summary>
            /// REJANG LETTER A ꥆ
            /// </summary>
            RejangLetterA = 0xA946
        }
        public enum NonSpacingMark : int
        {
            /// <summary>
            /// REJANG VOWEL SIGN I ꥇ
            /// </summary>
            RejangVowelSignI = 0xA947,
            /// <summary>
            /// REJANG VOWEL SIGN U ꥈ
            /// </summary>
            RejangVowelSignU = 0xA948,
            /// <summary>
            /// REJANG VOWEL SIGN E ꥉ
            /// </summary>
            RejangVowelSignE = 0xA949,
            /// <summary>
            /// REJANG VOWEL SIGN AI ꥊ
            /// </summary>
            RejangVowelSignAi = 0xA94A,
            /// <summary>
            /// REJANG VOWEL SIGN O ꥋ
            /// </summary>
            RejangVowelSignO = 0xA94B,
            /// <summary>
            /// REJANG VOWEL SIGN AU ꥌ
            /// </summary>
            RejangVowelSignAu = 0xA94C,
            /// <summary>
            /// REJANG VOWEL SIGN EU ꥍ
            /// </summary>
            RejangVowelSignEu = 0xA94D,
            /// <summary>
            /// REJANG VOWEL SIGN EA ꥎ
            /// </summary>
            RejangVowelSignEa = 0xA94E,
            /// <summary>
            /// REJANG CONSONANT SIGN NG ꥏ
            /// </summary>
            RejangConsonantSignNg = 0xA94F,
            /// <summary>
            /// REJANG CONSONANT SIGN N ꥐ
            /// </summary>
            RejangConsonantSignN = 0xA950,
            /// <summary>
            /// REJANG CONSONANT SIGN R ꥑ
            /// </summary>
            RejangConsonantSignR = 0xA951
        }
        public enum SpacingCombiningMark : int
        {
            /// <summary>
            /// REJANG CONSONANT SIGN H ꥒ
            /// </summary>
            RejangConsonantSignH = 0xA952,
            /// <summary>
            /// REJANG VIRAMA ꥓
            /// </summary>
            RejangVirama = 0xA953
        }
        public enum OtherPunctuation : int
        {
            /// <summary>
            /// REJANG SECTION MARK ꥟
            /// </summary>
            RejangSectionMark = 0xA95F
        }
    }
}
