// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class CJKCompatibilityForms
    {
        public enum OtherPunctuation : int
        {
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL TWO DOT LEADER ︰
            /// </summary>
            PresentationFormForVerticalTwoDotLeader = 0xFE30,
            /// <summary>
            /// SESAME DOT ﹅
            /// </summary>
            SesameDot = 0xFE45,
            /// <summary>
            /// WHITE SESAME DOT ﹆
            /// </summary>
            WhiteSesameDot = 0xFE46,
            /// <summary>
            /// DASHED OVERLINE ﹉
            /// </summary>
            DashedOverline = 0xFE49,
            /// <summary>
            /// CENTRELINE OVERLINE ﹊
            /// </summary>
            CentrelineOverline = 0xFE4A,
            /// <summary>
            /// WAVY OVERLINE ﹋
            /// </summary>
            WavyOverline = 0xFE4B,
            /// <summary>
            /// DOUBLE WAVY OVERLINE ﹌
            /// </summary>
            DoubleWavyOverline = 0xFE4C
        }
        public enum DashPunctuation : int
        {
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL EM DASH ︱
            /// </summary>
            PresentationFormForVerticalEmDash = 0xFE31,
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL EN DASH ︲
            /// </summary>
            PresentationFormForVerticalEnDash = 0xFE32
        }
        public enum ConnectorPunctuation : int
        {
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL LOW LINE ︳
            /// </summary>
            PresentationFormForVerticalLowLine = 0xFE33,
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL WAVY LOW LINE ︴
            /// </summary>
            PresentationFormForVerticalWavyLowLine = 0xFE34,
            /// <summary>
            /// DASHED LOW LINE ﹍
            /// </summary>
            DashedLowLine = 0xFE4D,
            /// <summary>
            /// CENTRELINE LOW LINE ﹎
            /// </summary>
            CentrelineLowLine = 0xFE4E,
            /// <summary>
            /// WAVY LOW LINE ﹏
            /// </summary>
            WavyLowLine = 0xFE4F
        }
        public enum OpenPunctuation : int
        {
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL LEFT PARENTHESIS ︵
            /// </summary>
            PresentationFormForVerticalLeftParenthesis = 0xFE35,
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL LEFT CURLY BRACKET ︷
            /// </summary>
            PresentationFormForVerticalLeftCurlyBracket = 0xFE37,
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL LEFT TORTOISE SHELL BRACKET ︹
            /// </summary>
            PresentationFormForVerticalLeftTortoiseShellBracket = 0xFE39,
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL LEFT BLACK LENTICULAR BRACKET ︻
            /// </summary>
            PresentationFormForVerticalLeftBlackLenticularBracket = 0xFE3B,
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL LEFT DOUBLE ANGLE BRACKET ︽
            /// </summary>
            PresentationFormForVerticalLeftDoubleAngleBracket = 0xFE3D,
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL LEFT ANGLE BRACKET ︿
            /// </summary>
            PresentationFormForVerticalLeftAngleBracket = 0xFE3F,
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL LEFT CORNER BRACKET ﹁
            /// </summary>
            PresentationFormForVerticalLeftCornerBracket = 0xFE41,
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL LEFT WHITE CORNER BRACKET ﹃
            /// </summary>
            PresentationFormForVerticalLeftWhiteCornerBracket = 0xFE43,
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL LEFT SQUARE BRACKET ﹇
            /// </summary>
            PresentationFormForVerticalLeftSquareBracket = 0xFE47
        }
        public enum ClosePunctuation : int
        {
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL RIGHT PARENTHESIS ︶
            /// </summary>
            PresentationFormForVerticalRightParenthesis = 0xFE36,
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL RIGHT CURLY BRACKET ︸
            /// </summary>
            PresentationFormForVerticalRightCurlyBracket = 0xFE38,
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL RIGHT TORTOISE SHELL BRACKET ︺
            /// </summary>
            PresentationFormForVerticalRightTortoiseShellBracket = 0xFE3A,
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL RIGHT BLACK LENTICULAR BRACKET ︼
            /// </summary>
            PresentationFormForVerticalRightBlackLenticularBracket = 0xFE3C,
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL RIGHT DOUBLE ANGLE BRACKET ︾
            /// </summary>
            PresentationFormForVerticalRightDoubleAngleBracket = 0xFE3E,
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL RIGHT ANGLE BRACKET ﹀
            /// </summary>
            PresentationFormForVerticalRightAngleBracket = 0xFE40,
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL RIGHT CORNER BRACKET ﹂
            /// </summary>
            PresentationFormForVerticalRightCornerBracket = 0xFE42,
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL RIGHT WHITE CORNER BRACKET ﹄
            /// </summary>
            PresentationFormForVerticalRightWhiteCornerBracket = 0xFE44,
            /// <summary>
            /// PRESENTATION FORM FOR VERTICAL RIGHT SQUARE BRACKET ﹈
            /// </summary>
            PresentationFormForVerticalRightSquareBracket = 0xFE48
        }
    }
}
