// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class ByzantineMusicalSymbols
    {
        public enum OtherSymbol : int
        {
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PSILI 𝀀
            /// </summary>
            ByzantineMusicalSymbolPsili = 0x1D000,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DASEIA 𝀁
            /// </summary>
            ByzantineMusicalSymbolDaseia = 0x1D001,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PERISPOMENI 𝀂
            /// </summary>
            ByzantineMusicalSymbolPerispomeni = 0x1D002,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL OXEIA EKFONITIKON 𝀃
            /// </summary>
            ByzantineMusicalSymbolOxeiaEkfonitikon = 0x1D003,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL OXEIA DIPLI 𝀄
            /// </summary>
            ByzantineMusicalSymbolOxeiaDipli = 0x1D004,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL VAREIA EKFONITIKON 𝀅
            /// </summary>
            ByzantineMusicalSymbolVareiaEkfonitikon = 0x1D005,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL VAREIA DIPLI 𝀆
            /// </summary>
            ByzantineMusicalSymbolVareiaDipli = 0x1D006,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KATHISTI 𝀇
            /// </summary>
            ByzantineMusicalSymbolKathisti = 0x1D007,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL SYRMATIKI 𝀈
            /// </summary>
            ByzantineMusicalSymbolSyrmatiki = 0x1D008,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PARAKLITIKI 𝀉
            /// </summary>
            ByzantineMusicalSymbolParaklitiki = 0x1D009,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL YPOKRISIS 𝀊
            /// </summary>
            ByzantineMusicalSymbolYpokrisis = 0x1D00A,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL YPOKRISIS DIPLI 𝀋
            /// </summary>
            ByzantineMusicalSymbolYpokrisisDipli = 0x1D00B,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KREMASTI 𝀌
            /// </summary>
            ByzantineMusicalSymbolKremasti = 0x1D00C,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL APESO EKFONITIKON 𝀍
            /// </summary>
            ByzantineMusicalSymbolApesoEkfonitikon = 0x1D00D,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL EXO EKFONITIKON 𝀎
            /// </summary>
            ByzantineMusicalSymbolExoEkfonitikon = 0x1D00E,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL TELEIA 𝀏
            /// </summary>
            ByzantineMusicalSymbolTeleia = 0x1D00F,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KENTIMATA 𝀐
            /// </summary>
            ByzantineMusicalSymbolKentimata = 0x1D010,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL APOSTROFOS 𝀑
            /// </summary>
            ByzantineMusicalSymbolApostrofos = 0x1D011,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL APOSTROFOS DIPLI 𝀒
            /// </summary>
            ByzantineMusicalSymbolApostrofosDipli = 0x1D012,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL SYNEVMA 𝀓
            /// </summary>
            ByzantineMusicalSymbolSynevma = 0x1D013,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL THITA 𝀔
            /// </summary>
            ByzantineMusicalSymbolThita = 0x1D014,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL OLIGON ARCHAION 𝀕
            /// </summary>
            ByzantineMusicalSymbolOligonArchaion = 0x1D015,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL GORGON ARCHAION 𝀖
            /// </summary>
            ByzantineMusicalSymbolGorgonArchaion = 0x1D016,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PSILON 𝀗
            /// </summary>
            ByzantineMusicalSymbolPsilon = 0x1D017,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL CHAMILON 𝀘
            /// </summary>
            ByzantineMusicalSymbolChamilon = 0x1D018,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL VATHY 𝀙
            /// </summary>
            ByzantineMusicalSymbolVathy = 0x1D019,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ISON ARCHAION 𝀚
            /// </summary>
            ByzantineMusicalSymbolIsonArchaion = 0x1D01A,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KENTIMA ARCHAION 𝀛
            /// </summary>
            ByzantineMusicalSymbolKentimaArchaion = 0x1D01B,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KENTIMATA ARCHAION 𝀜
            /// </summary>
            ByzantineMusicalSymbolKentimataArchaion = 0x1D01C,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL SAXIMATA 𝀝
            /// </summary>
            ByzantineMusicalSymbolSaximata = 0x1D01D,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PARICHON 𝀞
            /// </summary>
            ByzantineMusicalSymbolParichon = 0x1D01E,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL STAVROS APODEXIA 𝀟
            /// </summary>
            ByzantineMusicalSymbolStavrosApodexia = 0x1D01F,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL OXEIAI ARCHAION 𝀠
            /// </summary>
            ByzantineMusicalSymbolOxeiaiArchaion = 0x1D020,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL VAREIAI ARCHAION 𝀡
            /// </summary>
            ByzantineMusicalSymbolVareiaiArchaion = 0x1D021,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL APODERMA ARCHAION 𝀢
            /// </summary>
            ByzantineMusicalSymbolApodermaArchaion = 0x1D022,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL APOTHEMA 𝀣
            /// </summary>
            ByzantineMusicalSymbolApothema = 0x1D023,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KLASMA 𝀤
            /// </summary>
            ByzantineMusicalSymbolKlasma = 0x1D024,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL REVMA 𝀥
            /// </summary>
            ByzantineMusicalSymbolRevma = 0x1D025,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PIASMA ARCHAION 𝀦
            /// </summary>
            ByzantineMusicalSymbolPiasmaArchaion = 0x1D026,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL TINAGMA 𝀧
            /// </summary>
            ByzantineMusicalSymbolTinagma = 0x1D027,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ANATRICHISMA 𝀨
            /// </summary>
            ByzantineMusicalSymbolAnatrichisma = 0x1D028,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL SEISMA 𝀩
            /// </summary>
            ByzantineMusicalSymbolSeisma = 0x1D029,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL SYNAGMA ARCHAION 𝀪
            /// </summary>
            ByzantineMusicalSymbolSynagmaArchaion = 0x1D02A,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL SYNAGMA META STAVROU 𝀫
            /// </summary>
            ByzantineMusicalSymbolSynagmaMetaStavrou = 0x1D02B,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL OYRANISMA ARCHAION 𝀬
            /// </summary>
            ByzantineMusicalSymbolOyranismaArchaion = 0x1D02C,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL THEMA 𝀭
            /// </summary>
            ByzantineMusicalSymbolThema = 0x1D02D,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL LEMOI 𝀮
            /// </summary>
            ByzantineMusicalSymbolLemoi = 0x1D02E,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DYO 𝀯
            /// </summary>
            ByzantineMusicalSymbolDyo = 0x1D02F,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL TRIA 𝀰
            /// </summary>
            ByzantineMusicalSymbolTria = 0x1D030,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL TESSERA 𝀱
            /// </summary>
            ByzantineMusicalSymbolTessera = 0x1D031,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KRATIMATA 𝀲
            /// </summary>
            ByzantineMusicalSymbolKratimata = 0x1D032,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL APESO EXO NEO 𝀳
            /// </summary>
            ByzantineMusicalSymbolApesoExoNeo = 0x1D033,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FTHORA ARCHAION 𝀴
            /// </summary>
            ByzantineMusicalSymbolFthoraArchaion = 0x1D034,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL IMIFTHORA 𝀵
            /// </summary>
            ByzantineMusicalSymbolImifthora = 0x1D035,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL TROMIKON ARCHAION 𝀶
            /// </summary>
            ByzantineMusicalSymbolTromikonArchaion = 0x1D036,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KATAVA TROMIKON 𝀷
            /// </summary>
            ByzantineMusicalSymbolKatavaTromikon = 0x1D037,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PELASTON 𝀸
            /// </summary>
            ByzantineMusicalSymbolPelaston = 0x1D038,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PSIFISTON 𝀹
            /// </summary>
            ByzantineMusicalSymbolPsifiston = 0x1D039,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KONTEVMA 𝀺
            /// </summary>
            ByzantineMusicalSymbolKontevma = 0x1D03A,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL CHOREVMA ARCHAION 𝀻
            /// </summary>
            ByzantineMusicalSymbolChorevmaArchaion = 0x1D03B,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL RAPISMA 𝀼
            /// </summary>
            ByzantineMusicalSymbolRapisma = 0x1D03C,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PARAKALESMA ARCHAION 𝀽
            /// </summary>
            ByzantineMusicalSymbolParakalesmaArchaion = 0x1D03D,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PARAKLITIKI ARCHAION 𝀾
            /// </summary>
            ByzantineMusicalSymbolParaklitikiArchaion = 0x1D03E,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ICHADIN 𝀿
            /// </summary>
            ByzantineMusicalSymbolIchadin = 0x1D03F,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL NANA 𝁀
            /// </summary>
            ByzantineMusicalSymbolNana = 0x1D040,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PETASMA 𝁁
            /// </summary>
            ByzantineMusicalSymbolPetasma = 0x1D041,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KONTEVMA ALLO 𝁂
            /// </summary>
            ByzantineMusicalSymbolKontevmaAllo = 0x1D042,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL TROMIKON ALLO 𝁃
            /// </summary>
            ByzantineMusicalSymbolTromikonAllo = 0x1D043,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL STRAGGISMATA 𝁄
            /// </summary>
            ByzantineMusicalSymbolStraggismata = 0x1D044,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL GRONTHISMATA 𝁅
            /// </summary>
            ByzantineMusicalSymbolGronthismata = 0x1D045,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ISON NEO 𝁆
            /// </summary>
            ByzantineMusicalSymbolIsonNeo = 0x1D046,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL OLIGON NEO 𝁇
            /// </summary>
            ByzantineMusicalSymbolOligonNeo = 0x1D047,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL OXEIA NEO 𝁈
            /// </summary>
            ByzantineMusicalSymbolOxeiaNeo = 0x1D048,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PETASTI 𝁉
            /// </summary>
            ByzantineMusicalSymbolPetasti = 0x1D049,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KOUFISMA 𝁊
            /// </summary>
            ByzantineMusicalSymbolKoufisma = 0x1D04A,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PETASTOKOUFISMA 𝁋
            /// </summary>
            ByzantineMusicalSymbolPetastokoufisma = 0x1D04B,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KRATIMOKOUFISMA 𝁌
            /// </summary>
            ByzantineMusicalSymbolKratimokoufisma = 0x1D04C,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PELASTON NEO 𝁍
            /// </summary>
            ByzantineMusicalSymbolPelastonNeo = 0x1D04D,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KENTIMATA NEO ANO 𝁎
            /// </summary>
            ByzantineMusicalSymbolKentimataNeoAno = 0x1D04E,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KENTIMA NEO ANO 𝁏
            /// </summary>
            ByzantineMusicalSymbolKentimaNeoAno = 0x1D04F,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL YPSILI 𝁐
            /// </summary>
            ByzantineMusicalSymbolYpsili = 0x1D050,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL APOSTROFOS NEO 𝁑
            /// </summary>
            ByzantineMusicalSymbolApostrofosNeo = 0x1D051,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL APOSTROFOI SYNDESMOS NEO 𝁒
            /// </summary>
            ByzantineMusicalSymbolApostrofoiSyndesmosNeo = 0x1D052,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL YPORROI 𝁓
            /// </summary>
            ByzantineMusicalSymbolYporroi = 0x1D053,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KRATIMOYPORROON 𝁔
            /// </summary>
            ByzantineMusicalSymbolKratimoyporroon = 0x1D054,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ELAFRON 𝁕
            /// </summary>
            ByzantineMusicalSymbolElafron = 0x1D055,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL CHAMILI 𝁖
            /// </summary>
            ByzantineMusicalSymbolChamili = 0x1D056,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL MIKRON ISON 𝁗
            /// </summary>
            ByzantineMusicalSymbolMikronIson = 0x1D057,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL VAREIA NEO 𝁘
            /// </summary>
            ByzantineMusicalSymbolVareiaNeo = 0x1D058,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PIASMA NEO 𝁙
            /// </summary>
            ByzantineMusicalSymbolPiasmaNeo = 0x1D059,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PSIFISTON NEO 𝁚
            /// </summary>
            ByzantineMusicalSymbolPsifistonNeo = 0x1D05A,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL OMALON 𝁛
            /// </summary>
            ByzantineMusicalSymbolOmalon = 0x1D05B,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ANTIKENOMA 𝁜
            /// </summary>
            ByzantineMusicalSymbolAntikenoma = 0x1D05C,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL LYGISMA 𝁝
            /// </summary>
            ByzantineMusicalSymbolLygisma = 0x1D05D,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PARAKLITIKI NEO 𝁞
            /// </summary>
            ByzantineMusicalSymbolParaklitikiNeo = 0x1D05E,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PARAKALESMA NEO 𝁟
            /// </summary>
            ByzantineMusicalSymbolParakalesmaNeo = 0x1D05F,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ETERON PARAKALESMA 𝁠
            /// </summary>
            ByzantineMusicalSymbolEteronParakalesma = 0x1D060,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KYLISMA 𝁡
            /// </summary>
            ByzantineMusicalSymbolKylisma = 0x1D061,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ANTIKENOKYLISMA 𝁢
            /// </summary>
            ByzantineMusicalSymbolAntikenokylisma = 0x1D062,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL TROMIKON NEO 𝁣
            /// </summary>
            ByzantineMusicalSymbolTromikonNeo = 0x1D063,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL EKSTREPTON 𝁤
            /// </summary>
            ByzantineMusicalSymbolEkstrepton = 0x1D064,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL SYNAGMA NEO 𝁥
            /// </summary>
            ByzantineMusicalSymbolSynagmaNeo = 0x1D065,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL SYRMA 𝁦
            /// </summary>
            ByzantineMusicalSymbolSyrma = 0x1D066,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL CHOREVMA NEO 𝁧
            /// </summary>
            ByzantineMusicalSymbolChorevmaNeo = 0x1D067,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL EPEGERMA 𝁨
            /// </summary>
            ByzantineMusicalSymbolEpegerma = 0x1D068,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL SEISMA NEO 𝁩
            /// </summary>
            ByzantineMusicalSymbolSeismaNeo = 0x1D069,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL XIRON KLASMA 𝁪
            /// </summary>
            ByzantineMusicalSymbolXironKlasma = 0x1D06A,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL TROMIKOPSIFISTON 𝁫
            /// </summary>
            ByzantineMusicalSymbolTromikopsifiston = 0x1D06B,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PSIFISTOLYGISMA 𝁬
            /// </summary>
            ByzantineMusicalSymbolPsifistolygisma = 0x1D06C,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL TROMIKOLYGISMA 𝁭
            /// </summary>
            ByzantineMusicalSymbolTromikolygisma = 0x1D06D,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL TROMIKOPARAKALESMA 𝁮
            /// </summary>
            ByzantineMusicalSymbolTromikoparakalesma = 0x1D06E,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PSIFISTOPARAKALESMA 𝁯
            /// </summary>
            ByzantineMusicalSymbolPsifistoparakalesma = 0x1D06F,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL TROMIKOSYNAGMA 𝁰
            /// </summary>
            ByzantineMusicalSymbolTromikosynagma = 0x1D070,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL PSIFISTOSYNAGMA 𝁱
            /// </summary>
            ByzantineMusicalSymbolPsifistosynagma = 0x1D071,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL GORGOSYNTHETON 𝁲
            /// </summary>
            ByzantineMusicalSymbolGorgosyntheton = 0x1D072,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ARGOSYNTHETON 𝁳
            /// </summary>
            ByzantineMusicalSymbolArgosyntheton = 0x1D073,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ETERON ARGOSYNTHETON 𝁴
            /// </summary>
            ByzantineMusicalSymbolEteronArgosyntheton = 0x1D074,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL OYRANISMA NEO 𝁵
            /// </summary>
            ByzantineMusicalSymbolOyranismaNeo = 0x1D075,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL THEMATISMOS ESO 𝁶
            /// </summary>
            ByzantineMusicalSymbolThematismosEso = 0x1D076,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL THEMATISMOS EXO 𝁷
            /// </summary>
            ByzantineMusicalSymbolThematismosExo = 0x1D077,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL THEMA APLOUN 𝁸
            /// </summary>
            ByzantineMusicalSymbolThemaAploun = 0x1D078,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL THES KAI APOTHES 𝁹
            /// </summary>
            ByzantineMusicalSymbolThesKaiApothes = 0x1D079,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KATAVASMA 𝁺
            /// </summary>
            ByzantineMusicalSymbolKatavasma = 0x1D07A,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ENDOFONON 𝁻
            /// </summary>
            ByzantineMusicalSymbolEndofonon = 0x1D07B,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL YFEN KATO 𝁼
            /// </summary>
            ByzantineMusicalSymbolYfenKato = 0x1D07C,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL YFEN ANO 𝁽
            /// </summary>
            ByzantineMusicalSymbolYfenAno = 0x1D07D,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL STAVROS 𝁾
            /// </summary>
            ByzantineMusicalSymbolStavros = 0x1D07E,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KLASMA ANO 𝁿
            /// </summary>
            ByzantineMusicalSymbolKlasmaAno = 0x1D07F,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DIPLI ARCHAION 𝂀
            /// </summary>
            ByzantineMusicalSymbolDipliArchaion = 0x1D080,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KRATIMA ARCHAION 𝂁
            /// </summary>
            ByzantineMusicalSymbolKratimaArchaion = 0x1D081,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KRATIMA ALLO 𝂂
            /// </summary>
            ByzantineMusicalSymbolKratimaAllo = 0x1D082,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KRATIMA NEO 𝂃
            /// </summary>
            ByzantineMusicalSymbolKratimaNeo = 0x1D083,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL APODERMA NEO 𝂄
            /// </summary>
            ByzantineMusicalSymbolApodermaNeo = 0x1D084,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL APLI 𝂅
            /// </summary>
            ByzantineMusicalSymbolApli = 0x1D085,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DIPLI 𝂆
            /// </summary>
            ByzantineMusicalSymbolDipli = 0x1D086,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL TRIPLI 𝂇
            /// </summary>
            ByzantineMusicalSymbolTripli = 0x1D087,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL TETRAPLI 𝂈
            /// </summary>
            ByzantineMusicalSymbolTetrapli = 0x1D088,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KORONIS 𝂉
            /// </summary>
            ByzantineMusicalSymbolKoronis = 0x1D089,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL LEIMMA ENOS CHRONOU 𝂊
            /// </summary>
            ByzantineMusicalSymbolLeimmaEnosChronou = 0x1D08A,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL LEIMMA DYO CHRONON 𝂋
            /// </summary>
            ByzantineMusicalSymbolLeimmaDyoChronon = 0x1D08B,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL LEIMMA TRION CHRONON 𝂌
            /// </summary>
            ByzantineMusicalSymbolLeimmaTrionChronon = 0x1D08C,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL LEIMMA TESSARON CHRONON 𝂍
            /// </summary>
            ByzantineMusicalSymbolLeimmaTessaronChronon = 0x1D08D,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL LEIMMA IMISEOS CHRONOU 𝂎
            /// </summary>
            ByzantineMusicalSymbolLeimmaImiseosChronou = 0x1D08E,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL GORGON NEO ANO 𝂏
            /// </summary>
            ByzantineMusicalSymbolGorgonNeoAno = 0x1D08F,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL GORGON PARESTIGMENON ARISTERA 𝂐
            /// </summary>
            ByzantineMusicalSymbolGorgonParestigmenonAristera = 0x1D090,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL GORGON PARESTIGMENON DEXIA 𝂑
            /// </summary>
            ByzantineMusicalSymbolGorgonParestigmenonDexia = 0x1D091,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DIGORGON 𝂒
            /// </summary>
            ByzantineMusicalSymbolDigorgon = 0x1D092,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DIGORGON PARESTIGMENON ARISTERA KATO 𝂓
            /// </summary>
            ByzantineMusicalSymbolDigorgonParestigmenonAristeraKato = 0x1D093,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DIGORGON PARESTIGMENON ARISTERA ANO 𝂔
            /// </summary>
            ByzantineMusicalSymbolDigorgonParestigmenonAristeraAno = 0x1D094,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DIGORGON PARESTIGMENON DEXIA 𝂕
            /// </summary>
            ByzantineMusicalSymbolDigorgonParestigmenonDexia = 0x1D095,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL TRIGORGON 𝂖
            /// </summary>
            ByzantineMusicalSymbolTrigorgon = 0x1D096,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ARGON 𝂗
            /// </summary>
            ByzantineMusicalSymbolArgon = 0x1D097,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL IMIDIARGON 𝂘
            /// </summary>
            ByzantineMusicalSymbolImidiargon = 0x1D098,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DIARGON 𝂙
            /// </summary>
            ByzantineMusicalSymbolDiargon = 0x1D099,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL AGOGI POLI ARGI 𝂚
            /// </summary>
            ByzantineMusicalSymbolAgogiPoliArgi = 0x1D09A,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL AGOGI ARGOTERI 𝂛
            /// </summary>
            ByzantineMusicalSymbolAgogiArgoteri = 0x1D09B,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL AGOGI ARGI 𝂜
            /// </summary>
            ByzantineMusicalSymbolAgogiArgi = 0x1D09C,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL AGOGI METRIA 𝂝
            /// </summary>
            ByzantineMusicalSymbolAgogiMetria = 0x1D09D,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL AGOGI MESI 𝂞
            /// </summary>
            ByzantineMusicalSymbolAgogiMesi = 0x1D09E,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL AGOGI GORGI 𝂟
            /// </summary>
            ByzantineMusicalSymbolAgogiGorgi = 0x1D09F,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL AGOGI GORGOTERI 𝂠
            /// </summary>
            ByzantineMusicalSymbolAgogiGorgoteri = 0x1D0A0,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL AGOGI POLI GORGI 𝂡
            /// </summary>
            ByzantineMusicalSymbolAgogiPoliGorgi = 0x1D0A1,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL MARTYRIA PROTOS ICHOS 𝂢
            /// </summary>
            ByzantineMusicalSymbolMartyriaProtosIchos = 0x1D0A2,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL MARTYRIA ALLI PROTOS ICHOS 𝂣
            /// </summary>
            ByzantineMusicalSymbolMartyriaAlliProtosIchos = 0x1D0A3,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL MARTYRIA DEYTEROS ICHOS 𝂤
            /// </summary>
            ByzantineMusicalSymbolMartyriaDeyterosIchos = 0x1D0A4,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL MARTYRIA ALLI DEYTEROS ICHOS 𝂥
            /// </summary>
            ByzantineMusicalSymbolMartyriaAlliDeyterosIchos = 0x1D0A5,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL MARTYRIA TRITOS ICHOS 𝂦
            /// </summary>
            ByzantineMusicalSymbolMartyriaTritosIchos = 0x1D0A6,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL MARTYRIA TRIFONIAS 𝂧
            /// </summary>
            ByzantineMusicalSymbolMartyriaTrifonias = 0x1D0A7,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL MARTYRIA TETARTOS ICHOS 𝂨
            /// </summary>
            ByzantineMusicalSymbolMartyriaTetartosIchos = 0x1D0A8,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL MARTYRIA TETARTOS LEGETOS ICHOS 𝂩
            /// </summary>
            ByzantineMusicalSymbolMartyriaTetartosLegetosIchos = 0x1D0A9,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL MARTYRIA LEGETOS ICHOS 𝂪
            /// </summary>
            ByzantineMusicalSymbolMartyriaLegetosIchos = 0x1D0AA,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL MARTYRIA PLAGIOS ICHOS 𝂫
            /// </summary>
            ByzantineMusicalSymbolMartyriaPlagiosIchos = 0x1D0AB,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ISAKIA TELOUS ICHIMATOS 𝂬
            /// </summary>
            ByzantineMusicalSymbolIsakiaTelousIchimatos = 0x1D0AC,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL APOSTROFOI TELOUS ICHIMATOS 𝂭
            /// </summary>
            ByzantineMusicalSymbolApostrofoiTelousIchimatos = 0x1D0AD,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FANEROSIS TETRAFONIAS 𝂮
            /// </summary>
            ByzantineMusicalSymbolFanerosisTetrafonias = 0x1D0AE,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FANEROSIS MONOFONIAS 𝂯
            /// </summary>
            ByzantineMusicalSymbolFanerosisMonofonias = 0x1D0AF,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FANEROSIS DIFONIAS 𝂰
            /// </summary>
            ByzantineMusicalSymbolFanerosisDifonias = 0x1D0B0,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL MARTYRIA VARYS ICHOS 𝂱
            /// </summary>
            ByzantineMusicalSymbolMartyriaVarysIchos = 0x1D0B1,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL MARTYRIA PROTOVARYS ICHOS 𝂲
            /// </summary>
            ByzantineMusicalSymbolMartyriaProtovarysIchos = 0x1D0B2,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL MARTYRIA PLAGIOS TETARTOS ICHOS 𝂳
            /// </summary>
            ByzantineMusicalSymbolMartyriaPlagiosTetartosIchos = 0x1D0B3,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL GORTHMIKON N APLOUN 𝂴
            /// </summary>
            ByzantineMusicalSymbolGorthmikonNAploun = 0x1D0B4,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL GORTHMIKON N DIPLOUN 𝂵
            /// </summary>
            ByzantineMusicalSymbolGorthmikonNDiploun = 0x1D0B5,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ENARXIS KAI FTHORA VOU 𝂶
            /// </summary>
            ByzantineMusicalSymbolEnarxisKaiFthoraVou = 0x1D0B6,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL IMIFONON 𝂷
            /// </summary>
            ByzantineMusicalSymbolImifonon = 0x1D0B7,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL IMIFTHORON 𝂸
            /// </summary>
            ByzantineMusicalSymbolImifthoron = 0x1D0B8,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FTHORA ARCHAION DEYTEROU ICHOU 𝂹
            /// </summary>
            ByzantineMusicalSymbolFthoraArchaionDeyterouIchou = 0x1D0B9,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FTHORA DIATONIKI PA 𝂺
            /// </summary>
            ByzantineMusicalSymbolFthoraDiatonikiPa = 0x1D0BA,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FTHORA DIATONIKI NANA 𝂻
            /// </summary>
            ByzantineMusicalSymbolFthoraDiatonikiNana = 0x1D0BB,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FTHORA NAOS ICHOS 𝂼
            /// </summary>
            ByzantineMusicalSymbolFthoraNaosIchos = 0x1D0BC,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FTHORA DIATONIKI DI 𝂽
            /// </summary>
            ByzantineMusicalSymbolFthoraDiatonikiDi = 0x1D0BD,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FTHORA SKLIRON DIATONON DI 𝂾
            /// </summary>
            ByzantineMusicalSymbolFthoraSklironDiatononDi = 0x1D0BE,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FTHORA DIATONIKI KE 𝂿
            /// </summary>
            ByzantineMusicalSymbolFthoraDiatonikiKe = 0x1D0BF,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FTHORA DIATONIKI ZO 𝃀
            /// </summary>
            ByzantineMusicalSymbolFthoraDiatonikiZo = 0x1D0C0,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FTHORA DIATONIKI NI KATO 𝃁
            /// </summary>
            ByzantineMusicalSymbolFthoraDiatonikiNiKato = 0x1D0C1,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FTHORA DIATONIKI NI ANO 𝃂
            /// </summary>
            ByzantineMusicalSymbolFthoraDiatonikiNiAno = 0x1D0C2,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FTHORA MALAKON CHROMA DIFONIAS 𝃃
            /// </summary>
            ByzantineMusicalSymbolFthoraMalakonChromaDifonias = 0x1D0C3,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FTHORA MALAKON CHROMA MONOFONIAS 𝃄
            /// </summary>
            ByzantineMusicalSymbolFthoraMalakonChromaMonofonias = 0x1D0C4,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FHTORA SKLIRON CHROMA VASIS 𝃅
            /// </summary>
            ByzantineMusicalSymbolFhtoraSklironChromaVasis = 0x1D0C5,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FTHORA SKLIRON CHROMA SYNAFI 𝃆
            /// </summary>
            ByzantineMusicalSymbolFthoraSklironChromaSynafi = 0x1D0C6,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FTHORA NENANO 𝃇
            /// </summary>
            ByzantineMusicalSymbolFthoraNenano = 0x1D0C7,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL CHROA ZYGOS 𝃈
            /// </summary>
            ByzantineMusicalSymbolChroaZygos = 0x1D0C8,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL CHROA KLITON 𝃉
            /// </summary>
            ByzantineMusicalSymbolChroaKliton = 0x1D0C9,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL CHROA SPATHI 𝃊
            /// </summary>
            ByzantineMusicalSymbolChroaSpathi = 0x1D0CA,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FTHORA I YFESIS TETARTIMORION 𝃋
            /// </summary>
            ByzantineMusicalSymbolFthoraIYfesisTetartimorion = 0x1D0CB,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL FTHORA ENARMONIOS ANTIFONIA 𝃌
            /// </summary>
            ByzantineMusicalSymbolFthoraEnarmoniosAntifonia = 0x1D0CC,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL YFESIS TRITIMORION 𝃍
            /// </summary>
            ByzantineMusicalSymbolYfesisTritimorion = 0x1D0CD,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DIESIS TRITIMORION 𝃎
            /// </summary>
            ByzantineMusicalSymbolDiesisTritimorion = 0x1D0CE,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DIESIS TETARTIMORION 𝃏
            /// </summary>
            ByzantineMusicalSymbolDiesisTetartimorion = 0x1D0CF,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DIESIS APLI DYO DODEKATA 𝃐
            /// </summary>
            ByzantineMusicalSymbolDiesisApliDyoDodekata = 0x1D0D0,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DIESIS MONOGRAMMOS TESSERA DODEKATA 𝃑
            /// </summary>
            ByzantineMusicalSymbolDiesisMonogrammosTesseraDodekata = 0x1D0D1,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DIESIS DIGRAMMOS EX DODEKATA 𝃒
            /// </summary>
            ByzantineMusicalSymbolDiesisDigrammosExDodekata = 0x1D0D2,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DIESIS TRIGRAMMOS OKTO DODEKATA 𝃓
            /// </summary>
            ByzantineMusicalSymbolDiesisTrigrammosOktoDodekata = 0x1D0D3,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL YFESIS APLI DYO DODEKATA 𝃔
            /// </summary>
            ByzantineMusicalSymbolYfesisApliDyoDodekata = 0x1D0D4,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL YFESIS MONOGRAMMOS TESSERA DODEKATA 𝃕
            /// </summary>
            ByzantineMusicalSymbolYfesisMonogrammosTesseraDodekata = 0x1D0D5,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL YFESIS DIGRAMMOS EX DODEKATA 𝃖
            /// </summary>
            ByzantineMusicalSymbolYfesisDigrammosExDodekata = 0x1D0D6,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL YFESIS TRIGRAMMOS OKTO DODEKATA 𝃗
            /// </summary>
            ByzantineMusicalSymbolYfesisTrigrammosOktoDodekata = 0x1D0D7,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL GENIKI DIESIS 𝃘
            /// </summary>
            ByzantineMusicalSymbolGenikiDiesis = 0x1D0D8,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL GENIKI YFESIS 𝃙
            /// </summary>
            ByzantineMusicalSymbolGenikiYfesis = 0x1D0D9,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DIASTOLI APLI MIKRI 𝃚
            /// </summary>
            ByzantineMusicalSymbolDiastoliApliMikri = 0x1D0DA,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DIASTOLI APLI MEGALI 𝃛
            /// </summary>
            ByzantineMusicalSymbolDiastoliApliMegali = 0x1D0DB,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DIASTOLI DIPLI 𝃜
            /// </summary>
            ByzantineMusicalSymbolDiastoliDipli = 0x1D0DC,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DIASTOLI THESEOS 𝃝
            /// </summary>
            ByzantineMusicalSymbolDiastoliTheseos = 0x1D0DD,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL SIMANSIS THESEOS 𝃞
            /// </summary>
            ByzantineMusicalSymbolSimansisTheseos = 0x1D0DE,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL SIMANSIS THESEOS DISIMOU 𝃟
            /// </summary>
            ByzantineMusicalSymbolSimansisTheseosDisimou = 0x1D0DF,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL SIMANSIS THESEOS TRISIMOU 𝃠
            /// </summary>
            ByzantineMusicalSymbolSimansisTheseosTrisimou = 0x1D0E0,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL SIMANSIS THESEOS TETRASIMOU 𝃡
            /// </summary>
            ByzantineMusicalSymbolSimansisTheseosTetrasimou = 0x1D0E1,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL SIMANSIS ARSEOS 𝃢
            /// </summary>
            ByzantineMusicalSymbolSimansisArseos = 0x1D0E2,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL SIMANSIS ARSEOS DISIMOU 𝃣
            /// </summary>
            ByzantineMusicalSymbolSimansisArseosDisimou = 0x1D0E3,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL SIMANSIS ARSEOS TRISIMOU 𝃤
            /// </summary>
            ByzantineMusicalSymbolSimansisArseosTrisimou = 0x1D0E4,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL SIMANSIS ARSEOS TETRASIMOU 𝃥
            /// </summary>
            ByzantineMusicalSymbolSimansisArseosTetrasimou = 0x1D0E5,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DIGRAMMA GG 𝃦
            /// </summary>
            ByzantineMusicalSymbolDigrammaGg = 0x1D0E6,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL DIFTOGGOS OU 𝃧
            /// </summary>
            ByzantineMusicalSymbolDiftoggosOu = 0x1D0E7,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL STIGMA 𝃨
            /// </summary>
            ByzantineMusicalSymbolStigma = 0x1D0E8,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ARKTIKO PA 𝃩
            /// </summary>
            ByzantineMusicalSymbolArktikoPa = 0x1D0E9,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ARKTIKO VOU 𝃪
            /// </summary>
            ByzantineMusicalSymbolArktikoVou = 0x1D0EA,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ARKTIKO GA 𝃫
            /// </summary>
            ByzantineMusicalSymbolArktikoGa = 0x1D0EB,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ARKTIKO DI 𝃬
            /// </summary>
            ByzantineMusicalSymbolArktikoDi = 0x1D0EC,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ARKTIKO KE 𝃭
            /// </summary>
            ByzantineMusicalSymbolArktikoKe = 0x1D0ED,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ARKTIKO ZO 𝃮
            /// </summary>
            ByzantineMusicalSymbolArktikoZo = 0x1D0EE,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL ARKTIKO NI 𝃯
            /// </summary>
            ByzantineMusicalSymbolArktikoNi = 0x1D0EF,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KENTIMATA NEO MESO 𝃰
            /// </summary>
            ByzantineMusicalSymbolKentimataNeoMeso = 0x1D0F0,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KENTIMA NEO MESO 𝃱
            /// </summary>
            ByzantineMusicalSymbolKentimaNeoMeso = 0x1D0F1,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KENTIMATA NEO KATO 𝃲
            /// </summary>
            ByzantineMusicalSymbolKentimataNeoKato = 0x1D0F2,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KENTIMA NEO KATO 𝃳
            /// </summary>
            ByzantineMusicalSymbolKentimaNeoKato = 0x1D0F3,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL KLASMA KATO 𝃴
            /// </summary>
            ByzantineMusicalSymbolKlasmaKato = 0x1D0F4,
            /// <summary>
            /// BYZANTINE MUSICAL SYMBOL GORGON NEO KATO 𝃵
            /// </summary>
            ByzantineMusicalSymbolGorgonNeoKato = 0x1D0F5
        }
    }
}
