// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class Lydian
    {
        public enum OtherLetter : int
        {
            /// <summary>
            /// LYDIAN LETTER A 𐤠
            /// </summary>
            LydianLetterA = 0x10920,
            /// <summary>
            /// LYDIAN LETTER B 𐤡
            /// </summary>
            LydianLetterB = 0x10921,
            /// <summary>
            /// LYDIAN LETTER G 𐤢
            /// </summary>
            LydianLetterG = 0x10922,
            /// <summary>
            /// LYDIAN LETTER D 𐤣
            /// </summary>
            LydianLetterD = 0x10923,
            /// <summary>
            /// LYDIAN LETTER E 𐤤
            /// </summary>
            LydianLetterE = 0x10924,
            /// <summary>
            /// LYDIAN LETTER V 𐤥
            /// </summary>
            LydianLetterV = 0x10925,
            /// <summary>
            /// LYDIAN LETTER I 𐤦
            /// </summary>
            LydianLetterI = 0x10926,
            /// <summary>
            /// LYDIAN LETTER Y 𐤧
            /// </summary>
            LydianLetterY = 0x10927,
            /// <summary>
            /// LYDIAN LETTER K 𐤨
            /// </summary>
            LydianLetterK = 0x10928,
            /// <summary>
            /// LYDIAN LETTER L 𐤩
            /// </summary>
            LydianLetterL = 0x10929,
            /// <summary>
            /// LYDIAN LETTER M 𐤪
            /// </summary>
            LydianLetterM = 0x1092A,
            /// <summary>
            /// LYDIAN LETTER N 𐤫
            /// </summary>
            LydianLetterN = 0x1092B,
            /// <summary>
            /// LYDIAN LETTER O 𐤬
            /// </summary>
            LydianLetterO = 0x1092C,
            /// <summary>
            /// LYDIAN LETTER R 𐤭
            /// </summary>
            LydianLetterR = 0x1092D,
            /// <summary>
            /// LYDIAN LETTER SS 𐤮
            /// </summary>
            LydianLetterSs = 0x1092E,
            /// <summary>
            /// LYDIAN LETTER T 𐤯
            /// </summary>
            LydianLetterT = 0x1092F,
            /// <summary>
            /// LYDIAN LETTER U 𐤰
            /// </summary>
            LydianLetterU = 0x10930,
            /// <summary>
            /// LYDIAN LETTER F 𐤱
            /// </summary>
            LydianLetterF = 0x10931,
            /// <summary>
            /// LYDIAN LETTER Q 𐤲
            /// </summary>
            LydianLetterQ = 0x10932,
            /// <summary>
            /// LYDIAN LETTER S 𐤳
            /// </summary>
            LydianLetterS = 0x10933,
            /// <summary>
            /// LYDIAN LETTER TT 𐤴
            /// </summary>
            LydianLetterTt = 0x10934,
            /// <summary>
            /// LYDIAN LETTER AN 𐤵
            /// </summary>
            LydianLetterAn = 0x10935,
            /// <summary>
            /// LYDIAN LETTER EN 𐤶
            /// </summary>
            LydianLetterEn = 0x10936,
            /// <summary>
            /// LYDIAN LETTER LY 𐤷
            /// </summary>
            LydianLetterLy = 0x10937,
            /// <summary>
            /// LYDIAN LETTER NN 𐤸
            /// </summary>
            LydianLetterNn = 0x10938,
            /// <summary>
            /// LYDIAN LETTER C 𐤹
            /// </summary>
            LydianLetterC = 0x10939
        }
        public enum OtherPunctuation : int
        {
            /// <summary>
            /// LYDIAN TRIANGULAR MARK 𐤿
            /// </summary>
            LydianTriangularMark = 0x1093F
        }
    }
}
