// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class Devanagari
    {
        public enum NonSpacingMark : int
        {
            /// <summary>
            /// DEVANAGARI SIGN INVERTED CANDRABINDU ऀ
            /// </summary>
            DevanagariSignInvertedCandrabindu = 0x0900,
            /// <summary>
            /// DEVANAGARI SIGN CANDRABINDU ँ
            /// </summary>
            DevanagariSignCandrabindu = 0x0901,
            /// <summary>
            /// DEVANAGARI SIGN ANUSVARA ं
            /// </summary>
            DevanagariSignAnusvara = 0x0902,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN OE ऺ
            /// </summary>
            DevanagariVowelSignOe = 0x093A,
            /// <summary>
            /// DEVANAGARI SIGN NUKTA ़
            /// </summary>
            DevanagariSignNukta = 0x093C,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN U ु
            /// </summary>
            DevanagariVowelSignU = 0x0941,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN UU ू
            /// </summary>
            DevanagariVowelSignUu = 0x0942,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN VOCALIC R ृ
            /// </summary>
            DevanagariVowelSignVocalicR = 0x0943,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN VOCALIC RR ॄ
            /// </summary>
            DevanagariVowelSignVocalicRr = 0x0944,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN CANDRA E ॅ
            /// </summary>
            DevanagariVowelSignCandraE = 0x0945,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN SHORT E ॆ
            /// </summary>
            DevanagariVowelSignShortE = 0x0946,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN E े
            /// </summary>
            DevanagariVowelSignE = 0x0947,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN AI ै
            /// </summary>
            DevanagariVowelSignAi = 0x0948,
            /// <summary>
            /// DEVANAGARI SIGN VIRAMA ्
            /// </summary>
            DevanagariSignVirama = 0x094D,
            /// <summary>
            /// DEVANAGARI STRESS SIGN UDATTA ॑
            /// </summary>
            DevanagariStressSignUdatta = 0x0951,
            /// <summary>
            /// DEVANAGARI STRESS SIGN ANUDATTA ॒
            /// </summary>
            DevanagariStressSignAnudatta = 0x0952,
            /// <summary>
            /// DEVANAGARI GRAVE ACCENT ॓
            /// </summary>
            DevanagariGraveAccent = 0x0953,
            /// <summary>
            /// DEVANAGARI ACUTE ACCENT ॔
            /// </summary>
            DevanagariAcuteAccent = 0x0954,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN CANDRA LONG E ॕ
            /// </summary>
            DevanagariVowelSignCandraLongE = 0x0955,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN UE ॖ
            /// </summary>
            DevanagariVowelSignUe = 0x0956,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN UUE ॗ
            /// </summary>
            DevanagariVowelSignUue = 0x0957,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN VOCALIC L ॢ
            /// </summary>
            DevanagariVowelSignVocalicL = 0x0962,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN VOCALIC LL ॣ
            /// </summary>
            DevanagariVowelSignVocalicLl = 0x0963
        }
        public enum SpacingCombiningMark : int
        {
            /// <summary>
            /// DEVANAGARI SIGN VISARGA ः
            /// </summary>
            DevanagariSignVisarga = 0x0903,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN OOE ऻ
            /// </summary>
            DevanagariVowelSignOoe = 0x093B,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN AA ा
            /// </summary>
            DevanagariVowelSignAa = 0x093E,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN I ि
            /// </summary>
            DevanagariVowelSignI = 0x093F,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN II ी
            /// </summary>
            DevanagariVowelSignIi = 0x0940,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN CANDRA O ॉ
            /// </summary>
            DevanagariVowelSignCandraO = 0x0949,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN SHORT O ॊ
            /// </summary>
            DevanagariVowelSignShortO = 0x094A,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN O ो
            /// </summary>
            DevanagariVowelSignO = 0x094B,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN AU ौ
            /// </summary>
            DevanagariVowelSignAu = 0x094C,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN PRISHTHAMATRA E ॎ
            /// </summary>
            DevanagariVowelSignPrishthamatraE = 0x094E,
            /// <summary>
            /// DEVANAGARI VOWEL SIGN AW ॏ
            /// </summary>
            DevanagariVowelSignAw = 0x094F
        }
        public enum OtherLetter : int
        {
            /// <summary>
            /// DEVANAGARI LETTER SHORT A ऄ
            /// </summary>
            DevanagariLetterShortA = 0x0904,
            /// <summary>
            /// DEVANAGARI LETTER A अ
            /// </summary>
            DevanagariLetterA = 0x0905,
            /// <summary>
            /// DEVANAGARI LETTER AA आ
            /// </summary>
            DevanagariLetterAa = 0x0906,
            /// <summary>
            /// DEVANAGARI LETTER I इ
            /// </summary>
            DevanagariLetterI = 0x0907,
            /// <summary>
            /// DEVANAGARI LETTER II ई
            /// </summary>
            DevanagariLetterIi = 0x0908,
            /// <summary>
            /// DEVANAGARI LETTER U उ
            /// </summary>
            DevanagariLetterU = 0x0909,
            /// <summary>
            /// DEVANAGARI LETTER UU ऊ
            /// </summary>
            DevanagariLetterUu = 0x090A,
            /// <summary>
            /// DEVANAGARI LETTER VOCALIC R ऋ
            /// </summary>
            DevanagariLetterVocalicR = 0x090B,
            /// <summary>
            /// DEVANAGARI LETTER VOCALIC L ऌ
            /// </summary>
            DevanagariLetterVocalicL = 0x090C,
            /// <summary>
            /// DEVANAGARI LETTER CANDRA E ऍ
            /// </summary>
            DevanagariLetterCandraE = 0x090D,
            /// <summary>
            /// DEVANAGARI LETTER SHORT E ऎ
            /// </summary>
            DevanagariLetterShortE = 0x090E,
            /// <summary>
            /// DEVANAGARI LETTER E ए
            /// </summary>
            DevanagariLetterE = 0x090F,
            /// <summary>
            /// DEVANAGARI LETTER AI ऐ
            /// </summary>
            DevanagariLetterAi = 0x0910,
            /// <summary>
            /// DEVANAGARI LETTER CANDRA O ऑ
            /// </summary>
            DevanagariLetterCandraO = 0x0911,
            /// <summary>
            /// DEVANAGARI LETTER SHORT O ऒ
            /// </summary>
            DevanagariLetterShortO = 0x0912,
            /// <summary>
            /// DEVANAGARI LETTER O ओ
            /// </summary>
            DevanagariLetterO = 0x0913,
            /// <summary>
            /// DEVANAGARI LETTER AU औ
            /// </summary>
            DevanagariLetterAu = 0x0914,
            /// <summary>
            /// DEVANAGARI LETTER KA क
            /// </summary>
            DevanagariLetterKa = 0x0915,
            /// <summary>
            /// DEVANAGARI LETTER KHA ख
            /// </summary>
            DevanagariLetterKha = 0x0916,
            /// <summary>
            /// DEVANAGARI LETTER GA ग
            /// </summary>
            DevanagariLetterGa = 0x0917,
            /// <summary>
            /// DEVANAGARI LETTER GHA घ
            /// </summary>
            DevanagariLetterGha = 0x0918,
            /// <summary>
            /// DEVANAGARI LETTER NGA ङ
            /// </summary>
            DevanagariLetterNga = 0x0919,
            /// <summary>
            /// DEVANAGARI LETTER CA च
            /// </summary>
            DevanagariLetterCa = 0x091A,
            /// <summary>
            /// DEVANAGARI LETTER CHA छ
            /// </summary>
            DevanagariLetterCha = 0x091B,
            /// <summary>
            /// DEVANAGARI LETTER JA ज
            /// </summary>
            DevanagariLetterJa = 0x091C,
            /// <summary>
            /// DEVANAGARI LETTER JHA झ
            /// </summary>
            DevanagariLetterJha = 0x091D,
            /// <summary>
            /// DEVANAGARI LETTER NYA ञ
            /// </summary>
            DevanagariLetterNya = 0x091E,
            /// <summary>
            /// DEVANAGARI LETTER TTA ट
            /// </summary>
            DevanagariLetterTta = 0x091F,
            /// <summary>
            /// DEVANAGARI LETTER TTHA ठ
            /// </summary>
            DevanagariLetterTtha = 0x0920,
            /// <summary>
            /// DEVANAGARI LETTER DDA ड
            /// </summary>
            DevanagariLetterDda = 0x0921,
            /// <summary>
            /// DEVANAGARI LETTER DDHA ढ
            /// </summary>
            DevanagariLetterDdha = 0x0922,
            /// <summary>
            /// DEVANAGARI LETTER NNA ण
            /// </summary>
            DevanagariLetterNna = 0x0923,
            /// <summary>
            /// DEVANAGARI LETTER TA त
            /// </summary>
            DevanagariLetterTa = 0x0924,
            /// <summary>
            /// DEVANAGARI LETTER THA थ
            /// </summary>
            DevanagariLetterTha = 0x0925,
            /// <summary>
            /// DEVANAGARI LETTER DA द
            /// </summary>
            DevanagariLetterDa = 0x0926,
            /// <summary>
            /// DEVANAGARI LETTER DHA ध
            /// </summary>
            DevanagariLetterDha = 0x0927,
            /// <summary>
            /// DEVANAGARI LETTER NA न
            /// </summary>
            DevanagariLetterNa = 0x0928,
            /// <summary>
            /// DEVANAGARI LETTER NNNA ऩ
            /// </summary>
            DevanagariLetterNnna = 0x0929,
            /// <summary>
            /// DEVANAGARI LETTER PA प
            /// </summary>
            DevanagariLetterPa = 0x092A,
            /// <summary>
            /// DEVANAGARI LETTER PHA फ
            /// </summary>
            DevanagariLetterPha = 0x092B,
            /// <summary>
            /// DEVANAGARI LETTER BA ब
            /// </summary>
            DevanagariLetterBa = 0x092C,
            /// <summary>
            /// DEVANAGARI LETTER BHA भ
            /// </summary>
            DevanagariLetterBha = 0x092D,
            /// <summary>
            /// DEVANAGARI LETTER MA म
            /// </summary>
            DevanagariLetterMa = 0x092E,
            /// <summary>
            /// DEVANAGARI LETTER YA य
            /// </summary>
            DevanagariLetterYa = 0x092F,
            /// <summary>
            /// DEVANAGARI LETTER RA र
            /// </summary>
            DevanagariLetterRa = 0x0930,
            /// <summary>
            /// DEVANAGARI LETTER RRA ऱ
            /// </summary>
            DevanagariLetterRra = 0x0931,
            /// <summary>
            /// DEVANAGARI LETTER LA ल
            /// </summary>
            DevanagariLetterLa = 0x0932,
            /// <summary>
            /// DEVANAGARI LETTER LLA ळ
            /// </summary>
            DevanagariLetterLla = 0x0933,
            /// <summary>
            /// DEVANAGARI LETTER LLLA ऴ
            /// </summary>
            DevanagariLetterLlla = 0x0934,
            /// <summary>
            /// DEVANAGARI LETTER VA व
            /// </summary>
            DevanagariLetterVa = 0x0935,
            /// <summary>
            /// DEVANAGARI LETTER SHA श
            /// </summary>
            DevanagariLetterSha = 0x0936,
            /// <summary>
            /// DEVANAGARI LETTER SSA ष
            /// </summary>
            DevanagariLetterSsa = 0x0937,
            /// <summary>
            /// DEVANAGARI LETTER SA स
            /// </summary>
            DevanagariLetterSa = 0x0938,
            /// <summary>
            /// DEVANAGARI LETTER HA ह
            /// </summary>
            DevanagariLetterHa = 0x0939,
            /// <summary>
            /// DEVANAGARI SIGN AVAGRAHA ऽ
            /// </summary>
            DevanagariSignAvagraha = 0x093D,
            /// <summary>
            /// DEVANAGARI OM ॐ
            /// </summary>
            DevanagariOm = 0x0950,
            /// <summary>
            /// DEVANAGARI LETTER QA क़
            /// </summary>
            DevanagariLetterQa = 0x0958,
            /// <summary>
            /// DEVANAGARI LETTER KHHA ख़
            /// </summary>
            DevanagariLetterKhha = 0x0959,
            /// <summary>
            /// DEVANAGARI LETTER GHHA ग़
            /// </summary>
            DevanagariLetterGhha = 0x095A,
            /// <summary>
            /// DEVANAGARI LETTER ZA ज़
            /// </summary>
            DevanagariLetterZa = 0x095B,
            /// <summary>
            /// DEVANAGARI LETTER DDDHA ड़
            /// </summary>
            DevanagariLetterDddha = 0x095C,
            /// <summary>
            /// DEVANAGARI LETTER RHA ढ़
            /// </summary>
            DevanagariLetterRha = 0x095D,
            /// <summary>
            /// DEVANAGARI LETTER FA फ़
            /// </summary>
            DevanagariLetterFa = 0x095E,
            /// <summary>
            /// DEVANAGARI LETTER YYA य़
            /// </summary>
            DevanagariLetterYya = 0x095F,
            /// <summary>
            /// DEVANAGARI LETTER VOCALIC RR ॠ
            /// </summary>
            DevanagariLetterVocalicRr = 0x0960,
            /// <summary>
            /// DEVANAGARI LETTER VOCALIC LL ॡ
            /// </summary>
            DevanagariLetterVocalicLl = 0x0961,
            /// <summary>
            /// DEVANAGARI LETTER CANDRA A ॲ
            /// </summary>
            DevanagariLetterCandraA = 0x0972,
            /// <summary>
            /// DEVANAGARI LETTER OE ॳ
            /// </summary>
            DevanagariLetterOe = 0x0973,
            /// <summary>
            /// DEVANAGARI LETTER OOE ॴ
            /// </summary>
            DevanagariLetterOoe = 0x0974,
            /// <summary>
            /// DEVANAGARI LETTER AW ॵ
            /// </summary>
            DevanagariLetterAw = 0x0975,
            /// <summary>
            /// DEVANAGARI LETTER UE ॶ
            /// </summary>
            DevanagariLetterUe = 0x0976,
            /// <summary>
            /// DEVANAGARI LETTER UUE ॷ
            /// </summary>
            DevanagariLetterUue = 0x0977,
            /// <summary>
            /// DEVANAGARI LETTER MARWARI DDA ॸ
            /// </summary>
            DevanagariLetterMarwariDda = 0x0978,
            /// <summary>
            /// DEVANAGARI LETTER ZHA ॹ
            /// </summary>
            DevanagariLetterZha = 0x0979,
            /// <summary>
            /// DEVANAGARI LETTER HEAVY YA ॺ
            /// </summary>
            DevanagariLetterHeavyYa = 0x097A,
            /// <summary>
            /// DEVANAGARI LETTER GGA ॻ
            /// </summary>
            DevanagariLetterGga = 0x097B,
            /// <summary>
            /// DEVANAGARI LETTER JJA ॼ
            /// </summary>
            DevanagariLetterJja = 0x097C,
            /// <summary>
            /// DEVANAGARI LETTER GLOTTAL STOP ॽ
            /// </summary>
            DevanagariLetterGlottalStop = 0x097D,
            /// <summary>
            /// DEVANAGARI LETTER DDDA ॾ
            /// </summary>
            DevanagariLetterDdda = 0x097E,
            /// <summary>
            /// DEVANAGARI LETTER BBA ॿ
            /// </summary>
            DevanagariLetterBba = 0x097F
        }
        public enum OtherPunctuation : int
        {
            /// <summary>
            /// DEVANAGARI DANDA ।
            /// </summary>
            DevanagariDanda = 0x0964,
            /// <summary>
            /// DEVANAGARI DOUBLE DANDA ॥
            /// </summary>
            DevanagariDoubleDanda = 0x0965,
            /// <summary>
            /// DEVANAGARI ABBREVIATION SIGN ॰
            /// </summary>
            DevanagariAbbreviationSign = 0x0970
        }
        public enum DecimalDigitNumber : int
        {
            /// <summary>
            /// DEVANAGARI DIGIT ZERO ०
            /// </summary>
            DevanagariDigitZero = 0x0966,
            /// <summary>
            /// DEVANAGARI DIGIT ONE १
            /// </summary>
            DevanagariDigitOne = 0x0967,
            /// <summary>
            /// DEVANAGARI DIGIT TWO २
            /// </summary>
            DevanagariDigitTwo = 0x0968,
            /// <summary>
            /// DEVANAGARI DIGIT THREE ३
            /// </summary>
            DevanagariDigitThree = 0x0969,
            /// <summary>
            /// DEVANAGARI DIGIT FOUR ४
            /// </summary>
            DevanagariDigitFour = 0x096A,
            /// <summary>
            /// DEVANAGARI DIGIT FIVE ५
            /// </summary>
            DevanagariDigitFive = 0x096B,
            /// <summary>
            /// DEVANAGARI DIGIT SIX ६
            /// </summary>
            DevanagariDigitSix = 0x096C,
            /// <summary>
            /// DEVANAGARI DIGIT SEVEN ७
            /// </summary>
            DevanagariDigitSeven = 0x096D,
            /// <summary>
            /// DEVANAGARI DIGIT EIGHT ८
            /// </summary>
            DevanagariDigitEight = 0x096E,
            /// <summary>
            /// DEVANAGARI DIGIT NINE ९
            /// </summary>
            DevanagariDigitNine = 0x096F
        }
        public enum ModifierLetter : int
        {
            /// <summary>
            /// DEVANAGARI SIGN HIGH SPACING DOT ॱ
            /// </summary>
            DevanagariSignHighSpacingDot = 0x0971
        }
    }
}
