// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class PauCinHau
    {
        public enum OtherLetter : int
        {
            /// <summary>
            /// PAU CIN HAU LETTER PA 𑫀
            /// </summary>
            PauCinHauLetterPa = 0x11AC0,
            /// <summary>
            /// PAU CIN HAU LETTER KA 𑫁
            /// </summary>
            PauCinHauLetterKa = 0x11AC1,
            /// <summary>
            /// PAU CIN HAU LETTER LA 𑫂
            /// </summary>
            PauCinHauLetterLa = 0x11AC2,
            /// <summary>
            /// PAU CIN HAU LETTER MA 𑫃
            /// </summary>
            PauCinHauLetterMa = 0x11AC3,
            /// <summary>
            /// PAU CIN HAU LETTER DA 𑫄
            /// </summary>
            PauCinHauLetterDa = 0x11AC4,
            /// <summary>
            /// PAU CIN HAU LETTER ZA 𑫅
            /// </summary>
            PauCinHauLetterZa = 0x11AC5,
            /// <summary>
            /// PAU CIN HAU LETTER VA 𑫆
            /// </summary>
            PauCinHauLetterVa = 0x11AC6,
            /// <summary>
            /// PAU CIN HAU LETTER NGA 𑫇
            /// </summary>
            PauCinHauLetterNga = 0x11AC7,
            /// <summary>
            /// PAU CIN HAU LETTER HA 𑫈
            /// </summary>
            PauCinHauLetterHa = 0x11AC8,
            /// <summary>
            /// PAU CIN HAU LETTER GA 𑫉
            /// </summary>
            PauCinHauLetterGa = 0x11AC9,
            /// <summary>
            /// PAU CIN HAU LETTER KHA 𑫊
            /// </summary>
            PauCinHauLetterKha = 0x11ACA,
            /// <summary>
            /// PAU CIN HAU LETTER SA 𑫋
            /// </summary>
            PauCinHauLetterSa = 0x11ACB,
            /// <summary>
            /// PAU CIN HAU LETTER BA 𑫌
            /// </summary>
            PauCinHauLetterBa = 0x11ACC,
            /// <summary>
            /// PAU CIN HAU LETTER CA 𑫍
            /// </summary>
            PauCinHauLetterCa = 0x11ACD,
            /// <summary>
            /// PAU CIN HAU LETTER TA 𑫎
            /// </summary>
            PauCinHauLetterTa = 0x11ACE,
            /// <summary>
            /// PAU CIN HAU LETTER THA 𑫏
            /// </summary>
            PauCinHauLetterTha = 0x11ACF,
            /// <summary>
            /// PAU CIN HAU LETTER NA 𑫐
            /// </summary>
            PauCinHauLetterNa = 0x11AD0,
            /// <summary>
            /// PAU CIN HAU LETTER PHA 𑫑
            /// </summary>
            PauCinHauLetterPha = 0x11AD1,
            /// <summary>
            /// PAU CIN HAU LETTER RA 𑫒
            /// </summary>
            PauCinHauLetterRa = 0x11AD2,
            /// <summary>
            /// PAU CIN HAU LETTER FA 𑫓
            /// </summary>
            PauCinHauLetterFa = 0x11AD3,
            /// <summary>
            /// PAU CIN HAU LETTER CHA 𑫔
            /// </summary>
            PauCinHauLetterCha = 0x11AD4,
            /// <summary>
            /// PAU CIN HAU LETTER A 𑫕
            /// </summary>
            PauCinHauLetterA = 0x11AD5,
            /// <summary>
            /// PAU CIN HAU LETTER E 𑫖
            /// </summary>
            PauCinHauLetterE = 0x11AD6,
            /// <summary>
            /// PAU CIN HAU LETTER I 𑫗
            /// </summary>
            PauCinHauLetterI = 0x11AD7,
            /// <summary>
            /// PAU CIN HAU LETTER O 𑫘
            /// </summary>
            PauCinHauLetterO = 0x11AD8,
            /// <summary>
            /// PAU CIN HAU LETTER U 𑫙
            /// </summary>
            PauCinHauLetterU = 0x11AD9,
            /// <summary>
            /// PAU CIN HAU LETTER UA 𑫚
            /// </summary>
            PauCinHauLetterUa = 0x11ADA,
            /// <summary>
            /// PAU CIN HAU LETTER IA 𑫛
            /// </summary>
            PauCinHauLetterIa = 0x11ADB,
            /// <summary>
            /// PAU CIN HAU LETTER FINAL P 𑫜
            /// </summary>
            PauCinHauLetterFinalP = 0x11ADC,
            /// <summary>
            /// PAU CIN HAU LETTER FINAL K 𑫝
            /// </summary>
            PauCinHauLetterFinalK = 0x11ADD,
            /// <summary>
            /// PAU CIN HAU LETTER FINAL T 𑫞
            /// </summary>
            PauCinHauLetterFinalT = 0x11ADE,
            /// <summary>
            /// PAU CIN HAU LETTER FINAL M 𑫟
            /// </summary>
            PauCinHauLetterFinalM = 0x11ADF,
            /// <summary>
            /// PAU CIN HAU LETTER FINAL N 𑫠
            /// </summary>
            PauCinHauLetterFinalN = 0x11AE0,
            /// <summary>
            /// PAU CIN HAU LETTER FINAL L 𑫡
            /// </summary>
            PauCinHauLetterFinalL = 0x11AE1,
            /// <summary>
            /// PAU CIN HAU LETTER FINAL W 𑫢
            /// </summary>
            PauCinHauLetterFinalW = 0x11AE2,
            /// <summary>
            /// PAU CIN HAU LETTER FINAL NG 𑫣
            /// </summary>
            PauCinHauLetterFinalNg = 0x11AE3,
            /// <summary>
            /// PAU CIN HAU LETTER FINAL Y 𑫤
            /// </summary>
            PauCinHauLetterFinalY = 0x11AE4,
            /// <summary>
            /// PAU CIN HAU RISING TONE LONG 𑫥
            /// </summary>
            PauCinHauRisingToneLong = 0x11AE5,
            /// <summary>
            /// PAU CIN HAU RISING TONE 𑫦
            /// </summary>
            PauCinHauRisingTone = 0x11AE6,
            /// <summary>
            /// PAU CIN HAU SANDHI GLOTTAL STOP 𑫧
            /// </summary>
            PauCinHauSandhiGlottalStop = 0x11AE7,
            /// <summary>
            /// PAU CIN HAU RISING TONE LONG FINAL 𑫨
            /// </summary>
            PauCinHauRisingToneLongFinal = 0x11AE8,
            /// <summary>
            /// PAU CIN HAU RISING TONE FINAL 𑫩
            /// </summary>
            PauCinHauRisingToneFinal = 0x11AE9,
            /// <summary>
            /// PAU CIN HAU SANDHI GLOTTAL STOP FINAL 𑫪
            /// </summary>
            PauCinHauSandhiGlottalStopFinal = 0x11AEA,
            /// <summary>
            /// PAU CIN HAU SANDHI TONE LONG 𑫫
            /// </summary>
            PauCinHauSandhiToneLong = 0x11AEB,
            /// <summary>
            /// PAU CIN HAU SANDHI TONE 𑫬
            /// </summary>
            PauCinHauSandhiTone = 0x11AEC,
            /// <summary>
            /// PAU CIN HAU SANDHI TONE LONG FINAL 𑫭
            /// </summary>
            PauCinHauSandhiToneLongFinal = 0x11AED,
            /// <summary>
            /// PAU CIN HAU SANDHI TONE FINAL 𑫮
            /// </summary>
            PauCinHauSandhiToneFinal = 0x11AEE,
            /// <summary>
            /// PAU CIN HAU MID-LEVEL TONE 𑫯
            /// </summary>
            PauCinHauMidLevelTone = 0x11AEF,
            /// <summary>
            /// PAU CIN HAU GLOTTAL STOP VARIANT 𑫰
            /// </summary>
            PauCinHauGlottalStopVariant = 0x11AF0,
            /// <summary>
            /// PAU CIN HAU MID-LEVEL TONE LONG FINAL 𑫱
            /// </summary>
            PauCinHauMidLevelToneLongFinal = 0x11AF1,
            /// <summary>
            /// PAU CIN HAU MID-LEVEL TONE FINAL 𑫲
            /// </summary>
            PauCinHauMidLevelToneFinal = 0x11AF2,
            /// <summary>
            /// PAU CIN HAU LOW-FALLING TONE LONG 𑫳
            /// </summary>
            PauCinHauLowFallingToneLong = 0x11AF3,
            /// <summary>
            /// PAU CIN HAU LOW-FALLING TONE 𑫴
            /// </summary>
            PauCinHauLowFallingTone = 0x11AF4,
            /// <summary>
            /// PAU CIN HAU GLOTTAL STOP 𑫵
            /// </summary>
            PauCinHauGlottalStop = 0x11AF5,
            /// <summary>
            /// PAU CIN HAU LOW-FALLING TONE LONG FINAL 𑫶
            /// </summary>
            PauCinHauLowFallingToneLongFinal = 0x11AF6,
            /// <summary>
            /// PAU CIN HAU LOW-FALLING TONE FINAL 𑫷
            /// </summary>
            PauCinHauLowFallingToneFinal = 0x11AF7,
            /// <summary>
            /// PAU CIN HAU GLOTTAL STOP FINAL 𑫸
            /// </summary>
            PauCinHauGlottalStopFinal = 0x11AF8
        }
    }
}
