// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class LetterlikeSymbols
    {
        public enum OtherSymbol : int
        {
            /// <summary>
            /// ACCOUNT OF ℀
            /// </summary>
            AccountOf = 0x2100,
            /// <summary>
            /// ADDRESSED TO THE SUBJECT ℁
            /// </summary>
            AddressedToTheSubject = 0x2101,
            /// <summary>
            /// DEGREE CELSIUS ℃
            /// </summary>
            DegreeCelsius = 0x2103,
            /// <summary>
            /// CENTRE LINE SYMBOL ℄
            /// </summary>
            CentreLineSymbol = 0x2104,
            /// <summary>
            /// CARE OF ℅
            /// </summary>
            CareOf = 0x2105,
            /// <summary>
            /// CADA UNA ℆
            /// </summary>
            CadaUna = 0x2106,
            /// <summary>
            /// SCRUPLE ℈
            /// </summary>
            Scruple = 0x2108,
            /// <summary>
            /// DEGREE FAHRENHEIT ℉
            /// </summary>
            DegreeFahrenheit = 0x2109,
            /// <summary>
            /// L B BAR SYMBOL ℔
            /// </summary>
            LBBarSymbol = 0x2114,
            /// <summary>
            /// NUMERO SIGN №
            /// </summary>
            NumeroSign = 0x2116,
            /// <summary>
            /// SOUND RECORDING COPYRIGHT ℗
            /// </summary>
            SoundRecordingCopyright = 0x2117,
            /// <summary>
            /// PRESCRIPTION TAKE ℞
            /// </summary>
            PrescriptionTake = 0x211E,
            /// <summary>
            /// RESPONSE ℟
            /// </summary>
            Response = 0x211F,
            /// <summary>
            /// SERVICE MARK ℠
            /// </summary>
            ServiceMark = 0x2120,
            /// <summary>
            /// TELEPHONE SIGN ℡
            /// </summary>
            TelephoneSign = 0x2121,
            /// <summary>
            /// TRADE MARK SIGN ™
            /// </summary>
            TradeMarkSign = 0x2122,
            /// <summary>
            /// VERSICLE ℣
            /// </summary>
            Versicle = 0x2123,
            /// <summary>
            /// OUNCE SIGN ℥
            /// </summary>
            OunceSign = 0x2125,
            /// <summary>
            /// INVERTED OHM SIGN ℧
            /// </summary>
            InvertedOhmSign = 0x2127,
            /// <summary>
            /// TURNED GREEK SMALL LETTER IOTA ℩
            /// </summary>
            TurnedGreekSmallLetterIota = 0x2129,
            /// <summary>
            /// ESTIMATED SYMBOL ℮
            /// </summary>
            EstimatedSymbol = 0x212E,
            /// <summary>
            /// ROTATED CAPITAL Q ℺
            /// </summary>
            RotatedCapitalQ = 0x213A,
            /// <summary>
            /// FACSIMILE SIGN ℻
            /// </summary>
            FacsimileSign = 0x213B,
            /// <summary>
            /// PROPERTY LINE ⅊
            /// </summary>
            PropertyLine = 0x214A,
            /// <summary>
            /// PER SIGN ⅌
            /// </summary>
            PerSign = 0x214C,
            /// <summary>
            /// AKTIESELSKAB ⅍
            /// </summary>
            Aktieselskab = 0x214D,
            /// <summary>
            /// SYMBOL FOR SAMARITAN SOURCE ⅏
            /// </summary>
            SymbolForSamaritanSource = 0x214F
        }
        public enum UppercaseLetter : int
        {
            /// <summary>
            /// DOUBLE-STRUCK CAPITAL C ℂ
            /// </summary>
            DoubleStruckCapitalC = 0x2102,
            /// <summary>
            /// EULER CONSTANT ℇ
            /// </summary>
            EulerConstant = 0x2107,
            /// <summary>
            /// SCRIPT CAPITAL H ℋ
            /// </summary>
            ScriptCapitalH = 0x210B,
            /// <summary>
            /// BLACK-LETTER CAPITAL H ℌ
            /// </summary>
            BlackLetterCapitalH = 0x210C,
            /// <summary>
            /// DOUBLE-STRUCK CAPITAL H ℍ
            /// </summary>
            DoubleStruckCapitalH = 0x210D,
            /// <summary>
            /// SCRIPT CAPITAL I ℐ
            /// </summary>
            ScriptCapitalI = 0x2110,
            /// <summary>
            /// BLACK-LETTER CAPITAL I ℑ
            /// </summary>
            BlackLetterCapitalI = 0x2111,
            /// <summary>
            /// SCRIPT CAPITAL L ℒ
            /// </summary>
            ScriptCapitalL = 0x2112,
            /// <summary>
            /// DOUBLE-STRUCK CAPITAL N ℕ
            /// </summary>
            DoubleStruckCapitalN = 0x2115,
            /// <summary>
            /// DOUBLE-STRUCK CAPITAL P ℙ
            /// </summary>
            DoubleStruckCapitalP = 0x2119,
            /// <summary>
            /// DOUBLE-STRUCK CAPITAL Q ℚ
            /// </summary>
            DoubleStruckCapitalQ = 0x211A,
            /// <summary>
            /// SCRIPT CAPITAL R ℛ
            /// </summary>
            ScriptCapitalR = 0x211B,
            /// <summary>
            /// BLACK-LETTER CAPITAL R ℜ
            /// </summary>
            BlackLetterCapitalR = 0x211C,
            /// <summary>
            /// DOUBLE-STRUCK CAPITAL R ℝ
            /// </summary>
            DoubleStruckCapitalR = 0x211D,
            /// <summary>
            /// DOUBLE-STRUCK CAPITAL Z ℤ
            /// </summary>
            DoubleStruckCapitalZ = 0x2124,
            /// <summary>
            /// OHM SIGN Ω
            /// </summary>
            OhmSign = 0x2126,
            /// <summary>
            /// BLACK-LETTER CAPITAL Z ℨ
            /// </summary>
            BlackLetterCapitalZ = 0x2128,
            /// <summary>
            /// KELVIN SIGN K
            /// </summary>
            KelvinSign = 0x212A,
            /// <summary>
            /// ANGSTROM SIGN Å
            /// </summary>
            AngstromSign = 0x212B,
            /// <summary>
            /// SCRIPT CAPITAL B ℬ
            /// </summary>
            ScriptCapitalB = 0x212C,
            /// <summary>
            /// BLACK-LETTER CAPITAL C ℭ
            /// </summary>
            BlackLetterCapitalC = 0x212D,
            /// <summary>
            /// SCRIPT CAPITAL E ℰ
            /// </summary>
            ScriptCapitalE = 0x2130,
            /// <summary>
            /// SCRIPT CAPITAL F ℱ
            /// </summary>
            ScriptCapitalF = 0x2131,
            /// <summary>
            /// TURNED CAPITAL F Ⅎ
            /// </summary>
            TurnedCapitalF = 0x2132,
            /// <summary>
            /// SCRIPT CAPITAL M ℳ
            /// </summary>
            ScriptCapitalM = 0x2133,
            /// <summary>
            /// DOUBLE-STRUCK CAPITAL GAMMA ℾ
            /// </summary>
            DoubleStruckCapitalGamma = 0x213E,
            /// <summary>
            /// DOUBLE-STRUCK CAPITAL PI ℿ
            /// </summary>
            DoubleStruckCapitalPi = 0x213F,
            /// <summary>
            /// DOUBLE-STRUCK ITALIC CAPITAL D ⅅ
            /// </summary>
            DoubleStruckItalicCapitalD = 0x2145
        }
        public enum LowercaseLetter : int
        {
            /// <summary>
            /// SCRIPT SMALL G ℊ
            /// </summary>
            ScriptSmallG = 0x210A,
            /// <summary>
            /// PLANCK CONSTANT ℎ
            /// </summary>
            PlanckConstant = 0x210E,
            /// <summary>
            /// PLANCK CONSTANT OVER TWO PI ℏ
            /// </summary>
            PlanckConstantOverTwoPi = 0x210F,
            /// <summary>
            /// SCRIPT SMALL L ℓ
            /// </summary>
            ScriptSmallL = 0x2113,
            /// <summary>
            /// SCRIPT SMALL E ℯ
            /// </summary>
            ScriptSmallE = 0x212F,
            /// <summary>
            /// SCRIPT SMALL O ℴ
            /// </summary>
            ScriptSmallO = 0x2134,
            /// <summary>
            /// INFORMATION SOURCE ℹ
            /// </summary>
            InformationSource = 0x2139,
            /// <summary>
            /// DOUBLE-STRUCK SMALL PI ℼ
            /// </summary>
            DoubleStruckSmallPi = 0x213C,
            /// <summary>
            /// DOUBLE-STRUCK SMALL GAMMA ℽ
            /// </summary>
            DoubleStruckSmallGamma = 0x213D,
            /// <summary>
            /// DOUBLE-STRUCK ITALIC SMALL D ⅆ
            /// </summary>
            DoubleStruckItalicSmallD = 0x2146,
            /// <summary>
            /// DOUBLE-STRUCK ITALIC SMALL E ⅇ
            /// </summary>
            DoubleStruckItalicSmallE = 0x2147,
            /// <summary>
            /// DOUBLE-STRUCK ITALIC SMALL I ⅈ
            /// </summary>
            DoubleStruckItalicSmallI = 0x2148,
            /// <summary>
            /// DOUBLE-STRUCK ITALIC SMALL J ⅉ
            /// </summary>
            DoubleStruckItalicSmallJ = 0x2149,
            /// <summary>
            /// TURNED SMALL F ⅎ
            /// </summary>
            TurnedSmallF = 0x214E
        }
        public enum MathSymbol : int
        {
            /// <summary>
            /// SCRIPT CAPITAL P ℘
            /// </summary>
            ScriptCapitalP = 0x2118,
            /// <summary>
            /// DOUBLE-STRUCK N-ARY SUMMATION ⅀
            /// </summary>
            DoubleStruckNArySummation = 0x2140,
            /// <summary>
            /// TURNED SANS-SERIF CAPITAL G ⅁
            /// </summary>
            TurnedSansSerifCapitalG = 0x2141,
            /// <summary>
            /// TURNED SANS-SERIF CAPITAL L ⅂
            /// </summary>
            TurnedSansSerifCapitalL = 0x2142,
            /// <summary>
            /// REVERSED SANS-SERIF CAPITAL L ⅃
            /// </summary>
            ReversedSansSerifCapitalL = 0x2143,
            /// <summary>
            /// TURNED SANS-SERIF CAPITAL Y ⅄
            /// </summary>
            TurnedSansSerifCapitalY = 0x2144,
            /// <summary>
            /// TURNED AMPERSAND ⅋
            /// </summary>
            TurnedAmpersand = 0x214B
        }
        public enum OtherLetter : int
        {
            /// <summary>
            /// ALEF SYMBOL ℵ
            /// </summary>
            AlefSymbol = 0x2135,
            /// <summary>
            /// BET SYMBOL ℶ
            /// </summary>
            BetSymbol = 0x2136,
            /// <summary>
            /// GIMEL SYMBOL ℷ
            /// </summary>
            GimelSymbol = 0x2137,
            /// <summary>
            /// DALET SYMBOL ℸ
            /// </summary>
            DaletSymbol = 0x2138
        }
    }
}
