// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class GeneralPunctuation
    {
        public enum SpaceSeparator : int
        {
            /// <summary>
            /// EN QUAD  
            /// </summary>
            EnQuad = 0x2000,
            /// <summary>
            /// EM QUAD  
            /// </summary>
            EmQuad = 0x2001,
            /// <summary>
            /// EN SPACE  
            /// </summary>
            EnSpace = 0x2002,
            /// <summary>
            /// EM SPACE  
            /// </summary>
            EmSpace = 0x2003,
            /// <summary>
            /// THREE-PER-EM SPACE  
            /// </summary>
            ThreePerEmSpace = 0x2004,
            /// <summary>
            /// FOUR-PER-EM SPACE  
            /// </summary>
            FourPerEmSpace = 0x2005,
            /// <summary>
            /// SIX-PER-EM SPACE  
            /// </summary>
            SixPerEmSpace = 0x2006,
            /// <summary>
            /// FIGURE SPACE  
            /// </summary>
            FigureSpace = 0x2007,
            /// <summary>
            /// PUNCTUATION SPACE  
            /// </summary>
            PunctuationSpace = 0x2008,
            /// <summary>
            /// THIN SPACE  
            /// </summary>
            ThinSpace = 0x2009,
            /// <summary>
            /// HAIR SPACE  
            /// </summary>
            HairSpace = 0x200A,
            /// <summary>
            /// NARROW NO-BREAK SPACE  
            /// </summary>
            NarrowNoBreakSpace = 0x202F,
            /// <summary>
            /// MEDIUM MATHEMATICAL SPACE  
            /// </summary>
            MediumMathematicalSpace = 0x205F
        }
        public enum Format : int
        {
            /// <summary>
            /// ZERO WIDTH SPACE ​
            /// </summary>
            ZeroWidthSpace = 0x200B,
            /// <summary>
            /// ZERO WIDTH NON-JOINER ‌
            /// </summary>
            ZeroWidthNonJoiner = 0x200C,
            /// <summary>
            /// ZERO WIDTH JOINER ‍
            /// </summary>
            ZeroWidthJoiner = 0x200D,
            /// <summary>
            /// LEFT-TO-RIGHT MARK ‎
            /// </summary>
            LeftToRightMark = 0x200E,
            /// <summary>
            /// RIGHT-TO-LEFT MARK ‏
            /// </summary>
            RightToLeftMark = 0x200F,
            /// <summary>
            /// LEFT-TO-RIGHT EMBEDDING ‪
            /// </summary>
            LeftToRightEmbedding = 0x202A,
            /// <summary>
            /// RIGHT-TO-LEFT EMBEDDING ‫
            /// </summary>
            RightToLeftEmbedding = 0x202B,
            /// <summary>
            /// POP DIRECTIONAL FORMATTING ‬
            /// </summary>
            PopDirectionalFormatting = 0x202C,
            /// <summary>
            /// LEFT-TO-RIGHT OVERRIDE ‭
            /// </summary>
            LeftToRightOverride = 0x202D,
            /// <summary>
            /// RIGHT-TO-LEFT OVERRIDE ‮
            /// </summary>
            RightToLeftOverride = 0x202E,
            /// <summary>
            /// WORD JOINER ⁠
            /// </summary>
            WordJoiner = 0x2060,
            /// <summary>
            /// FUNCTION APPLICATION ⁡
            /// </summary>
            FunctionApplication = 0x2061,
            /// <summary>
            /// INVISIBLE TIMES ⁢
            /// </summary>
            InvisibleTimes = 0x2062,
            /// <summary>
            /// INVISIBLE SEPARATOR ⁣
            /// </summary>
            InvisibleSeparator = 0x2063,
            /// <summary>
            /// INVISIBLE PLUS ⁤
            /// </summary>
            InvisiblePlus = 0x2064,
            /// <summary>
            /// LEFT-TO-RIGHT ISOLATE ⁦
            /// </summary>
            LeftToRightIsolate = 0x2066,
            /// <summary>
            /// RIGHT-TO-LEFT ISOLATE ⁧
            /// </summary>
            RightToLeftIsolate = 0x2067,
            /// <summary>
            /// FIRST STRONG ISOLATE ⁨
            /// </summary>
            FirstStrongIsolate = 0x2068,
            /// <summary>
            /// POP DIRECTIONAL ISOLATE ⁩
            /// </summary>
            PopDirectionalIsolate = 0x2069,
            /// <summary>
            /// INHIBIT SYMMETRIC SWAPPING ⁪
            /// </summary>
            InhibitSymmetricSwapping = 0x206A,
            /// <summary>
            /// ACTIVATE SYMMETRIC SWAPPING ⁫
            /// </summary>
            ActivateSymmetricSwapping = 0x206B,
            /// <summary>
            /// INHIBIT ARABIC FORM SHAPING ⁬
            /// </summary>
            InhibitArabicFormShaping = 0x206C,
            /// <summary>
            /// ACTIVATE ARABIC FORM SHAPING ⁭
            /// </summary>
            ActivateArabicFormShaping = 0x206D,
            /// <summary>
            /// NATIONAL DIGIT SHAPES ⁮
            /// </summary>
            NationalDigitShapes = 0x206E,
            /// <summary>
            /// NOMINAL DIGIT SHAPES ⁯
            /// </summary>
            NominalDigitShapes = 0x206F
        }
        public enum DashPunctuation : int
        {
            /// <summary>
            /// HYPHEN ‐
            /// </summary>
            Hyphen = 0x2010,
            /// <summary>
            /// NON-BREAKING HYPHEN ‑
            /// </summary>
            NonBreakingHyphen = 0x2011,
            /// <summary>
            /// FIGURE DASH ‒
            /// </summary>
            FigureDash = 0x2012,
            /// <summary>
            /// EN DASH –
            /// </summary>
            EnDash = 0x2013,
            /// <summary>
            /// EM DASH —
            /// </summary>
            EmDash = 0x2014,
            /// <summary>
            /// HORIZONTAL BAR ―
            /// </summary>
            HorizontalBar = 0x2015
        }
        public enum OtherPunctuation : int
        {
            /// <summary>
            /// DOUBLE VERTICAL LINE ‖
            /// </summary>
            DoubleVerticalLine = 0x2016,
            /// <summary>
            /// DOUBLE LOW LINE ‗
            /// </summary>
            DoubleLowLine = 0x2017,
            /// <summary>
            /// DAGGER †
            /// </summary>
            Dagger = 0x2020,
            /// <summary>
            /// DOUBLE DAGGER ‡
            /// </summary>
            DoubleDagger = 0x2021,
            /// <summary>
            /// BULLET •
            /// </summary>
            Bullet = 0x2022,
            /// <summary>
            /// TRIANGULAR BULLET ‣
            /// </summary>
            TriangularBullet = 0x2023,
            /// <summary>
            /// ONE DOT LEADER ․
            /// </summary>
            OneDotLeader = 0x2024,
            /// <summary>
            /// TWO DOT LEADER ‥
            /// </summary>
            TwoDotLeader = 0x2025,
            /// <summary>
            /// HORIZONTAL ELLIPSIS …
            /// </summary>
            HorizontalEllipsis = 0x2026,
            /// <summary>
            /// HYPHENATION POINT ‧
            /// </summary>
            HyphenationPoint = 0x2027,
            /// <summary>
            /// PER MILLE SIGN ‰
            /// </summary>
            PerMilleSign = 0x2030,
            /// <summary>
            /// PER TEN THOUSAND SIGN ‱
            /// </summary>
            PerTenThousandSign = 0x2031,
            /// <summary>
            /// PRIME ′
            /// </summary>
            Prime = 0x2032,
            /// <summary>
            /// DOUBLE PRIME ″
            /// </summary>
            DoublePrime = 0x2033,
            /// <summary>
            /// TRIPLE PRIME ‴
            /// </summary>
            TriplePrime = 0x2034,
            /// <summary>
            /// REVERSED PRIME ‵
            /// </summary>
            ReversedPrime = 0x2035,
            /// <summary>
            /// REVERSED DOUBLE PRIME ‶
            /// </summary>
            ReversedDoublePrime = 0x2036,
            /// <summary>
            /// REVERSED TRIPLE PRIME ‷
            /// </summary>
            ReversedTriplePrime = 0x2037,
            /// <summary>
            /// CARET ‸
            /// </summary>
            Caret = 0x2038,
            /// <summary>
            /// REFERENCE MARK ※
            /// </summary>
            ReferenceMark = 0x203B,
            /// <summary>
            /// DOUBLE EXCLAMATION MARK ‼
            /// </summary>
            DoubleExclamationMark = 0x203C,
            /// <summary>
            /// INTERROBANG ‽
            /// </summary>
            Interrobang = 0x203D,
            /// <summary>
            /// OVERLINE ‾
            /// </summary>
            Overline = 0x203E,
            /// <summary>
            /// CARET INSERTION POINT ⁁
            /// </summary>
            CaretInsertionPoint = 0x2041,
            /// <summary>
            /// ASTERISM ⁂
            /// </summary>
            Asterism = 0x2042,
            /// <summary>
            /// HYPHEN BULLET ⁃
            /// </summary>
            HyphenBullet = 0x2043,
            /// <summary>
            /// DOUBLE QUESTION MARK ⁇
            /// </summary>
            DoubleQuestionMark = 0x2047,
            /// <summary>
            /// QUESTION EXCLAMATION MARK ⁈
            /// </summary>
            QuestionExclamationMark = 0x2048,
            /// <summary>
            /// EXCLAMATION QUESTION MARK ⁉
            /// </summary>
            ExclamationQuestionMark = 0x2049,
            /// <summary>
            /// TIRONIAN SIGN ET ⁊
            /// </summary>
            TironianSignEt = 0x204A,
            /// <summary>
            /// REVERSED PILCROW SIGN ⁋
            /// </summary>
            ReversedPilcrowSign = 0x204B,
            /// <summary>
            /// BLACK LEFTWARDS BULLET ⁌
            /// </summary>
            BlackLeftwardsBullet = 0x204C,
            /// <summary>
            /// BLACK RIGHTWARDS BULLET ⁍
            /// </summary>
            BlackRightwardsBullet = 0x204D,
            /// <summary>
            /// LOW ASTERISK ⁎
            /// </summary>
            LowAsterisk = 0x204E,
            /// <summary>
            /// REVERSED SEMICOLON ⁏
            /// </summary>
            ReversedSemicolon = 0x204F,
            /// <summary>
            /// CLOSE UP ⁐
            /// </summary>
            CloseUp = 0x2050,
            /// <summary>
            /// TWO ASTERISKS ALIGNED VERTICALLY ⁑
            /// </summary>
            TwoAsterisksAlignedVertically = 0x2051,
            /// <summary>
            /// SWUNG DASH ⁓
            /// </summary>
            SwungDash = 0x2053,
            /// <summary>
            /// FLOWER PUNCTUATION MARK ⁕
            /// </summary>
            FlowerPunctuationMark = 0x2055,
            /// <summary>
            /// THREE DOT PUNCTUATION ⁖
            /// </summary>
            ThreeDotPunctuation = 0x2056,
            /// <summary>
            /// QUADRUPLE PRIME ⁗
            /// </summary>
            QuadruplePrime = 0x2057,
            /// <summary>
            /// FOUR DOT PUNCTUATION ⁘
            /// </summary>
            FourDotPunctuation = 0x2058,
            /// <summary>
            /// FIVE DOT PUNCTUATION ⁙
            /// </summary>
            FiveDotPunctuation = 0x2059,
            /// <summary>
            /// TWO DOT PUNCTUATION ⁚
            /// </summary>
            TwoDotPunctuation = 0x205A,
            /// <summary>
            /// FOUR DOT MARK ⁛
            /// </summary>
            FourDotMark = 0x205B,
            /// <summary>
            /// DOTTED CROSS ⁜
            /// </summary>
            DottedCross = 0x205C,
            /// <summary>
            /// TRICOLON ⁝
            /// </summary>
            Tricolon = 0x205D,
            /// <summary>
            /// VERTICAL FOUR DOTS ⁞
            /// </summary>
            VerticalFourDots = 0x205E
        }
        public enum InitialQuotePunctuation : int
        {
            /// <summary>
            /// LEFT SINGLE QUOTATION MARK ‘
            /// </summary>
            LeftSingleQuotationMark = 0x2018,
            /// <summary>
            /// SINGLE HIGH-REVERSED-9 QUOTATION MARK ‛
            /// </summary>
            SingleHighReversed9QuotationMark = 0x201B,
            /// <summary>
            /// LEFT DOUBLE QUOTATION MARK “
            /// </summary>
            LeftDoubleQuotationMark = 0x201C,
            /// <summary>
            /// DOUBLE HIGH-REVERSED-9 QUOTATION MARK ‟
            /// </summary>
            DoubleHighReversed9QuotationMark = 0x201F,
            /// <summary>
            /// SINGLE LEFT-POINTING ANGLE QUOTATION MARK ‹
            /// </summary>
            SingleLeftPointingAngleQuotationMark = 0x2039
        }
        public enum FinalQuotePunctuation : int
        {
            /// <summary>
            /// RIGHT SINGLE QUOTATION MARK ’
            /// </summary>
            RightSingleQuotationMark = 0x2019,
            /// <summary>
            /// RIGHT DOUBLE QUOTATION MARK ”
            /// </summary>
            RightDoubleQuotationMark = 0x201D,
            /// <summary>
            /// SINGLE RIGHT-POINTING ANGLE QUOTATION MARK ›
            /// </summary>
            SingleRightPointingAngleQuotationMark = 0x203A
        }
        public enum OpenPunctuation : int
        {
            /// <summary>
            /// SINGLE LOW-9 QUOTATION MARK ‚
            /// </summary>
            SingleLow9QuotationMark = 0x201A,
            /// <summary>
            /// DOUBLE LOW-9 QUOTATION MARK „
            /// </summary>
            DoubleLow9QuotationMark = 0x201E,
            /// <summary>
            /// LEFT SQUARE BRACKET WITH QUILL ⁅
            /// </summary>
            LeftSquareBracketWithQuill = 0x2045
        }
        public enum LineSeparator : int
        {
            /// <summary>
            /// LINE SEPARATOR  
            /// </summary>
            LineSeparator = 0x2028
        }
        public enum ParagraphSeparator : int
        {
            /// <summary>
            /// PARAGRAPH SEPARATOR  
            /// </summary>
            ParagraphSeparator = 0x2029
        }
        public enum ConnectorPunctuation : int
        {
            /// <summary>
            /// UNDERTIE ‿
            /// </summary>
            Undertie = 0x203F,
            /// <summary>
            /// CHARACTER TIE ⁀
            /// </summary>
            CharacterTie = 0x2040,
            /// <summary>
            /// INVERTED UNDERTIE ⁔
            /// </summary>
            InvertedUndertie = 0x2054
        }
        public enum MathSymbol : int
        {
            /// <summary>
            /// FRACTION SLASH ⁄
            /// </summary>
            FractionSlash = 0x2044,
            /// <summary>
            /// COMMERCIAL MINUS SIGN ⁒
            /// </summary>
            CommercialMinusSign = 0x2052
        }
        public enum ClosePunctuation : int
        {
            /// <summary>
            /// RIGHT SQUARE BRACKET WITH QUILL ⁆
            /// </summary>
            RightSquareBracketWithQuill = 0x2046
        }
        public enum OtherNotAssigned : int
        {
        }
    }
}
