// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class Tagbanwa
    {
        public enum OtherLetter : int
        {
            /// <summary>
            /// TAGBANWA LETTER A ᝠ
            /// </summary>
            TagbanwaLetterA = 0x1760,
            /// <summary>
            /// TAGBANWA LETTER I ᝡ
            /// </summary>
            TagbanwaLetterI = 0x1761,
            /// <summary>
            /// TAGBANWA LETTER U ᝢ
            /// </summary>
            TagbanwaLetterU = 0x1762,
            /// <summary>
            /// TAGBANWA LETTER KA ᝣ
            /// </summary>
            TagbanwaLetterKa = 0x1763,
            /// <summary>
            /// TAGBANWA LETTER GA ᝤ
            /// </summary>
            TagbanwaLetterGa = 0x1764,
            /// <summary>
            /// TAGBANWA LETTER NGA ᝥ
            /// </summary>
            TagbanwaLetterNga = 0x1765,
            /// <summary>
            /// TAGBANWA LETTER TA ᝦ
            /// </summary>
            TagbanwaLetterTa = 0x1766,
            /// <summary>
            /// TAGBANWA LETTER DA ᝧ
            /// </summary>
            TagbanwaLetterDa = 0x1767,
            /// <summary>
            /// TAGBANWA LETTER NA ᝨ
            /// </summary>
            TagbanwaLetterNa = 0x1768,
            /// <summary>
            /// TAGBANWA LETTER PA ᝩ
            /// </summary>
            TagbanwaLetterPa = 0x1769,
            /// <summary>
            /// TAGBANWA LETTER BA ᝪ
            /// </summary>
            TagbanwaLetterBa = 0x176A,
            /// <summary>
            /// TAGBANWA LETTER MA ᝫ
            /// </summary>
            TagbanwaLetterMa = 0x176B,
            /// <summary>
            /// TAGBANWA LETTER YA ᝬ
            /// </summary>
            TagbanwaLetterYa = 0x176C,
            /// <summary>
            /// TAGBANWA LETTER LA ᝮ
            /// </summary>
            TagbanwaLetterLa = 0x176E,
            /// <summary>
            /// TAGBANWA LETTER WA ᝯ
            /// </summary>
            TagbanwaLetterWa = 0x176F,
            /// <summary>
            /// TAGBANWA LETTER SA ᝰ
            /// </summary>
            TagbanwaLetterSa = 0x1770
        }
        public enum NonSpacingMark : int
        {
            /// <summary>
            /// TAGBANWA VOWEL SIGN I ᝲ
            /// </summary>
            TagbanwaVowelSignI = 0x1772,
            /// <summary>
            /// TAGBANWA VOWEL SIGN U ᝳ
            /// </summary>
            TagbanwaVowelSignU = 0x1773
        }
    }
}
