// Licensed to Schroedinger Entertainment (SOE) under the terms of the AGPLv3
// Distributed under the Schroedinger Entertainment EULA (See EULA.md for details

using System;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Soe.Unicode
{
    #if EXPORT_HAMPER_CORE_UNICODE
    public
    #else
    internal
    #endif
    static class Telugu
    {
        public enum NonSpacingMark : int
        {
            /// <summary>
            /// TELUGU SIGN COMBINING CANDRABINDU ABOVE ఀ
            /// </summary>
            TeluguSignCombiningCandrabinduAbove = 0x0C00,
            /// <summary>
            /// TELUGU VOWEL SIGN AA ా
            /// </summary>
            TeluguVowelSignAa = 0x0C3E,
            /// <summary>
            /// TELUGU VOWEL SIGN I ి
            /// </summary>
            TeluguVowelSignI = 0x0C3F,
            /// <summary>
            /// TELUGU VOWEL SIGN II ీ
            /// </summary>
            TeluguVowelSignIi = 0x0C40,
            /// <summary>
            /// TELUGU VOWEL SIGN E ె
            /// </summary>
            TeluguVowelSignE = 0x0C46,
            /// <summary>
            /// TELUGU VOWEL SIGN EE ే
            /// </summary>
            TeluguVowelSignEe = 0x0C47,
            /// <summary>
            /// TELUGU VOWEL SIGN AI ై
            /// </summary>
            TeluguVowelSignAi = 0x0C48,
            /// <summary>
            /// TELUGU VOWEL SIGN O ొ
            /// </summary>
            TeluguVowelSignO = 0x0C4A,
            /// <summary>
            /// TELUGU VOWEL SIGN OO ో
            /// </summary>
            TeluguVowelSignOo = 0x0C4B,
            /// <summary>
            /// TELUGU VOWEL SIGN AU ౌ
            /// </summary>
            TeluguVowelSignAu = 0x0C4C,
            /// <summary>
            /// TELUGU SIGN VIRAMA ్
            /// </summary>
            TeluguSignVirama = 0x0C4D,
            /// <summary>
            /// TELUGU LENGTH MARK ౕ
            /// </summary>
            TeluguLengthMark = 0x0C55,
            /// <summary>
            /// TELUGU AI LENGTH MARK ౖ
            /// </summary>
            TeluguAiLengthMark = 0x0C56,
            /// <summary>
            /// TELUGU VOWEL SIGN VOCALIC L ౢ
            /// </summary>
            TeluguVowelSignVocalicL = 0x0C62,
            /// <summary>
            /// TELUGU VOWEL SIGN VOCALIC LL ౣ
            /// </summary>
            TeluguVowelSignVocalicLl = 0x0C63
        }
        public enum SpacingCombiningMark : int
        {
            /// <summary>
            /// TELUGU SIGN CANDRABINDU ఁ
            /// </summary>
            TeluguSignCandrabindu = 0x0C01,
            /// <summary>
            /// TELUGU SIGN ANUSVARA ం
            /// </summary>
            TeluguSignAnusvara = 0x0C02,
            /// <summary>
            /// TELUGU SIGN VISARGA ః
            /// </summary>
            TeluguSignVisarga = 0x0C03,
            /// <summary>
            /// TELUGU VOWEL SIGN U ు
            /// </summary>
            TeluguVowelSignU = 0x0C41,
            /// <summary>
            /// TELUGU VOWEL SIGN UU ూ
            /// </summary>
            TeluguVowelSignUu = 0x0C42,
            /// <summary>
            /// TELUGU VOWEL SIGN VOCALIC R ృ
            /// </summary>
            TeluguVowelSignVocalicR = 0x0C43,
            /// <summary>
            /// TELUGU VOWEL SIGN VOCALIC RR ౄ
            /// </summary>
            TeluguVowelSignVocalicRr = 0x0C44
        }
        public enum OtherLetter : int
        {
            /// <summary>
            /// TELUGU LETTER A అ
            /// </summary>
            TeluguLetterA = 0x0C05,
            /// <summary>
            /// TELUGU LETTER AA ఆ
            /// </summary>
            TeluguLetterAa = 0x0C06,
            /// <summary>
            /// TELUGU LETTER I ఇ
            /// </summary>
            TeluguLetterI = 0x0C07,
            /// <summary>
            /// TELUGU LETTER II ఈ
            /// </summary>
            TeluguLetterIi = 0x0C08,
            /// <summary>
            /// TELUGU LETTER U ఉ
            /// </summary>
            TeluguLetterU = 0x0C09,
            /// <summary>
            /// TELUGU LETTER UU ఊ
            /// </summary>
            TeluguLetterUu = 0x0C0A,
            /// <summary>
            /// TELUGU LETTER VOCALIC R ఋ
            /// </summary>
            TeluguLetterVocalicR = 0x0C0B,
            /// <summary>
            /// TELUGU LETTER VOCALIC L ఌ
            /// </summary>
            TeluguLetterVocalicL = 0x0C0C,
            /// <summary>
            /// TELUGU LETTER E ఎ
            /// </summary>
            TeluguLetterE = 0x0C0E,
            /// <summary>
            /// TELUGU LETTER EE ఏ
            /// </summary>
            TeluguLetterEe = 0x0C0F,
            /// <summary>
            /// TELUGU LETTER AI ఐ
            /// </summary>
            TeluguLetterAi = 0x0C10,
            /// <summary>
            /// TELUGU LETTER O ఒ
            /// </summary>
            TeluguLetterO = 0x0C12,
            /// <summary>
            /// TELUGU LETTER OO ఓ
            /// </summary>
            TeluguLetterOo = 0x0C13,
            /// <summary>
            /// TELUGU LETTER AU ఔ
            /// </summary>
            TeluguLetterAu = 0x0C14,
            /// <summary>
            /// TELUGU LETTER KA క
            /// </summary>
            TeluguLetterKa = 0x0C15,
            /// <summary>
            /// TELUGU LETTER KHA ఖ
            /// </summary>
            TeluguLetterKha = 0x0C16,
            /// <summary>
            /// TELUGU LETTER GA గ
            /// </summary>
            TeluguLetterGa = 0x0C17,
            /// <summary>
            /// TELUGU LETTER GHA ఘ
            /// </summary>
            TeluguLetterGha = 0x0C18,
            /// <summary>
            /// TELUGU LETTER NGA ఙ
            /// </summary>
            TeluguLetterNga = 0x0C19,
            /// <summary>
            /// TELUGU LETTER CA చ
            /// </summary>
            TeluguLetterCa = 0x0C1A,
            /// <summary>
            /// TELUGU LETTER CHA ఛ
            /// </summary>
            TeluguLetterCha = 0x0C1B,
            /// <summary>
            /// TELUGU LETTER JA జ
            /// </summary>
            TeluguLetterJa = 0x0C1C,
            /// <summary>
            /// TELUGU LETTER JHA ఝ
            /// </summary>
            TeluguLetterJha = 0x0C1D,
            /// <summary>
            /// TELUGU LETTER NYA ఞ
            /// </summary>
            TeluguLetterNya = 0x0C1E,
            /// <summary>
            /// TELUGU LETTER TTA ట
            /// </summary>
            TeluguLetterTta = 0x0C1F,
            /// <summary>
            /// TELUGU LETTER TTHA ఠ
            /// </summary>
            TeluguLetterTtha = 0x0C20,
            /// <summary>
            /// TELUGU LETTER DDA డ
            /// </summary>
            TeluguLetterDda = 0x0C21,
            /// <summary>
            /// TELUGU LETTER DDHA ఢ
            /// </summary>
            TeluguLetterDdha = 0x0C22,
            /// <summary>
            /// TELUGU LETTER NNA ణ
            /// </summary>
            TeluguLetterNna = 0x0C23,
            /// <summary>
            /// TELUGU LETTER TA త
            /// </summary>
            TeluguLetterTa = 0x0C24,
            /// <summary>
            /// TELUGU LETTER THA థ
            /// </summary>
            TeluguLetterTha = 0x0C25,
            /// <summary>
            /// TELUGU LETTER DA ద
            /// </summary>
            TeluguLetterDa = 0x0C26,
            /// <summary>
            /// TELUGU LETTER DHA ధ
            /// </summary>
            TeluguLetterDha = 0x0C27,
            /// <summary>
            /// TELUGU LETTER NA న
            /// </summary>
            TeluguLetterNa = 0x0C28,
            /// <summary>
            /// TELUGU LETTER PA ప
            /// </summary>
            TeluguLetterPa = 0x0C2A,
            /// <summary>
            /// TELUGU LETTER PHA ఫ
            /// </summary>
            TeluguLetterPha = 0x0C2B,
            /// <summary>
            /// TELUGU LETTER BA బ
            /// </summary>
            TeluguLetterBa = 0x0C2C,
            /// <summary>
            /// TELUGU LETTER BHA భ
            /// </summary>
            TeluguLetterBha = 0x0C2D,
            /// <summary>
            /// TELUGU LETTER MA మ
            /// </summary>
            TeluguLetterMa = 0x0C2E,
            /// <summary>
            /// TELUGU LETTER YA య
            /// </summary>
            TeluguLetterYa = 0x0C2F,
            /// <summary>
            /// TELUGU LETTER RA ర
            /// </summary>
            TeluguLetterRa = 0x0C30,
            /// <summary>
            /// TELUGU LETTER RRA ఱ
            /// </summary>
            TeluguLetterRra = 0x0C31,
            /// <summary>
            /// TELUGU LETTER LA ల
            /// </summary>
            TeluguLetterLa = 0x0C32,
            /// <summary>
            /// TELUGU LETTER LLA ళ
            /// </summary>
            TeluguLetterLla = 0x0C33,
            /// <summary>
            /// TELUGU LETTER LLLA ఴ
            /// </summary>
            TeluguLetterLlla = 0x0C34,
            /// <summary>
            /// TELUGU LETTER VA వ
            /// </summary>
            TeluguLetterVa = 0x0C35,
            /// <summary>
            /// TELUGU LETTER SHA శ
            /// </summary>
            TeluguLetterSha = 0x0C36,
            /// <summary>
            /// TELUGU LETTER SSA ష
            /// </summary>
            TeluguLetterSsa = 0x0C37,
            /// <summary>
            /// TELUGU LETTER SA స
            /// </summary>
            TeluguLetterSa = 0x0C38,
            /// <summary>
            /// TELUGU LETTER HA హ
            /// </summary>
            TeluguLetterHa = 0x0C39,
            /// <summary>
            /// TELUGU SIGN AVAGRAHA ఽ
            /// </summary>
            TeluguSignAvagraha = 0x0C3D,
            /// <summary>
            /// TELUGU LETTER TSA ౘ
            /// </summary>
            TeluguLetterTsa = 0x0C58,
            /// <summary>
            /// TELUGU LETTER DZA ౙ
            /// </summary>
            TeluguLetterDza = 0x0C59,
            /// <summary>
            /// TELUGU LETTER VOCALIC RR ౠ
            /// </summary>
            TeluguLetterVocalicRr = 0x0C60,
            /// <summary>
            /// TELUGU LETTER VOCALIC LL ౡ
            /// </summary>
            TeluguLetterVocalicLl = 0x0C61
        }
        public enum DecimalDigitNumber : int
        {
            /// <summary>
            /// TELUGU DIGIT ZERO ౦
            /// </summary>
            TeluguDigitZero = 0x0C66,
            /// <summary>
            /// TELUGU DIGIT ONE ౧
            /// </summary>
            TeluguDigitOne = 0x0C67,
            /// <summary>
            /// TELUGU DIGIT TWO ౨
            /// </summary>
            TeluguDigitTwo = 0x0C68,
            /// <summary>
            /// TELUGU DIGIT THREE ౩
            /// </summary>
            TeluguDigitThree = 0x0C69,
            /// <summary>
            /// TELUGU DIGIT FOUR ౪
            /// </summary>
            TeluguDigitFour = 0x0C6A,
            /// <summary>
            /// TELUGU DIGIT FIVE ౫
            /// </summary>
            TeluguDigitFive = 0x0C6B,
            /// <summary>
            /// TELUGU DIGIT SIX ౬
            /// </summary>
            TeluguDigitSix = 0x0C6C,
            /// <summary>
            /// TELUGU DIGIT SEVEN ౭
            /// </summary>
            TeluguDigitSeven = 0x0C6D,
            /// <summary>
            /// TELUGU DIGIT EIGHT ౮
            /// </summary>
            TeluguDigitEight = 0x0C6E,
            /// <summary>
            /// TELUGU DIGIT NINE ౯
            /// </summary>
            TeluguDigitNine = 0x0C6F
        }
        public enum OtherNumber : int
        {
            /// <summary>
            /// TELUGU FRACTION DIGIT ZERO FOR ODD POWERS OF FOUR ౸
            /// </summary>
            TeluguFractionDigitZeroForOddPowersOfFour = 0x0C78,
            /// <summary>
            /// TELUGU FRACTION DIGIT ONE FOR ODD POWERS OF FOUR ౹
            /// </summary>
            TeluguFractionDigitOneForOddPowersOfFour = 0x0C79,
            /// <summary>
            /// TELUGU FRACTION DIGIT TWO FOR ODD POWERS OF FOUR ౺
            /// </summary>
            TeluguFractionDigitTwoForOddPowersOfFour = 0x0C7A,
            /// <summary>
            /// TELUGU FRACTION DIGIT THREE FOR ODD POWERS OF FOUR ౻
            /// </summary>
            TeluguFractionDigitThreeForOddPowersOfFour = 0x0C7B,
            /// <summary>
            /// TELUGU FRACTION DIGIT ONE FOR EVEN POWERS OF FOUR ౼
            /// </summary>
            TeluguFractionDigitOneForEvenPowersOfFour = 0x0C7C,
            /// <summary>
            /// TELUGU FRACTION DIGIT TWO FOR EVEN POWERS OF FOUR ౽
            /// </summary>
            TeluguFractionDigitTwoForEvenPowersOfFour = 0x0C7D,
            /// <summary>
            /// TELUGU FRACTION DIGIT THREE FOR EVEN POWERS OF FOUR ౾
            /// </summary>
            TeluguFractionDigitThreeForEvenPowersOfFour = 0x0C7E
        }
        public enum OtherSymbol : int
        {
            /// <summary>
            /// TELUGU SIGN TUUMU ౿
            /// </summary>
            TeluguSignTuumu = 0x0C7F
        }
    }
}
